// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

pub type ASN1_BIT_STRING = isize;
pub type ASN1_BMPSTRING = isize;
pub type ASN1_BOOLEAN = i32;
pub type ASN1_ENUMERATED = isize;
pub type ASN1_GENERALIZEDTIME = isize;
pub type ASN1_GENERALSTRING = isize;
pub type ASN1_IA5STRING = isize;
pub type ASN1_INTEGER = isize;
pub type ASN1_ITEM = isize;
pub type ASN1_NULL = i32;
pub type ASN1_OBJECT = isize;
pub type ASN1_OCTET_STRING = isize;
pub type ASN1_PCTX = isize;
pub type ASN1_PRINTABLESTRING = isize;
pub type ASN1_SCTX = isize;
pub type ASN1_STRING = isize;
pub type ASN1_STRING_TABLE = isize;
pub type ASN1_T61STRING = isize;
pub type ASN1_TIME = isize;
pub type ASN1_TYPE = isize;
pub type ASN1_UNIVERSALSTRING = isize;
pub type ASN1_UTCTIME = isize;
pub type ASN1_UTF8STRING = isize;
pub type ASN1_VISIBLESTRING = isize;
pub type AUTHORITY_KEYID = isize;
pub type BIGNUM = isize;
pub type BIO = isize;
pub type BN_BLINDING = isize;
pub type BN_CTX = isize;
pub type BN_GENCB = isize;
pub type BN_MONT_CTX = isize;
pub type BN_RECP_CTX = isize;
pub type BUF_MEM = isize;
pub type COMP_CTX = isize;
pub type COMP_METHOD = isize;
pub type CONF = isize;
pub type CRYPTO_EX_DATA = isize;
pub type CTLOG = isize;
pub type CTLOG_STORE = isize;
pub type CT_POLICY_EVAL_CTX = isize;
pub type DH = isize;
pub type DH_METHOD = isize;
pub type DIST_POINT = isize;
pub type DSA = isize;
pub type DSA_METHOD = isize;
pub type EC_KEY = isize;
pub type EC_KEY_METHOD = isize;
pub type ENGINE = isize;
pub type ERR_STATE = isize;
pub type EVP_ASYM_CIPHER = isize;
pub type EVP_CIPHER = isize;
pub type EVP_CIPHER_CTX = isize;
pub type EVP_ENCODE_CTX = isize;
pub type EVP_KDF = isize;
pub type EVP_KDF_CTX = isize;
pub type EVP_KEM = isize;
pub type EVP_KEYEXCH = isize;
pub type EVP_KEYMGMT = isize;
pub type EVP_MAC = isize;
pub type EVP_MAC_CTX = isize;
pub type EVP_MD = isize;
pub type EVP_MD_CTX = isize;
pub type EVP_PKEY = isize;
pub type EVP_PKEY_ASN1_METHOD = isize;
pub type EVP_PKEY_CTX = isize;
pub type EVP_PKEY_METHOD = isize;
pub type EVP_RAND = isize;
pub type EVP_RAND_CTX = isize;
pub type EVP_SIGNATURE = isize;
pub type EVP_SKEY = isize;
pub type EVP_SKEYMGMT = isize;
pub type HMAC_CTX = isize;
pub type ISSUING_DIST_POINT = isize;
pub type NAME_CONSTRAINTS = isize;
pub type OCSP_RESPID = isize;
pub type OCSP_RESPONSE = isize;
pub type OPENSSL_INIT_SETTINGS = isize;
pub type OSSL_ALGORITHM = isize;
pub type OSSL_DECODER = isize;
pub type OSSL_DECODER_CTX = isize;
pub type OSSL_DISPATCH = isize;
pub type OSSL_ENCODER = isize;
pub type OSSL_ENCODER_CTX = isize;
pub type OSSL_HTTP_REQ_CTX = isize;
pub type OSSL_ITEM = isize;
pub type OSSL_LIB_CTX = isize;
pub type OSSL_PARAM = isize;
pub type OSSL_PARAM_BLD = isize;
pub type OSSL_PROVIDER = isize;
pub type OSSL_SELF_TEST = isize;
pub type OSSL_STORE_INFO = isize;
pub type OSSL_STORE_SEARCH = isize;
pub type PKCS8_PRIV_KEY_INFO = isize;
pub type RAND_DRBG = isize;
pub type RAND_METHOD = isize;
pub type RSA = isize;
pub type RSA_METHOD = isize;
pub type RSA_PSS_PARAMS = isize;
pub type SCT = isize;
pub type SCT_CTX = isize;
pub type SSL = isize;
pub type SSL_CTX = isize;
pub type SSL_DANE = isize;
pub type UI = isize;
pub type UI_METHOD = isize;
pub type X509 = isize;
pub type X509V3_CTX = isize;
pub type X509_ALGOR = isize;
pub type X509_CRL = isize;
pub type X509_CRL_METHOD = isize;
pub type X509_LOOKUP = isize;
pub type X509_LOOKUP_METHOD = isize;
pub type X509_NAME = isize;
pub type X509_OBJECT = isize;
pub type X509_POLICY_CACHE = isize;
pub type X509_POLICY_LEVEL = isize;
pub type X509_POLICY_NODE = isize;
pub type X509_POLICY_TREE = isize;
pub type X509_PUBKEY = isize;
pub type X509_REVOKED = isize;
pub type X509_SIG_INFO = isize;
pub type X509_STORE = isize;
pub type X509_STORE_CTX = isize;
pub type X509_VERIFY_PARAM = isize;
pub type pem_password_cb = Option<
    unsafe extern "system" fn(
        param0: *const i8,
        param1: i32,
        param2: i32,
        param3: *const core::ffi::c_void,
    ) -> i32,
>;
