// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("c" "C" fn dlclose(__handle : *mut core::ffi::c_void) -> i32);
windows_link::link!("c" "C" fn dlerror() -> *mut i8);
windows_link::link!("c" "C" fn dlopen(__file : *const i8, __mode : i32) -> *mut core::ffi::c_void);
windows_link::link!("c" "C" fn dlsym(__handle : *mut core::ffi::c_void, __name : *const i8) -> *mut core::ffi::c_void);
pub const RTLD_BINDING_MASK: i32 = 3i32;
pub const RTLD_DEEPBIND: i32 = 8i32;
pub const RTLD_GLOBAL: i32 = 256i32;
pub const RTLD_LAZY: i32 = 1i32;
pub const RTLD_LOCAL: i32 = 0i32;
pub const RTLD_NODELETE: i32 = 4096i32;
pub const RTLD_NOLOAD: i32 = 4i32;
pub const RTLD_NOW: i32 = 2i32;
pub const _DLFCN_H: i32 = 1i32;
