// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(feature = "posix_dirent")]
pub mod dirent;
#[cfg(feature = "posix_dl")]
pub mod dl;
#[cfg(feature = "posix_errno")]
pub mod errno;
#[cfg(feature = "posix_fcntl")]
pub mod fcntl;
#[cfg(feature = "posix_inet")]
pub mod inet;
#[cfg(feature = "posix_mmap")]
pub mod mmap;
#[cfg(feature = "posix_netdb")]
pub mod netdb;
#[cfg(feature = "posix_pthread")]
pub mod pthread;
#[cfg(feature = "posix_sched")]
pub mod sched;
#[cfg(feature = "posix_signal")]
pub mod signal;
#[cfg(feature = "posix_socket")]
pub mod socket;
#[cfg(feature = "posix_stat")]
pub mod stat;
#[cfg(feature = "posix_stdio")]
pub mod stdio;
#[cfg(feature = "posix_time")]
pub mod time;
#[cfg(feature = "posix_types")]
pub mod types;
#[cfg(feature = "posix_unistd")]
pub mod unistd;
