// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("c" "C" fn epoll_create(__size : i32) -> i32);
windows_link::link!("c" "C" fn epoll_create1(__flags : i32) -> i32);
windows_link::link!("c" "C" fn epoll_ctl(__epfd : i32, __op : i32, __fd : i32, __event : *mut epoll_event) -> i32);
windows_link::link!("c" "C" fn epoll_pwait(__epfd : i32, __events : *mut epoll_event, __maxevents : i32, __timeout : i32, __ss : *const bnd_posix::posix::signal:: __sigset_t) -> i32);
windows_link::link!("c" "C" fn epoll_pwait2(__epfd : i32, __events : *mut epoll_event, __maxevents : i32, __timeout : *const bnd_posix::posix::stat:: timespec, __ss : *const bnd_posix::posix::signal:: __sigset_t) -> i32);
windows_link::link!("c" "C" fn epoll_wait(__epfd : i32, __events : *mut epoll_event, __maxevents : i32, __timeout : i32) -> i32);
pub const EPOLLERR: u32 = 8u32;
pub const EPOLLET: u32 = 2147483648u32;
pub const EPOLLEXCLUSIVE: u32 = 268435456u32;
pub const EPOLLHUP: u32 = 16u32;
pub const EPOLLIN: u32 = 1u32;
pub const EPOLLMSG: u32 = 1024u32;
pub const EPOLLONESHOT: u32 = 1073741824u32;
pub const EPOLLOUT: u32 = 4u32;
pub const EPOLLPRI: u32 = 2u32;
pub const EPOLLRDBAND: u32 = 128u32;
pub const EPOLLRDHUP: u32 = 8192u32;
pub const EPOLLRDNORM: u32 = 64u32;
pub const EPOLLWAKEUP: u32 = 536870912u32;
pub const EPOLLWRBAND: u32 = 512u32;
pub const EPOLLWRNORM: u32 = 256u32;
pub const EPOLL_CLOEXEC: u32 = 524288u32;
pub const EPOLL_CTL_ADD: i32 = 1i32;
pub const EPOLL_CTL_DEL: i32 = 2i32;
pub const EPOLL_CTL_MOD: i32 = 3i32;
pub type EPOLL_EVENTS = u32;
pub const _SYS_EPOLL_H: i32 = 1i32;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub union epoll_data {
    pub ptr: *mut core::ffi::c_void,
    pub fd: i32,
    pub u32: u32,
    pub u64: u64,
}
impl Default for epoll_data {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct epoll_data_t {
    pub Value: epoll_data,
}
impl Default for epoll_data_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(1))]
#[derive(Clone, Copy)]
pub struct epoll_event {
    pub events: u32,
    pub data: epoll_data_t,
}
impl Default for epoll_event {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
