// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("simple" "C" fn create_widget(name : *const i8, bounds : Rect, out : *const Widget) -> i32);
windows_link::link!("simple" "C" fn destroy_widget(w : *const Widget));
windows_link::link!("simple" "C" fn widget_count() -> i32);
pub const COLOR_BLUE: u32 = 2u32;
pub const COLOR_GREEN: u32 = 1u32;
pub const COLOR_RED: u32 = 0u32;
pub type Color = u32;
pub type CompareFunc = Option<
    unsafe extern "system" fn(
        param0: *const core::ffi::c_void,
        param1: *const core::ffi::c_void,
    ) -> i32,
>;
pub const DEFAULT_HEIGHT: i32 = 600i32;
pub const DEFAULT_WIDTH: i32 = 800i32;
pub const MAX_WIDGETS: i32 = 256i32;
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub struct NetAddr {
    pub addr: NetAddr_addr,
    pub scope_id: u32,
}
impl Default for NetAddr {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub union NetAddr_addr {
    pub bytes: [u8; 16],
    pub words: [u16; 8],
    pub dwords: [u32; 4],
}
impl Default for NetAddr_addr {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[derive(Clone, Copy, Default)]
pub struct Rect {
    pub x: i32,
    pub y: i32,
    pub width: u32,
    pub height: u32,
}
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub union Value {
    pub i: i32,
    pub f: f32,
    pub bytes: [u8; 4],
}
impl Default for Value {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct Widget {
    pub name: *mut i8,
    pub values: [i32; 4],
    pub color: Color,
}
impl Default for Widget {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
