// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

pub type __be16 = u16;
pub type __be32 = u32;
pub type __be64 = u64;
pub type __le16 = u16;
pub type __le32 = u32;
pub type __le64 = u64;
pub type __poll_t = u32;
pub type __sum16 = u16;
pub type __wsum = u32;
