// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(feature = "Fcntl")]
pub mod Fcntl;
#[cfg(feature = "Stat")]
pub mod Stat;
#[cfg(feature = "Unistd")]
pub mod Unistd;
