// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(feature = "Dirent")]
pub mod Dirent;
#[cfg(feature = "Fcntl")]
pub mod Fcntl;
#[cfg(feature = "Inet")]
pub mod Inet;
#[cfg(feature = "Mmap")]
pub mod Mmap;
#[cfg(feature = "Netdb")]
pub mod Netdb;
#[cfg(feature = "Socket")]
pub mod Socket;
#[cfg(feature = "Stat")]
pub mod Stat;
#[cfg(feature = "Unistd")]
pub mod Unistd;
