[package]
name = "bnd-openssl-clang"
version = "0.0.0"
edition.workspace = true
description = "Staging crate for OpenSSL bindings generated through bnd-clang"
authors.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
publish = false

[dependencies]
bnd-linux-clang = { path = "../bnd-linux-clang", default-features = false, features = [
    "file",
    "netdb",
    "pthreadtypes",
    "struct_timeval",
    "struct_tm",
    "time_t",
    "types",
] }
bnd-macros.workspace = true

[features]
default = ["bio", "bn", "crypto", "evp", "rand", "sha", "ssl", "types"]
Foundation = []
# generated features
asn1 = ["types"]
bio = ["core", "types"]
bn = ["crypto", "types"]
buffer = []
comp = []
conf = ["conftypes"]
conftypes = ["conf", "types"]
core = ["types"]
crypto = ["core", "types"]
evp = ["asn1", "bio", "core", "types", "x509"]
rand = ["types"]
rsa = ["asn1", "types", "x509"]
sha = []
ssl = ["bio", "comp", "core", "tls1", "types"]
tls1 = ["types"]
types = ["asn1", "buffer", "conf", "conftypes", "core", "crypto", "rand", "rsa", "x509"]
x509 = ["asn1", "types"]
