// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(feature = "epoll")]
pub mod epoll;
#[cfg(feature = "eventfd")]
pub mod eventfd;
#[cfg(feature = "inotify")]
pub mod inotify;
#[cfg(feature = "mount")]
pub mod mount;
#[cfg(feature = "sendfile")]
pub mod sendfile;
#[cfg(feature = "signalfd")]
pub mod signalfd;
#[cfg(feature = "timerfd")]
pub mod timerfd;
#[cfg(feature = "xattr")]
pub mod xattr;
