// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("z" "C" fn adler32(adler : uLong, buf : *const Bytef, len : uInt) -> uLong);
windows_link::link!("z" "C" fn adler32_combine(param0 : uLong, param1 : uLong, param2 : i64) -> uLong);
windows_link::link!("z" "C" fn adler32_z(adler : uLong, buf : *const Bytef, len : z_size_t) -> uLong);
windows_link::link!("z" "C" fn compress(dest : *mut Bytef, destlen : *mut uLongf, source : *const Bytef, sourcelen : uLong) -> i32);
windows_link::link!("z" "C" fn compress2(dest : *mut Bytef, destlen : *mut uLongf, source : *const Bytef, sourcelen : uLong, level : i32) -> i32);
windows_link::link!("z" "C" fn compressBound(sourcelen : uLong) -> uLong);
windows_link::link!("z" "C" fn crc32(crc : uLong, buf : *const Bytef, len : uInt) -> uLong);
windows_link::link!("z" "C" fn crc32_combine(param0 : uLong, param1 : uLong, param2 : i64) -> uLong);
windows_link::link!("z" "C" fn crc32_combine_gen(param0 : i64) -> uLong);
windows_link::link!("z" "C" fn crc32_combine_op(crc1 : uLong, crc2 : uLong, op : uLong) -> uLong);
windows_link::link!("z" "C" fn crc32_z(crc : uLong, buf : *const Bytef, len : z_size_t) -> uLong);
windows_link::link!("z" "C" fn deflate(strm : z_streamp, flush : i32) -> i32);
windows_link::link!("z" "C" fn deflateBound(strm : z_streamp, sourcelen : uLong) -> uLong);
windows_link::link!("z" "C" fn deflateCopy(dest : z_streamp, source : z_streamp) -> i32);
windows_link::link!("z" "C" fn deflateEnd(strm : z_streamp) -> i32);
windows_link::link!("z" "C" fn deflateGetDictionary(strm : z_streamp, dictionary : *mut Bytef, dictlength : *mut uInt) -> i32);
windows_link::link!("z" "C" fn deflateInit2_(strm : z_streamp, level : i32, method : i32, windowbits : i32, memlevel : i32, strategy : i32, version : *const i8, stream_size : i32) -> i32);
windows_link::link!("z" "C" fn deflateInit_(strm : z_streamp, level : i32, version : *const i8, stream_size : i32) -> i32);
windows_link::link!("z" "C" fn deflateParams(strm : z_streamp, level : i32, strategy : i32) -> i32);
windows_link::link!("z" "C" fn deflatePending(strm : z_streamp, pending : *mut u32, bits : *mut i32) -> i32);
windows_link::link!("z" "C" fn deflatePrime(strm : z_streamp, bits : i32, value : i32) -> i32);
windows_link::link!("z" "C" fn deflateReset(strm : z_streamp) -> i32);
windows_link::link!("z" "C" fn deflateResetKeep(param0 : z_streamp) -> i32);
windows_link::link!("z" "C" fn deflateSetDictionary(strm : z_streamp, dictionary : *const Bytef, dictlength : uInt) -> i32);
windows_link::link!("z" "C" fn deflateSetHeader(strm : z_streamp, head : gz_headerp) -> i32);
windows_link::link!("z" "C" fn deflateTune(strm : z_streamp, good_length : i32, max_lazy : i32, nice_length : i32, max_chain : i32) -> i32);
windows_link::link!("z" "C" fn get_crc_table() -> *mut z_crc_t);
windows_link::link!("z" "C" fn gzbuffer(file : gzFile, size : u32) -> i32);
windows_link::link!("z" "C" fn gzclearerr(file : gzFile));
windows_link::link!("z" "C" fn gzclose(file : gzFile) -> i32);
windows_link::link!("z" "C" fn gzclose_r(file : gzFile) -> i32);
windows_link::link!("z" "C" fn gzclose_w(file : gzFile) -> i32);
windows_link::link!("z" "C" fn gzdirect(file : gzFile) -> i32);
windows_link::link!("z" "C" fn gzdopen(fd : i32, mode : *const i8) -> gzFile);
windows_link::link!("z" "C" fn gzeof(file : gzFile) -> i32);
windows_link::link!("z" "C" fn gzerror(file : gzFile, errnum : *mut i32) -> *mut i8);
windows_link::link!("z" "C" fn gzflush(file : gzFile, flush : i32) -> i32);
windows_link::link!("z" "C" fn gzfread(buf : voidp, size : z_size_t, nitems : z_size_t, file : gzFile) -> z_size_t);
windows_link::link!("z" "C" fn gzfwrite(buf : voidpc, size : z_size_t, nitems : z_size_t, file : gzFile) -> z_size_t);
windows_link::link!("z" "C" fn gzgetc(file : gzFile) -> i32);
windows_link::link!("z" "C" fn gzgetc_(file : gzFile) -> i32);
windows_link::link!("z" "C" fn gzgets(file : gzFile, buf : *mut i8, len : i32) -> *mut i8);
windows_link::link!("z" "C" fn gzoffset(param0 : gzFile) -> i64);
windows_link::link!("z" "C" fn gzopen(param0 : *const i8, param1 : *const i8) -> gzFile);
windows_link::link!("z" "C" fn gzputc(file : gzFile, c : i32) -> i32);
windows_link::link!("z" "C" fn gzputs(file : gzFile, s : *const i8) -> i32);
windows_link::link!("z" "C" fn gzread(file : gzFile, buf : voidp, len : u32) -> i32);
windows_link::link!("z" "C" fn gzrewind(file : gzFile) -> i32);
windows_link::link!("z" "C" fn gzseek(param0 : gzFile, param1 : i64, param2 : i32) -> i64);
windows_link::link!("z" "C" fn gzsetparams(file : gzFile, level : i32, strategy : i32) -> i32);
windows_link::link!("z" "C" fn gztell(param0 : gzFile) -> i64);
windows_link::link!("z" "C" fn gzungetc(c : i32, file : gzFile) -> i32);
windows_link::link!("z" "C" fn gzvprintf(file : gzFile, format : *const i8, va : *mut core::ffi::c_void) -> i32);
windows_link::link!("z" "C" fn gzwrite(file : gzFile, buf : voidpc, len : u32) -> i32);
windows_link::link!("z" "C" fn inflate(strm : z_streamp, flush : i32) -> i32);
windows_link::link!("z" "C" fn inflateBack(strm : z_streamp, r#in : in_func, in_desc : *mut core::ffi::c_void, out : out_func, out_desc : *mut core::ffi::c_void) -> i32);
windows_link::link!("z" "C" fn inflateBackEnd(strm : z_streamp) -> i32);
windows_link::link!("z" "C" fn inflateBackInit_(strm : z_streamp, windowbits : i32, window : *mut u8, version : *const i8, stream_size : i32) -> i32);
windows_link::link!("z" "C" fn inflateCodesUsed(param0 : z_streamp) -> u64);
windows_link::link!("z" "C" fn inflateCopy(dest : z_streamp, source : z_streamp) -> i32);
windows_link::link!("z" "C" fn inflateEnd(strm : z_streamp) -> i32);
windows_link::link!("z" "C" fn inflateGetDictionary(strm : z_streamp, dictionary : *mut Bytef, dictlength : *mut uInt) -> i32);
windows_link::link!("z" "C" fn inflateGetHeader(strm : z_streamp, head : gz_headerp) -> i32);
windows_link::link!("z" "C" fn inflateInit2_(strm : z_streamp, windowbits : i32, version : *const i8, stream_size : i32) -> i32);
windows_link::link!("z" "C" fn inflateInit_(strm : z_streamp, version : *const i8, stream_size : i32) -> i32);
windows_link::link!("z" "C" fn inflateMark(strm : z_streamp) -> i64);
windows_link::link!("z" "C" fn inflatePrime(strm : z_streamp, bits : i32, value : i32) -> i32);
windows_link::link!("z" "C" fn inflateReset(strm : z_streamp) -> i32);
windows_link::link!("z" "C" fn inflateReset2(strm : z_streamp, windowbits : i32) -> i32);
windows_link::link!("z" "C" fn inflateResetKeep(param0 : z_streamp) -> i32);
windows_link::link!("z" "C" fn inflateSetDictionary(strm : z_streamp, dictionary : *const Bytef, dictlength : uInt) -> i32);
windows_link::link!("z" "C" fn inflateSync(strm : z_streamp) -> i32);
windows_link::link!("z" "C" fn inflateSyncPoint(param0 : z_streamp) -> i32);
windows_link::link!("z" "C" fn inflateUndermine(param0 : z_streamp, param1 : i32) -> i32);
windows_link::link!("z" "C" fn inflateValidate(param0 : z_streamp, param1 : i32) -> i32);
windows_link::link!("z" "C" fn uncompress(dest : *mut Bytef, destlen : *mut uLongf, source : *const Bytef, sourcelen : uLong) -> i32);
windows_link::link!("z" "C" fn uncompress2(dest : *mut Bytef, destlen : *mut uLongf, source : *const Bytef, sourcelen : *mut uLong) -> i32);
windows_link::link!("z" "C" fn zError(param0 : i32) -> *mut i8);
windows_link::link!("z" "C" fn zlibCompileFlags() -> uLong);
windows_link::link!("z" "C" fn zlibVersion() -> *mut i8);
pub type Byte = u8;
pub type Bytef = Byte;
pub const MAX_MEM_LEVEL: i32 = 9i32;
pub const MAX_WBITS: i32 = 15i32;
pub const ZLIB_VERNUM: i32 = 4864i32;
pub const ZLIB_VER_MAJOR: i32 = 1i32;
pub const ZLIB_VER_MINOR: i32 = 3i32;
pub const ZLIB_VER_REVISION: i32 = 0i32;
pub const ZLIB_VER_SUBREVISION: i32 = 0i32;
pub const Z_BEST_COMPRESSION: i32 = 9i32;
pub const Z_BEST_SPEED: i32 = 1i32;
pub const Z_BINARY: i32 = 0i32;
pub const Z_BLOCK: i32 = 5i32;
pub const Z_DEFAULT_STRATEGY: i32 = 0i32;
pub const Z_DEFLATED: i32 = 8i32;
pub const Z_FILTERED: i32 = 1i32;
pub const Z_FINISH: i32 = 4i32;
pub const Z_FIXED: i32 = 4i32;
pub const Z_FULL_FLUSH: i32 = 3i32;
pub const Z_HUFFMAN_ONLY: i32 = 2i32;
pub const Z_NEED_DICT: i32 = 2i32;
pub const Z_NO_COMPRESSION: i32 = 0i32;
pub const Z_NO_FLUSH: i32 = 0i32;
pub const Z_NULL: i32 = 0i32;
pub const Z_OK: i32 = 0i32;
pub const Z_PARTIAL_FLUSH: i32 = 1i32;
pub const Z_RLE: i32 = 3i32;
pub const Z_STREAM_END: i32 = 1i32;
pub const Z_SYNC_FLUSH: i32 = 2i32;
pub const Z_TEXT: i32 = 1i32;
pub const Z_TREES: i32 = 6i32;
pub const Z_UNKNOWN: i32 = 2i32;
pub type alloc_func =
    Option<unsafe extern "system" fn(param0: voidpf, param1: uInt, param2: uInt) -> voidpf>;
pub type charf = i8;
pub type free_func = Option<unsafe extern "system" fn(param0: voidpf, param1: voidpf)>;
pub type gzFile = *mut gzFile_s;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct gzFile_s {
    pub have: u32,
    pub next: *mut u8,
    pub pos: i64,
}
impl Default for gzFile_s {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct gz_header {
    pub Value: gz_header_s,
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct gz_header_s {
    pub text: i32,
    pub time: uLong,
    pub xflags: i32,
    pub os: i32,
    pub extra: *mut Bytef,
    pub extra_len: uInt,
    pub extra_max: uInt,
    pub name: *mut Bytef,
    pub name_max: uInt,
    pub comment: *mut Bytef,
    pub comm_max: uInt,
    pub hcrc: i32,
    pub done: i32,
}
impl Default for gz_header_s {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type gz_headerp = *mut gz_header;
pub type in_func = Option<
    unsafe extern "system" fn(param0: *const core::ffi::c_void, param1: *const *const u8) -> u32,
>;
pub type intf = i32;
pub type out_func = Option<
    unsafe extern "system" fn(
        param0: *const core::ffi::c_void,
        param1: *const u8,
        param2: u32,
    ) -> i32,
>;
pub type uInt = u32;
pub type uIntf = uInt;
pub type uLong = u64;
pub type uLongf = uLong;
pub type voidp = *mut core::ffi::c_void;
pub type voidpc = *mut core::ffi::c_void;
pub type voidpf = *mut core::ffi::c_void;
pub type z_crc_t = u32;
pub type z_size_t = u64;
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct z_stream {
    pub Value: z_stream_s,
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct z_stream_s {
    pub next_in: *mut Bytef,
    pub avail_in: uInt,
    pub total_in: uLong,
    pub next_out: *mut Bytef,
    pub avail_out: uInt,
    pub total_out: uLong,
    pub msg: *mut i8,
    pub state: *mut core::ffi::c_void,
    pub zalloc: alloc_func,
    pub zfree: free_func,
    pub opaque: voidpf,
    pub data_type: i32,
    pub adler: uLong,
    pub reserved: uLong,
}
impl Default for z_stream_s {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type z_streamp = *mut z_stream;
