[package]
name = "bnd-linux-clang"
version = "0.0.0"
edition.workspace = true
description = "Staging crate for bnd-linux bindings generated through bnd-clang"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
bnd-macros.workspace = true

[dev-dependencies]
libc = "0.2"
tempfile.workspace = true

[features]
default = [
    "__sigset_t",
    "epoll",
    "eventfd",
    "inotify",
    "sendfile",
    "struct_itimerspec",
    "struct_timespec",
    "timerfd",
    "types",
]
Foundation = []
# generated features
__sigset_t = ["Foundation"]
epoll = ["Foundation", "__sigset_t", "struct_timespec", "types"]
eventfd = ["Foundation"]
inotify = ["Foundation"]
sendfile = ["Foundation", "types"]
struct_itimerspec = ["Foundation", "struct_timespec"]
struct_timespec = ["Foundation", "types"]
timerfd = ["Foundation", "struct_itimerspec", "types"]
types = ["Foundation"]
