// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("c" "C" fn __sched_cpualloc(__count : u64) -> *mut cpu_set_t);
windows_link::link!("c" "C" fn __sched_cpucount(__setsize : u64, __setp : *const cpu_set_t) -> i32);
windows_link::link!("c" "C" fn __sched_cpufree(__set : *const cpu_set_t));
windows_link::link!("c" "C" fn sched_get_priority_max(__algorithm : i32) -> i32);
windows_link::link!("c" "C" fn sched_get_priority_min(__algorithm : i32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("c" "C" fn sched_getparam(__pid : super::types:: __pid_t, __param : *const sched_param) -> i32);
#[cfg(feature = "types")]
windows_link::link!("c" "C" fn sched_getscheduler(__pid : super::types:: __pid_t) -> i32);
#[cfg(all(feature = "stat", feature = "types"))]
windows_link::link!("c" "C" fn sched_rr_get_interval(__pid : super::types:: __pid_t, __t : *const super::stat:: timespec) -> i32);
#[cfg(feature = "types")]
windows_link::link!("c" "C" fn sched_setparam(__pid : super::types:: __pid_t, __param : *const sched_param) -> i32);
#[cfg(feature = "types")]
windows_link::link!("c" "C" fn sched_setscheduler(__pid : super::types:: __pid_t, __policy : i32, __param : *const sched_param) -> i32);
windows_link::link!("c" "C" fn sched_yield() -> i32);
pub const SCHED_FIFO: i32 = 1i32;
pub const SCHED_OTHER: i32 = 0i32;
pub const SCHED_RR: i32 = 2i32;
pub const _BITS_CPU_SET_H: i32 = 1i32;
pub const _BITS_SCHED_H: i32 = 1i32;
pub const _BITS_TYPES_STRUCT_SCHED_PARAM: i32 = 1i32;
pub const _SCHED_H: i32 = 1i32;
pub const __CPU_SETSIZE: i32 = 1024i32;
pub type __cpu_mask = u64;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct cpu_set_t {
    pub __bits: [__cpu_mask; 16],
}
impl Default for cpu_set_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[derive(Clone, Copy, Default)]
pub struct sched_param {
    pub sched_priority: i32,
}
