[package]
name = "bnd-clang"
version = "0.0.0"
edition.workspace = true
rust-version = "1.95"
publish = false
license = "MIT OR Apache-2.0"
description = "Experimental bnd fork of windows-clang"
repository.workspace = true
readme = "vendored/windows-clang/readme.md"

[lib]
name = "windows_clang"
path = "vendored/windows-clang/src/lib.rs"

[features]
default = []
runtime = ["clang-sys/runtime"]

[dependencies]
windows-default = { version = "0.100", default-features = false }
windows-rdl = { version = "0.100", default-features = false }
windows-metadata = { version = "0.100", default-features = false }
windows-threading = { version = "0.100", default-features = false }
syn = { version = "3", default-features = false, features = ["full", "parsing", "clone-impls", "printing", "extra-traits"] }
quote = { version = "1", default-features = false }
proc-macro2 = { version = "1", default-features = false }
clang-sys = { version = "1.8.1", features = ["clang_18_0"] }

[dev-dependencies]
tempfile.workspace = true
