// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("c" "C" fn fsconfig(__fd : i32, __cmd : u32, __key : *const i8, __value : *const core::ffi::c_void, __aux : i32) -> i32);
windows_link::link!("c" "C" fn fsmount(__fd : i32, __flags : u32, __ms_flags : u32) -> i32);
windows_link::link!("c" "C" fn fsopen(__fs_name : *const i8, __flags : u32) -> i32);
windows_link::link!("c" "C" fn fspick(__dfd : i32, __path : *const i8, __flags : u32) -> i32);
windows_link::link!("c" "C" fn mount(__special_file : *const i8, __dir : *const i8, __fstype : *const i8, __rwflag : u64, __data : *const core::ffi::c_void) -> i32);
windows_link::link!("c" "C" fn mount_setattr(__dfd : i32, __path : *const i8, __flags : u32, __uattr : *mut mount_attr, __usize : u64) -> i32);
windows_link::link!("c" "C" fn move_mount(__from_dfd : i32, __from_pathname : *const i8, __to_dfd : i32, __to_pathname : *const i8, flags : u32) -> i32);
windows_link::link!("c" "C" fn open_tree(__dfd : i32, __filename : *const i8, __flags : u32) -> i32);
windows_link::link!("c" "C" fn umount(__special_file : *const i8) -> i32);
windows_link::link!("c" "C" fn umount2(__special_file : *const i8, __flags : i32) -> i32);
pub const BLOCK_SIZE_BITS: i32 = 10i32;
pub const FSCONFIG_CMD_CREATE: u32 = 6u32;
pub const FSCONFIG_CMD_CREATE_EXCL: u32 = 8u32;
pub const FSCONFIG_CMD_RECONFIGURE: u32 = 7u32;
pub const FSCONFIG_SET_BINARY: u32 = 2u32;
pub const FSCONFIG_SET_FD: u32 = 5u32;
pub const FSCONFIG_SET_FLAG: u32 = 0u32;
pub const FSCONFIG_SET_PATH: u32 = 3u32;
pub const FSCONFIG_SET_PATH_EMPTY: u32 = 4u32;
pub const FSCONFIG_SET_STRING: u32 = 1u32;
pub const FSMOUNT_CLOEXEC: i32 = 1i32;
pub const FSOPEN_CLOEXEC: i32 = 1i32;
pub const FSPICK_CLOEXEC: i32 = 1i32;
pub const FSPICK_EMPTY_PATH: i32 = 8i32;
pub const FSPICK_NO_AUTOMOUNT: i32 = 4i32;
pub const FSPICK_SYMLINK_NOFOLLOW: i32 = 2i32;
pub const MNT_DETACH: u32 = 2u32;
pub const MNT_EXPIRE: u32 = 4u32;
pub const MNT_FORCE: u32 = 1u32;
pub const MOUNT_ATTR_IDMAP: i32 = 1048576i32;
pub const MOUNT_ATTR_NOATIME: i32 = 16i32;
pub const MOUNT_ATTR_NODEV: i32 = 4i32;
pub const MOUNT_ATTR_NODIRATIME: i32 = 128i32;
pub const MOUNT_ATTR_NOEXEC: i32 = 8i32;
pub const MOUNT_ATTR_NOSUID: i32 = 2i32;
pub const MOUNT_ATTR_NOSYMFOLLOW: i32 = 2097152i32;
pub const MOUNT_ATTR_RDONLY: i32 = 1i32;
pub const MOUNT_ATTR_RELATIME: i32 = 0i32;
pub const MOUNT_ATTR_SIZE_VER0: i32 = 32i32;
pub const MOUNT_ATTR_STRICTATIME: i32 = 32i32;
pub const MOUNT_ATTR__ATIME: i32 = 112i32;
pub const MOVE_MOUNT_BENEATH: i32 = 512i32;
pub const MOVE_MOUNT_F_AUTOMOUNTS: i32 = 2i32;
pub const MOVE_MOUNT_F_EMPTY_PATH: i32 = 4i32;
pub const MOVE_MOUNT_F_SYMLINKS: i32 = 1i32;
pub const MOVE_MOUNT_SET_GROUP: i32 = 256i32;
pub const MOVE_MOUNT_T_AUTOMOUNTS: i32 = 32i32;
pub const MOVE_MOUNT_T_EMPTY_PATH: i32 = 64i32;
pub const MOVE_MOUNT_T_SYMLINKS: i32 = 16i32;
pub const MS_ACTIVE: u32 = 1073741824u32;
pub const MS_BIND: u32 = 4096u32;
pub const MS_DIRSYNC: u32 = 128u32;
pub const MS_I_VERSION: u32 = 8388608u32;
pub const MS_KERNMOUNT: u32 = 4194304u32;
pub const MS_LAZYTIME: u32 = 33554432u32;
pub const MS_MANDLOCK: u32 = 64u32;
pub const MS_MGC_MSK: i32 = -65536i32;
pub const MS_MGC_VAL: i32 = -1058209792i32;
pub const MS_MOVE: u32 = 8192u32;
pub const MS_NOATIME: u32 = 1024u32;
pub const MS_NODEV: u32 = 4u32;
pub const MS_NODIRATIME: u32 = 2048u32;
pub const MS_NOEXEC: u32 = 8u32;
pub const MS_NOSUID: u32 = 2u32;
pub const MS_NOSYMFOLLOW: u32 = 256u32;
pub const MS_NOUSER: i32 = -2147483648i32;
pub const MS_POSIXACL: u32 = 65536u32;
pub const MS_PRIVATE: u32 = 262144u32;
pub const MS_RDONLY: u32 = 1u32;
pub const MS_REC: u32 = 16384u32;
pub const MS_RELATIME: u32 = 2097152u32;
pub const MS_REMOUNT: u32 = 32u32;
pub const MS_SHARED: u32 = 1048576u32;
pub const MS_SILENT: u32 = 32768u32;
pub const MS_SLAVE: u32 = 524288u32;
pub const MS_STRICTATIME: u32 = 16777216u32;
pub const MS_SYNCHRONOUS: u32 = 16u32;
pub const MS_UNBINDABLE: u32 = 131072u32;
pub const OPEN_TREE_CLONE: i32 = 1i32;
pub const UMOUNT_NOFOLLOW: u32 = 8u32;
pub const _SYS_MOUNT_H: i32 = 1i32;
pub type fsconfig_command = u32;
#[repr(C, packed(8))]
#[derive(Clone, Copy, Default)]
pub struct mount_attr {
    pub attr_set: u64,
    pub attr_clr: u64,
    pub propagation: u64,
    pub userns_fd: u64,
}
