// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn __getdelim(__lineptr : *mut *mut i8, __n : *mut u64, __delimiter : i32, __stream : *mut _IO_FILE) -> super::types:: __ssize_t);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn __overflow(param0 : *mut _IO_FILE, param1 : i32) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn __uflow(param0 : *mut _IO_FILE) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn clearerr(__stream : *mut _IO_FILE));
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn clearerr_unlocked(__stream : *mut _IO_FILE));
windows_link::link!("c" "C" fn ctermid(__s : *mut i8) -> *mut i8);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn fclose(__stream : *mut _IO_FILE) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn fdopen(__fd : i32, __modes : *const i8) -> *mut _IO_FILE);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn feof(__stream : *mut _IO_FILE) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn feof_unlocked(__stream : *mut _IO_FILE) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn ferror(__stream : *mut _IO_FILE) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn ferror_unlocked(__stream : *mut _IO_FILE) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn fflush(__stream : *mut _IO_FILE) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn fflush_unlocked(__stream : *mut _IO_FILE) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn fgetc(__stream : *mut _IO_FILE) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn fgetc_unlocked(__stream : *mut _IO_FILE) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn fgetpos(__stream : *mut _IO_FILE, __pos : *mut fpos_t) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn fgets(__s : *mut i8, __n : i32, __stream : *mut _IO_FILE) -> *mut i8);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn fileno(__stream : *mut _IO_FILE) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn fileno_unlocked(__stream : *mut _IO_FILE) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn flockfile(__stream : *mut _IO_FILE));
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn fmemopen(__s : *mut core::ffi::c_void, __len : u64, __modes : *const i8) -> *mut _IO_FILE);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn fopen(__filename : *const i8, __modes : *const i8) -> *mut _IO_FILE);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn fopencookie(__magic_cookie : *mut core::ffi::c_void, __modes : *const i8, __io_funcs : cookie_io_functions_t) -> *mut _IO_FILE);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn fputc(__c : i32, __stream : *mut _IO_FILE) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn fputc_unlocked(__c : i32, __stream : *mut _IO_FILE) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn fputs(__s : *const i8, __stream : *mut _IO_FILE) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn fread(__ptr : *mut core::ffi::c_void, __size : u64, __n : u64, __stream : *mut _IO_FILE) -> u64);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn fread_unlocked(__ptr : *mut core::ffi::c_void, __size : u64, __n : u64, __stream : *mut _IO_FILE) -> u64);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn freopen(__filename : *const i8, __modes : *const i8, __stream : *mut _IO_FILE) -> *mut _IO_FILE);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn fseek(__stream : *mut _IO_FILE, __off : i64, __whence : i32) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn fseeko(__stream : *mut _IO_FILE, __off : super::types:: __off_t, __whence : i32) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn fsetpos(__stream : *mut _IO_FILE, __pos : *const fpos_t) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn ftell(__stream : *mut _IO_FILE) -> i64);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn ftello(__stream : *mut _IO_FILE) -> super::types:: __off_t);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn ftrylockfile(__stream : *mut _IO_FILE) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn funlockfile(__stream : *mut _IO_FILE));
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn fwrite(__ptr : *const core::ffi::c_void, __size : u64, __n : u64, __s : *mut _IO_FILE) -> u64);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn fwrite_unlocked(__ptr : *const core::ffi::c_void, __size : u64, __n : u64, __stream : *mut _IO_FILE) -> u64);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn getc(__stream : *mut _IO_FILE) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn getc_unlocked(__stream : *mut _IO_FILE) -> i32);
windows_link::link!("c" "C" fn getchar() -> i32);
windows_link::link!("c" "C" fn getchar_unlocked() -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn getdelim(__lineptr : *mut *mut i8, __n : *mut u64, __delimiter : i32, __stream : *mut _IO_FILE) -> super::types:: __ssize_t);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn getline(__lineptr : *mut *mut i8, __n : *mut u64, __stream : *mut _IO_FILE) -> super::types:: __ssize_t);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn getw(__stream : *mut _IO_FILE) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn open_memstream(__bufloc : *mut *mut i8, __sizeloc : *mut u64) -> *mut _IO_FILE);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn pclose(__stream : *mut _IO_FILE) -> i32);
windows_link::link!("c" "C" fn perror(__s : *const i8));
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn popen(__command : *const i8, __modes : *const i8) -> *mut _IO_FILE);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn putc(__c : i32, __stream : *mut _IO_FILE) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn putc_unlocked(__c : i32, __stream : *mut _IO_FILE) -> i32);
windows_link::link!("c" "C" fn putchar(__c : i32) -> i32);
windows_link::link!("c" "C" fn putchar_unlocked(__c : i32) -> i32);
windows_link::link!("c" "C" fn puts(__s : *const i8) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn putw(__w : i32, __stream : *mut _IO_FILE) -> i32);
windows_link::link!("c" "C" fn remove(__filename : *const i8) -> i32);
windows_link::link!("c" "C" fn rename(__old : *const i8, __new : *const i8) -> i32);
windows_link::link!("c" "C" fn renameat(__oldfd : i32, __old : *const i8, __newfd : i32, __new : *const i8) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn rewind(__stream : *mut _IO_FILE));
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn setbuf(__stream : *mut _IO_FILE, __buf : *mut i8));
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn setbuffer(__stream : *mut _IO_FILE, __buf : *mut i8, __size : u64));
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn setlinebuf(__stream : *mut _IO_FILE));
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn setvbuf(__stream : *mut _IO_FILE, __buf : *mut i8, __modes : i32, __n : u64) -> i32);
windows_link::link!("c" "C" fn tempnam(__dir : *const i8, __pfx : *const i8) -> *mut i8);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn tmpfile() -> *mut _IO_FILE);
windows_link::link!("c" "C" fn tmpnam(param0 : *mut i8) -> *mut i8);
windows_link::link!("c" "C" fn tmpnam_r(__s : *mut i8) -> *mut i8);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn ungetc(__c : i32, __stream : *mut _IO_FILE) -> i32);
windows_link::link!("c" "C" fn vasprintf(__ptr : *mut *mut i8, __f : *const i8, __arg : *mut core::ffi::c_void) -> i32);
windows_link::link!("c" "C" fn vdprintf(__fd : i32, __fmt : *const i8, __arg : *mut core::ffi::c_void) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn vfprintf(__s : *mut _IO_FILE, __format : *const i8, __arg : *mut core::ffi::c_void) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn vfscanf(__s : *mut _IO_FILE, __format : *const i8, __arg : *mut core::ffi::c_void) -> i32);
windows_link::link!("c" "C" fn vprintf(__format : *const i8, __arg : *mut core::ffi::c_void) -> i32);
windows_link::link!("c" "C" fn vscanf(__format : *const i8, __arg : *mut core::ffi::c_void) -> i32);
windows_link::link!("c" "C" fn vsnprintf(__s : *mut i8, __maxlen : u64, __format : *const i8, __arg : *mut core::ffi::c_void) -> i32);
windows_link::link!("c" "C" fn vsprintf(__s : *mut i8, __format : *const i8, __arg : *mut core::ffi::c_void) -> i32);
windows_link::link!("c" "C" fn vsscanf(__s : *const i8, __format : *const i8, __arg : *mut core::ffi::c_void) -> i32);
pub const BUFSIZ: i32 = 8192i32;
pub const FILENAME_MAX: i32 = 4096i32;
pub const FOPEN_MAX: i32 = 16i32;
pub const L_ctermid: i32 = 9i32;
pub const L_tmpnam: i32 = 20i32;
pub const SEEK_CUR: i32 = 1i32;
pub const SEEK_END: i32 = 2i32;
pub const SEEK_SET: i32 = 0i32;
pub const TMP_MAX: i32 = 238328i32;
pub const _BITS_STDIO_LIM_H: i32 = 1i32;
#[repr(C, packed(8))]
#[cfg(feature = "posix_types")]
#[derive(Clone, Copy)]
pub struct _G_fpos_t {
    pub __pos: super::types::__off_t,
    pub __state: __mbstate_t,
}
#[cfg(feature = "posix_types")]
impl Default for _G_fpos_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub const _IOFBF: i32 = 0i32;
pub const _IOLBF: i32 = 1i32;
pub const _IONBF: i32 = 2i32;
pub const _IO_EOF_SEEN: i32 = 16i32;
pub const _IO_ERR_SEEN: i32 = 32i32;
#[repr(C, packed(8))]
#[cfg(feature = "posix_types")]
#[derive(Clone, Copy)]
pub struct _IO_FILE {
    pub _flags: i32,
    pub _IO_read_ptr: *mut i8,
    pub _IO_read_end: *mut i8,
    pub _IO_read_base: *mut i8,
    pub _IO_write_base: *mut i8,
    pub _IO_write_ptr: *mut i8,
    pub _IO_write_end: *mut i8,
    pub _IO_buf_base: *mut i8,
    pub _IO_buf_end: *mut i8,
    pub _IO_save_base: *mut i8,
    pub _IO_backup_base: *mut i8,
    pub _IO_save_end: *mut i8,
    pub _markers: *mut core::ffi::c_void,
    pub _chain: *mut _IO_FILE,
    pub _fileno: i32,
    pub _flags2: i32,
    pub _old_offset: super::types::__off_t,
    pub _cur_column: u16,
    pub _vtable_offset: i8,
    pub _shortbuf: [i8; 1],
    pub _lock: *mut _IO_lock_t,
    pub _offset: super::types::__off64_t,
    pub _codecvt: *mut core::ffi::c_void,
    pub _wide_data: *mut core::ffi::c_void,
    pub _freeres_list: *mut _IO_FILE,
    pub _freeres_buf: *mut core::ffi::c_void,
    pub __pad5: u64,
    pub _mode: i32,
    pub _unused2: [i8; 20],
}
#[cfg(feature = "posix_types")]
impl Default for _IO_FILE {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub const _IO_USER_LOCK: i32 = 32768i32;
#[repr(C, packed(8))]
#[cfg(feature = "posix_types")]
#[derive(Clone, Copy)]
pub struct _IO_cookie_io_functions_t {
    pub read: *mut cookie_read_function_t,
    pub write: *mut cookie_write_function_t,
    pub seek: *mut cookie_seek_function_t,
    pub close: *mut cookie_close_function_t,
}
#[cfg(feature = "posix_types")]
impl Default for _IO_cookie_io_functions_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type _IO_lock_t = isize;
pub const _STDIO_H: i32 = 1i32;
pub const _____fpos_t_defined: i32 = 1i32;
pub const ____mbstate_t_defined: i32 = 1i32;
pub const __cookie_io_functions_t_defined: i32 = 1i32;
#[repr(C)]
#[cfg(feature = "posix_types")]
#[derive(Clone, Copy)]
pub struct __fpos_t {
    pub Value: _G_fpos_t,
}
#[cfg(feature = "posix_types")]
impl Default for __fpos_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub struct __mbstate_t {
    pub __count: i32,
    pub __value: __mbstate_t___value,
}
impl Default for __mbstate_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub union __mbstate_t___value {
    pub __wch: u32,
    pub __wchb: [i8; 4],
}
impl Default for __mbstate_t___value {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub const __struct_FILE_defined: i32 = 1i32;
pub type cookie_close_function_t =
    Option<unsafe extern "system" fn(param0: *const core::ffi::c_void) -> i32>;
#[repr(C)]
#[cfg(feature = "posix_types")]
#[derive(Clone, Copy, Default)]
pub struct cookie_io_functions_t {
    pub Value: _IO_cookie_io_functions_t,
}
#[cfg(feature = "posix_types")]
pub type cookie_read_function_t = Option<
    unsafe extern "system" fn(
        param0: *const core::ffi::c_void,
        param1: *const i8,
        param2: u64,
    ) -> super::types::__ssize_t,
>;
#[cfg(feature = "posix_types")]
pub type cookie_seek_function_t = Option<
    unsafe extern "system" fn(
        param0: *const core::ffi::c_void,
        param1: *const super::types::__off64_t,
        param2: i32,
    ) -> i32,
>;
#[cfg(feature = "posix_types")]
pub type cookie_write_function_t = Option<
    unsafe extern "system" fn(
        param0: *const core::ffi::c_void,
        param1: *const i8,
        param2: u64,
    ) -> super::types::__ssize_t,
>;
#[repr(C)]
#[cfg(feature = "posix_types")]
#[derive(Clone, Copy)]
pub struct fpos_t {
    pub Value: __fpos_t,
}
#[cfg(feature = "posix_types")]
impl Default for fpos_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type va_list = *mut core::ffi::c_void;
