// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("c" "C" fn asctime(__tp : *const tm) -> *mut i8);
windows_link::link!("c" "C" fn asctime_r(__tp : *const tm, __buf : *const i8) -> *mut i8);
#[cfg(feature = "types")]
windows_link::link!("c" "C" fn clock() -> clock_t);
#[cfg(feature = "types")]
windows_link::link!("c" "C" fn clock_getcpuclockid(__pid : super::types:: pid_t, __clock_id : *const clockid_t) -> i32);
#[cfg(all(feature = "stat", feature = "types"))]
windows_link::link!("c" "C" fn clock_getres(__clock_id : clockid_t, __res : *const super::stat:: timespec) -> i32);
#[cfg(all(feature = "stat", feature = "types"))]
windows_link::link!("c" "C" fn clock_gettime(__clock_id : clockid_t, __tp : *const super::stat:: timespec) -> i32);
#[cfg(all(feature = "stat", feature = "types"))]
windows_link::link!("c" "C" fn clock_nanosleep(__clock_id : clockid_t, __flags : i32, __req : *const super::stat:: timespec, __rem : *const super::stat:: timespec) -> i32);
#[cfg(all(feature = "stat", feature = "types"))]
windows_link::link!("c" "C" fn clock_settime(__clock_id : clockid_t, __tp : *const super::stat:: timespec) -> i32);
windows_link::link!("c" "C" fn ctime(__timer : *const i64) -> *mut i8);
windows_link::link!("c" "C" fn ctime_r(__timer : *const i64, __buf : *const i8) -> *mut i8);
windows_link::link!("c" "C" fn difftime(__time1 : i64, __time0 : i64) -> f64);
windows_link::link!("c" "C" fn dysize(__year : i32) -> i32);
windows_link::link!("c" "C" fn gmtime(__timer : *const i64) -> *mut tm);
windows_link::link!("c" "C" fn gmtime_r(__timer : *const i64, __tp : *const tm) -> *mut tm);
windows_link::link!("c" "C" fn localtime(__timer : *const i64) -> *mut tm);
windows_link::link!("c" "C" fn localtime_r(__timer : *const i64, __tp : *const tm) -> *mut tm);
windows_link::link!("c" "C" fn mktime(__tp : *const tm) -> i64);
#[cfg(all(feature = "stat", feature = "types"))]
windows_link::link!("c" "C" fn nanosleep(__requested_time : *const super::stat:: timespec, __remaining : *const super::stat:: timespec) -> i32);
windows_link::link!("c" "C" fn strftime(__s : *const i8, __maxsize : u64, __format : *const i8, __tp : *const tm) -> u64);
windows_link::link!("c" "C" fn strftime_l(__s : *const i8, __maxsize : u64, __format : *const i8, __tp : *const tm, __loc : locale_t) -> u64);
windows_link::link!("c" "C" fn time(__timer : *const i64) -> i64);
windows_link::link!("c" "C" fn timegm(__tp : *const tm) -> i64);
windows_link::link!("c" "C" fn timelocal(__tp : *const tm) -> i64);
#[cfg(feature = "types")]
windows_link::link!("c" "C" fn timer_create(__clock_id : clockid_t, __evp : *const core::ffi::c_void, __timerid : *const timer_t) -> i32);
#[cfg(feature = "types")]
windows_link::link!("c" "C" fn timer_delete(__timerid : timer_t) -> i32);
#[cfg(feature = "types")]
windows_link::link!("c" "C" fn timer_getoverrun(__timerid : timer_t) -> i32);
#[cfg(all(feature = "stat", feature = "types"))]
windows_link::link!("c" "C" fn timer_gettime(__timerid : timer_t, __value : *const itimerspec) -> i32);
#[cfg(all(feature = "stat", feature = "types"))]
windows_link::link!("c" "C" fn timer_settime(__timerid : timer_t, __flags : i32, __value : *const itimerspec, __ovalue : *const itimerspec) -> i32);
#[cfg(all(feature = "stat", feature = "types"))]
windows_link::link!("c" "C" fn timespec_get(__ts : *const super::stat:: timespec, __base : i32) -> i32);
windows_link::link!("c" "C" fn tzset());
pub const CLOCK_BOOTTIME: i32 = 7i32;
pub const CLOCK_BOOTTIME_ALARM: i32 = 9i32;
pub const CLOCK_MONOTONIC: i32 = 1i32;
pub const CLOCK_MONOTONIC_COARSE: i32 = 6i32;
pub const CLOCK_MONOTONIC_RAW: i32 = 4i32;
pub const CLOCK_PROCESS_CPUTIME_ID: i32 = 2i32;
pub const CLOCK_REALTIME: i32 = 0i32;
pub const CLOCK_REALTIME_ALARM: i32 = 8i32;
pub const CLOCK_REALTIME_COARSE: i32 = 5i32;
pub const CLOCK_TAI: i32 = 11i32;
pub const CLOCK_THREAD_CPUTIME_ID: i32 = 3i32;
pub const TIMER_ABSTIME: i32 = 1i32;
pub const TIME_UTC: i32 = 1i32;
pub const _BITS_TIME_H: i32 = 1i32;
pub const _BITS_TYPES_LOCALE_T_H: i32 = 1i32;
pub const _BITS_TYPES___LOCALE_T_H: i32 = 1i32;
pub const _TIME_H: i32 = 1i32;
pub const __clock_t_defined: i32 = 1i32;
pub const __clockid_t_defined: i32 = 1i32;
pub const __itimerspec_defined: i32 = 1i32;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct __locale_struct {
    pub __locales: [*mut core::ffi::c_void; 13],
    pub __ctype_b: *mut u16,
    pub __ctype_tolower: *mut i32,
    pub __ctype_toupper: *mut i32,
    pub __names: [*mut i8; 13],
}
impl Default for __locale_struct {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type __locale_t = *mut __locale_struct;
pub const __struct_tm_defined: i32 = 1i32;
pub const __timer_t_defined: i32 = 1i32;
pub type clock_t = super::types::__clock_t;
pub type clockid_t = super::types::__clockid_t;
#[repr(C, packed(8))]
#[cfg(all(feature = "stat", feature = "types"))]
#[derive(Clone, Copy, Default)]
pub struct itimerspec {
    pub it_interval: super::stat::timespec,
    pub it_value: super::stat::timespec,
}
pub type locale_t = __locale_t;
pub type timer_t = super::types::__timer_t;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct tm {
    pub tm_sec: i32,
    pub tm_min: i32,
    pub tm_hour: i32,
    pub tm_mday: i32,
    pub tm_mon: i32,
    pub tm_year: i32,
    pub tm_wday: i32,
    pub tm_yday: i32,
    pub tm_isdst: i32,
    pub tm_gmtoff: i64,
    pub tm_zone: *mut i8,
}
impl Default for tm {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
