// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("c" "C" fn __libc_current_sigrtmax() -> i32);
windows_link::link!("c" "C" fn __libc_current_sigrtmin() -> i32);
windows_link::link!("c" "C" fn __sysv_signal(__sig : i32, __handler : __sighandler_t) -> __sighandler_t);
windows_link::link!("c" "C" fn gsignal(__sig : i32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("c" "C" fn kill(__pid : super::types:: __pid_t, __sig : i32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("c" "C" fn killpg(__pgrp : super::types:: __pid_t, __sig : i32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("c" "C" fn psiginfo(__pinfo : *const siginfo_t, __s : *const i8));
windows_link::link!("c" "C" fn psignal(__sig : i32, __s : *const i8));
windows_link::link!("c" "C" fn raise(__sig : i32) -> i32);
#[cfg(feature = "pthread")]
windows_link::link!("c" "C" fn sigaction(__sig : i32, __act : *const sigaction, __oact : *const sigaction) -> i32);
#[cfg(feature = "pthread")]
windows_link::link!("c" "C" fn sigaddset(__set : *const super::pthread:: __sigset_t, __signo : i32) -> i32);
windows_link::link!("c" "C" fn sigaltstack(__ss : *const stack_t, __oss : *const stack_t) -> i32);
windows_link::link!("c" "C" fn sigblock(__mask : i32) -> i32);
#[cfg(feature = "pthread")]
windows_link::link!("c" "C" fn sigdelset(__set : *const super::pthread:: __sigset_t, __signo : i32) -> i32);
#[cfg(feature = "pthread")]
windows_link::link!("c" "C" fn sigemptyset(__set : *const super::pthread:: __sigset_t) -> i32);
#[cfg(feature = "pthread")]
windows_link::link!("c" "C" fn sigfillset(__set : *const super::pthread:: __sigset_t) -> i32);
windows_link::link!("c" "C" fn siggetmask() -> i32);
windows_link::link!("c" "C" fn siginterrupt(__sig : i32, __interrupt : i32) -> i32);
#[cfg(feature = "pthread")]
windows_link::link!("c" "C" fn sigismember(__set : *const super::pthread:: __sigset_t, __signo : i32) -> i32);
windows_link::link!("c" "C" fn signal(__sig : i32, __handler : __sighandler_t) -> __sighandler_t);
#[cfg(feature = "pthread")]
windows_link::link!("c" "C" fn sigpending(__set : *const super::pthread:: __sigset_t) -> i32);
#[cfg(feature = "pthread")]
windows_link::link!("c" "C" fn sigprocmask(__how : i32, __set : *const super::pthread:: __sigset_t, __oset : *const super::pthread:: __sigset_t) -> i32);
#[cfg(feature = "types")]
windows_link::link!("c" "C" fn sigqueue(__pid : super::types:: __pid_t, __sig : i32, __val : sigval) -> i32);
#[cfg(feature = "types")]
windows_link::link!("c" "C" fn sigreturn(__scp : *const sigcontext) -> i32);
windows_link::link!("c" "C" fn sigsetmask(__mask : i32) -> i32);
windows_link::link!("c" "C" fn sigstack(__ss : *const sigstack, __oss : *const sigstack) -> i32);
#[cfg(feature = "pthread")]
windows_link::link!("c" "C" fn sigsuspend(__set : *const super::pthread:: __sigset_t) -> i32);
#[cfg(all(feature = "pthread", feature = "stat", feature = "types"))]
windows_link::link!("c" "C" fn sigtimedwait(__set : *const super::pthread:: __sigset_t, __info : *const siginfo_t, __timeout : *const super::stat:: timespec) -> i32);
#[cfg(feature = "pthread")]
windows_link::link!("c" "C" fn sigwait(__set : *const super::pthread:: __sigset_t, __sig : *const i32) -> i32);
#[cfg(all(feature = "pthread", feature = "types"))]
windows_link::link!("c" "C" fn sigwaitinfo(__set : *const super::pthread:: __sigset_t, __info : *const siginfo_t) -> i32);
windows_link::link!("c" "C" fn ssignal(__sig : i32, __handler : __sighandler_t) -> __sighandler_t);
pub const FP_XSTATE_MAGIC1: i32 = 1179670611i32;
pub const FP_XSTATE_MAGIC2: i32 = 1179670597i32;
pub const SA_INTERRUPT: i32 = 536870912i32;
pub const SA_NOCLDSTOP: i32 = 1i32;
pub const SA_NOCLDWAIT: i32 = 2i32;
pub const SA_NODEFER: i32 = 1073741824i32;
pub const SA_ONSTACK: i32 = 134217728i32;
pub const SA_RESETHAND: i32 = -2147483648i32;
pub const SA_RESTART: i32 = 268435456i32;
pub const SA_SIGINFO: i32 = 4i32;
pub const SIGABRT: i32 = 6i32;
pub const SIGALRM: i32 = 14i32;
pub const SIGBUS: i32 = 7i32;
pub const SIGCHLD: i32 = 17i32;
pub const SIGCONT: i32 = 18i32;
pub const SIGFPE: i32 = 8i32;
pub const SIGHUP: i32 = 1i32;
pub const SIGILL: i32 = 4i32;
pub const SIGINT: i32 = 2i32;
pub const SIGKILL: i32 = 9i32;
pub const SIGPIPE: i32 = 13i32;
pub const SIGPOLL: i32 = 29i32;
pub const SIGPROF: i32 = 27i32;
pub const SIGPWR: i32 = 30i32;
pub const SIGQUIT: i32 = 3i32;
pub const SIGSEGV: i32 = 11i32;
pub const SIGSTKFLT: i32 = 16i32;
pub const SIGSTOP: i32 = 19i32;
pub const SIGSYS: i32 = 31i32;
pub const SIGTERM: i32 = 15i32;
pub const SIGTRAP: i32 = 5i32;
pub const SIGTSTP: i32 = 20i32;
pub const SIGTTIN: i32 = 21i32;
pub const SIGTTOU: i32 = 22i32;
pub const SIGURG: i32 = 23i32;
pub const SIGUSR1: i32 = 10i32;
pub const SIGUSR2: i32 = 12i32;
pub const SIGVTALRM: i32 = 26i32;
pub const SIGWINCH: i32 = 28i32;
pub const SIGXCPU: i32 = 24i32;
pub const SIGXFSZ: i32 = 25i32;
pub const SIG_BLOCK: i32 = 0i32;
pub const SIG_SETMASK: i32 = 2i32;
pub const SIG_UNBLOCK: i32 = 1i32;
pub const _BITS_SIGACTION_H: i32 = 1i32;
pub const _BITS_SIGCONTEXT_H: i32 = 1i32;
pub const _BITS_SIGNUM_ARCH_H: i32 = 1i32;
pub const _BITS_SIGNUM_GENERIC_H: i32 = 1i32;
pub const __SIGRTMAX: i32 = 64i32;
pub const __SIGRTMIN: i32 = 32i32;
pub const __SI_ERRNO_THEN_CODE: i32 = 1i32;
pub const __SI_HAVE_SIGSYS: i32 = 1i32;
pub const __SI_MAX_SIZE: i32 = 128i32;
pub type __sighandler_t = Option<unsafe extern "system" fn(param0: i32)>;
pub const __siginfo_t_defined: i32 = 1i32;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct __sigset_t {
    pub __val: [u64; 16],
}
impl Default for __sigset_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub const __sigstack_defined: i32 = 1i32;
#[repr(C)]
#[derive(Clone, Copy)]
pub struct __sigval_t {
    pub Value: sigval,
}
impl Default for __sigval_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub const __stack_t_defined: i32 = 1i32;
#[repr(C, packed(2))]
#[derive(Clone, Copy)]
pub struct _fpreg {
    pub significand: [u16; 4],
    pub exponent: u16,
}
impl Default for _fpreg {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct _fpstate {
    pub cwd: super::types::__uint16_t,
    pub swd: super::types::__uint16_t,
    pub ftw: super::types::__uint16_t,
    pub fop: super::types::__uint16_t,
    pub rip: super::types::__uint64_t,
    pub rdp: super::types::__uint64_t,
    pub mxcsr: super::types::__uint32_t,
    pub mxcr_mask: super::types::__uint32_t,
    pub _st: [_fpxreg; 8],
    pub _xmm: [_xmmreg; 16],
    pub __glibc_reserved1: [super::types::__uint32_t; 24],
}
#[cfg(feature = "types")]
impl Default for _fpstate {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct _fpx_sw_bytes {
    pub magic1: super::types::__uint32_t,
    pub extended_size: super::types::__uint32_t,
    pub xstate_bv: super::types::__uint64_t,
    pub xstate_size: super::types::__uint32_t,
    pub __glibc_reserved1: [super::types::__uint32_t; 7],
}
#[cfg(feature = "types")]
impl Default for _fpx_sw_bytes {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(2))]
#[derive(Clone, Copy)]
pub struct _fpxreg {
    pub significand: [u16; 4],
    pub exponent: u16,
    pub __glibc_reserved1: [u16; 3],
}
impl Default for _fpxreg {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct _xmmreg {
    pub element: [super::types::__uint32_t; 4],
}
#[cfg(feature = "types")]
impl Default for _xmmreg {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct _xsave_hdr {
    pub xstate_bv: super::types::__uint64_t,
    pub __glibc_reserved1: [super::types::__uint64_t; 2],
    pub __glibc_reserved2: [super::types::__uint64_t; 5],
}
#[cfg(feature = "types")]
impl Default for _xsave_hdr {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct _xstate {
    pub fpstate: _fpstate,
    pub xstate_hdr: _xsave_hdr,
    pub ymmh: _ymmh_state,
}
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct _ymmh_state {
    pub ymmh_space: [super::types::__uint32_t; 64],
}
#[cfg(feature = "types")]
impl Default for _ymmh_state {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type sig_t = __sighandler_t;
#[repr(C, packed(8))]
#[cfg(feature = "pthread")]
#[derive(Clone, Copy)]
pub struct sigaction {
    pub __sigaction_handler: sigaction___sigaction_handler,
    pub sa_mask: super::pthread::__sigset_t,
    pub sa_flags: i32,
    pub sa_restorer: *mut isize,
}
#[cfg(feature = "pthread")]
impl Default for sigaction {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub union sigaction___sigaction_handler {
    pub sa_handler: __sighandler_t,
    pub sa_sigaction: *mut isize,
}
impl Default for sigaction___sigaction_handler {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct sigcontext {
    pub r8: super::types::__uint64_t,
    pub r9: super::types::__uint64_t,
    pub r10: super::types::__uint64_t,
    pub r11: super::types::__uint64_t,
    pub r12: super::types::__uint64_t,
    pub r13: super::types::__uint64_t,
    pub r14: super::types::__uint64_t,
    pub r15: super::types::__uint64_t,
    pub rdi: super::types::__uint64_t,
    pub rsi: super::types::__uint64_t,
    pub rbp: super::types::__uint64_t,
    pub rbx: super::types::__uint64_t,
    pub rdx: super::types::__uint64_t,
    pub rax: super::types::__uint64_t,
    pub rcx: super::types::__uint64_t,
    pub rsp: super::types::__uint64_t,
    pub rip: super::types::__uint64_t,
    pub eflags: super::types::__uint64_t,
    pub cs: u16,
    pub gs: u16,
    pub fs: u16,
    pub __pad0: u16,
    pub err: super::types::__uint64_t,
    pub trapno: super::types::__uint64_t,
    pub oldmask: super::types::__uint64_t,
    pub cr2: super::types::__uint64_t,
    pub __reserved1: [super::types::__uint64_t; 8],
}
#[cfg(feature = "types")]
impl Default for sigcontext {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct siginfo_t {
    pub si_signo: i32,
    pub si_errno: i32,
    pub si_code: i32,
    pub __pad0: i32,
    pub _sifields: siginfo_t__sifields,
}
#[cfg(feature = "types")]
impl Default for siginfo_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub union siginfo_t__sifields {
    pub _pad: [i32; 28],
    pub _kill: siginfo_t__sifields__kill,
    pub _timer: siginfo_t__sifields__timer,
    pub _rt: siginfo_t__sifields__rt,
    pub _sigchld: siginfo_t__sifields__sigchld,
    pub _sigfault: siginfo_t__sifields__sigfault,
    pub _sigpoll: siginfo_t__sifields__sigpoll,
    pub _sigsys: siginfo_t__sifields__sigsys,
}
#[cfg(feature = "types")]
impl Default for siginfo_t__sifields {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct siginfo_t__sifields__kill {
    pub si_pid: super::types::__pid_t,
    pub si_uid: super::types::__uid_t,
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct siginfo_t__sifields__rt {
    pub si_pid: super::types::__pid_t,
    pub si_uid: super::types::__uid_t,
    pub si_sigval: __sigval_t,
}
#[cfg(feature = "types")]
impl Default for siginfo_t__sifields__rt {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct siginfo_t__sifields__sigchld {
    pub si_pid: super::types::__pid_t,
    pub si_uid: super::types::__uid_t,
    pub si_status: i32,
    pub si_utime: super::types::__clock_t,
    pub si_stime: super::types::__clock_t,
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct siginfo_t__sifields__sigfault {
    pub si_addr: *mut core::ffi::c_void,
    pub si_addr_lsb: i16,
    pub _bounds: siginfo_t__sifields__sigfault__bounds,
}
#[cfg(feature = "types")]
impl Default for siginfo_t__sifields__sigfault {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub union siginfo_t__sifields__sigfault__bounds {
    pub _addr_bnd: siginfo_t__sifields__sigfault__bounds__addr_bnd,
    pub _pkey: super::types::__uint32_t,
}
#[cfg(feature = "types")]
impl Default for siginfo_t__sifields__sigfault__bounds {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct siginfo_t__sifields__sigfault__bounds__addr_bnd {
    pub _lower: *mut core::ffi::c_void,
    pub _upper: *mut core::ffi::c_void,
}
impl Default for siginfo_t__sifields__sigfault__bounds__addr_bnd {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy, Default)]
pub struct siginfo_t__sifields__sigpoll {
    pub si_band: i64,
    pub si_fd: i32,
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct siginfo_t__sifields__sigsys {
    pub _call_addr: *mut core::ffi::c_void,
    pub _syscall: i32,
    pub _arch: u32,
}
impl Default for siginfo_t__sifields__sigsys {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct siginfo_t__sifields__timer {
    pub si_tid: i32,
    pub si_overrun: i32,
    pub si_sigval: __sigval_t,
}
impl Default for siginfo_t__sifields__timer {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct sigstack {
    pub ss_sp: *mut core::ffi::c_void,
    pub ss_onstack: i32,
}
impl Default for sigstack {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub union sigval {
    pub sival_int: i32,
    pub sival_ptr: *mut core::ffi::c_void,
}
impl Default for sigval {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct stack_t {
    pub ss_sp: *mut core::ffi::c_void,
    pub ss_flags: i32,
    pub ss_size: u64,
}
impl Default for stack_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
