//! Rust FFI bindings for POSIX and Linux system APIs.
//!
//! Generated by `bnd-linux-gen` through the direct-Clang pipeline. Do not
//! edit `src/libc/` manually.

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(not(all(target_os = "linux", target_arch = "x86_64", target_env = "gnu")))]
compile_error!("bnd-linux supports only x86_64-unknown-linux-gnu");

pub mod libc;

extern crate bnd_macros as windows_link;
