//! Rust FFI bindings for POSIX and Linux system APIs.
//!
//! Generated by `bnd-linux-gen` through the direct-Clang pipeline. Do not
//! edit `src/libc/` manually.

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

pub mod libc;

extern crate bnd_macros as windows_link;
