// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("c" "C" fn __pthread_register_cancel(__buf : *const __pthread_unwind_buf_t));
windows_link::link!("c" "C" fn __pthread_unregister_cancel(__buf : *const __pthread_unwind_buf_t));
windows_link::link!("c" "C" fn __pthread_unwind_next(__buf : *const __pthread_unwind_buf_t));
windows_link::link!("c" "C" fn __sigsetjmp(__env : *const __jmp_buf_tag, __savemask : i32) -> i32);
windows_link::link!("c" "C" fn pthread_atfork(__prepare : *const isize, __parent : *const isize, __child : *const isize) -> i32);
windows_link::link!("c" "C" fn pthread_attr_destroy(__attr : *const pthread_attr_t) -> i32);
windows_link::link!("c" "C" fn pthread_attr_getdetachstate(__attr : *const pthread_attr_t, __detachstate : *const i32) -> i32);
windows_link::link!("c" "C" fn pthread_attr_getguardsize(__attr : *const pthread_attr_t, __guardsize : *const u64) -> i32);
windows_link::link!("c" "C" fn pthread_attr_getinheritsched(__attr : *const pthread_attr_t, __inherit : *const i32) -> i32);
#[cfg(feature = "sched")]
windows_link::link!("c" "C" fn pthread_attr_getschedparam(__attr : *const pthread_attr_t, __param : *const super::sched:: sched_param) -> i32);
windows_link::link!("c" "C" fn pthread_attr_getschedpolicy(__attr : *const pthread_attr_t, __policy : *const i32) -> i32);
windows_link::link!("c" "C" fn pthread_attr_getscope(__attr : *const pthread_attr_t, __scope : *const i32) -> i32);
windows_link::link!("c" "C" fn pthread_attr_getstack(__attr : *const pthread_attr_t, __stackaddr : *const *const core::ffi::c_void, __stacksize : *const u64) -> i32);
windows_link::link!("c" "C" fn pthread_attr_getstackaddr(__attr : *const pthread_attr_t, __stackaddr : *const *const core::ffi::c_void) -> i32);
windows_link::link!("c" "C" fn pthread_attr_getstacksize(__attr : *const pthread_attr_t, __stacksize : *const u64) -> i32);
windows_link::link!("c" "C" fn pthread_attr_init(__attr : *const pthread_attr_t) -> i32);
windows_link::link!("c" "C" fn pthread_attr_setdetachstate(__attr : *const pthread_attr_t, __detachstate : i32) -> i32);
windows_link::link!("c" "C" fn pthread_attr_setguardsize(__attr : *const pthread_attr_t, __guardsize : u64) -> i32);
windows_link::link!("c" "C" fn pthread_attr_setinheritsched(__attr : *const pthread_attr_t, __inherit : i32) -> i32);
#[cfg(feature = "sched")]
windows_link::link!("c" "C" fn pthread_attr_setschedparam(__attr : *const pthread_attr_t, __param : *const super::sched:: sched_param) -> i32);
windows_link::link!("c" "C" fn pthread_attr_setschedpolicy(__attr : *const pthread_attr_t, __policy : i32) -> i32);
windows_link::link!("c" "C" fn pthread_attr_setscope(__attr : *const pthread_attr_t, __scope : i32) -> i32);
windows_link::link!("c" "C" fn pthread_attr_setstack(__attr : *const pthread_attr_t, __stackaddr : *const core::ffi::c_void, __stacksize : u64) -> i32);
windows_link::link!("c" "C" fn pthread_attr_setstackaddr(__attr : *const pthread_attr_t, __stackaddr : *const core::ffi::c_void) -> i32);
windows_link::link!("c" "C" fn pthread_attr_setstacksize(__attr : *const pthread_attr_t, __stacksize : u64) -> i32);
windows_link::link!("c" "C" fn pthread_barrier_destroy(__barrier : *const pthread_barrier_t) -> i32);
windows_link::link!("c" "C" fn pthread_barrier_init(__barrier : *const pthread_barrier_t, __attr : *const pthread_barrierattr_t, __count : u32) -> i32);
windows_link::link!("c" "C" fn pthread_barrier_wait(__barrier : *const pthread_barrier_t) -> i32);
windows_link::link!("c" "C" fn pthread_barrierattr_destroy(__attr : *const pthread_barrierattr_t) -> i32);
windows_link::link!("c" "C" fn pthread_barrierattr_getpshared(__attr : *const pthread_barrierattr_t, __pshared : *const i32) -> i32);
windows_link::link!("c" "C" fn pthread_barrierattr_init(__attr : *const pthread_barrierattr_t) -> i32);
windows_link::link!("c" "C" fn pthread_barrierattr_setpshared(__attr : *const pthread_barrierattr_t, __pshared : i32) -> i32);
windows_link::link!("c" "C" fn pthread_cancel(__th : pthread_t) -> i32);
windows_link::link!("c" "C" fn pthread_cond_broadcast(__cond : *const pthread_cond_t) -> i32);
windows_link::link!("c" "C" fn pthread_cond_destroy(__cond : *const pthread_cond_t) -> i32);
windows_link::link!("c" "C" fn pthread_cond_init(__cond : *const pthread_cond_t, __cond_attr : *const pthread_condattr_t) -> i32);
windows_link::link!("c" "C" fn pthread_cond_signal(__cond : *const pthread_cond_t) -> i32);
#[cfg(all(feature = "stat", feature = "types"))]
windows_link::link!("c" "C" fn pthread_cond_timedwait(__cond : *const pthread_cond_t, __mutex : *const pthread_mutex_t, __abstime : *const super::stat:: timespec) -> i32);
windows_link::link!("c" "C" fn pthread_cond_wait(__cond : *const pthread_cond_t, __mutex : *const pthread_mutex_t) -> i32);
windows_link::link!("c" "C" fn pthread_condattr_destroy(__attr : *const pthread_condattr_t) -> i32);
#[cfg(feature = "types")]
windows_link::link!("c" "C" fn pthread_condattr_getclock(__attr : *const pthread_condattr_t, __clock_id : *const super::types:: __clockid_t) -> i32);
windows_link::link!("c" "C" fn pthread_condattr_getpshared(__attr : *const pthread_condattr_t, __pshared : *const i32) -> i32);
windows_link::link!("c" "C" fn pthread_condattr_init(__attr : *const pthread_condattr_t) -> i32);
#[cfg(feature = "types")]
windows_link::link!("c" "C" fn pthread_condattr_setclock(__attr : *const pthread_condattr_t, __clock_id : super::types:: __clockid_t) -> i32);
windows_link::link!("c" "C" fn pthread_condattr_setpshared(__attr : *const pthread_condattr_t, __pshared : i32) -> i32);
windows_link::link!("c" "C" fn pthread_create(__newthread : *const pthread_t, __attr : *const pthread_attr_t, __start_routine : *const isize, __arg : *const core::ffi::c_void) -> i32);
windows_link::link!("c" "C" fn pthread_detach(__th : pthread_t) -> i32);
windows_link::link!("c" "C" fn pthread_equal(__thread1 : pthread_t, __thread2 : pthread_t) -> i32);
windows_link::link!("c" "C" fn pthread_exit(__retval : *const core::ffi::c_void));
#[cfg(feature = "types")]
windows_link::link!("c" "C" fn pthread_getcpuclockid(__thread_id : pthread_t, __clock_id : *const super::types:: __clockid_t) -> i32);
#[cfg(feature = "sched")]
windows_link::link!("c" "C" fn pthread_getschedparam(__target_thread : pthread_t, __policy : *const i32, __param : *const super::sched:: sched_param) -> i32);
windows_link::link!("c" "C" fn pthread_getspecific(__key : pthread_key_t) -> *mut core::ffi::c_void);
windows_link::link!("c" "C" fn pthread_join(__th : pthread_t, __thread_return : *const *const core::ffi::c_void) -> i32);
windows_link::link!("c" "C" fn pthread_key_create(__key : *const pthread_key_t, __destr_function : *const isize) -> i32);
windows_link::link!("c" "C" fn pthread_key_delete(__key : pthread_key_t) -> i32);
windows_link::link!("c" "C" fn pthread_mutex_consistent(__mutex : *const pthread_mutex_t) -> i32);
windows_link::link!("c" "C" fn pthread_mutex_destroy(__mutex : *const pthread_mutex_t) -> i32);
windows_link::link!("c" "C" fn pthread_mutex_getprioceiling(__mutex : *const pthread_mutex_t, __prioceiling : *const i32) -> i32);
windows_link::link!("c" "C" fn pthread_mutex_init(__mutex : *const pthread_mutex_t, __mutexattr : *const pthread_mutexattr_t) -> i32);
windows_link::link!("c" "C" fn pthread_mutex_lock(__mutex : *const pthread_mutex_t) -> i32);
windows_link::link!("c" "C" fn pthread_mutex_setprioceiling(__mutex : *const pthread_mutex_t, __prioceiling : i32, __old_ceiling : *const i32) -> i32);
#[cfg(all(feature = "stat", feature = "types"))]
windows_link::link!("c" "C" fn pthread_mutex_timedlock(__mutex : *const pthread_mutex_t, __abstime : *const super::stat:: timespec) -> i32);
windows_link::link!("c" "C" fn pthread_mutex_trylock(__mutex : *const pthread_mutex_t) -> i32);
windows_link::link!("c" "C" fn pthread_mutex_unlock(__mutex : *const pthread_mutex_t) -> i32);
windows_link::link!("c" "C" fn pthread_mutexattr_destroy(__attr : *const pthread_mutexattr_t) -> i32);
windows_link::link!("c" "C" fn pthread_mutexattr_getprioceiling(__attr : *const pthread_mutexattr_t, __prioceiling : *const i32) -> i32);
windows_link::link!("c" "C" fn pthread_mutexattr_getprotocol(__attr : *const pthread_mutexattr_t, __protocol : *const i32) -> i32);
windows_link::link!("c" "C" fn pthread_mutexattr_getpshared(__attr : *const pthread_mutexattr_t, __pshared : *const i32) -> i32);
windows_link::link!("c" "C" fn pthread_mutexattr_getrobust(__attr : *const pthread_mutexattr_t, __robustness : *const i32) -> i32);
windows_link::link!("c" "C" fn pthread_mutexattr_gettype(__attr : *const pthread_mutexattr_t, __kind : *const i32) -> i32);
windows_link::link!("c" "C" fn pthread_mutexattr_init(__attr : *const pthread_mutexattr_t) -> i32);
windows_link::link!("c" "C" fn pthread_mutexattr_setprioceiling(__attr : *const pthread_mutexattr_t, __prioceiling : i32) -> i32);
windows_link::link!("c" "C" fn pthread_mutexattr_setprotocol(__attr : *const pthread_mutexattr_t, __protocol : i32) -> i32);
windows_link::link!("c" "C" fn pthread_mutexattr_setpshared(__attr : *const pthread_mutexattr_t, __pshared : i32) -> i32);
windows_link::link!("c" "C" fn pthread_mutexattr_setrobust(__attr : *const pthread_mutexattr_t, __robustness : i32) -> i32);
windows_link::link!("c" "C" fn pthread_mutexattr_settype(__attr : *const pthread_mutexattr_t, __kind : i32) -> i32);
windows_link::link!("c" "C" fn pthread_once(__once_control : *const pthread_once_t, __init_routine : *const isize) -> i32);
windows_link::link!("c" "C" fn pthread_rwlock_destroy(__rwlock : *const pthread_rwlock_t) -> i32);
windows_link::link!("c" "C" fn pthread_rwlock_init(__rwlock : *const pthread_rwlock_t, __attr : *const pthread_rwlockattr_t) -> i32);
windows_link::link!("c" "C" fn pthread_rwlock_rdlock(__rwlock : *const pthread_rwlock_t) -> i32);
#[cfg(all(feature = "stat", feature = "types"))]
windows_link::link!("c" "C" fn pthread_rwlock_timedrdlock(__rwlock : *const pthread_rwlock_t, __abstime : *const super::stat:: timespec) -> i32);
#[cfg(all(feature = "stat", feature = "types"))]
windows_link::link!("c" "C" fn pthread_rwlock_timedwrlock(__rwlock : *const pthread_rwlock_t, __abstime : *const super::stat:: timespec) -> i32);
windows_link::link!("c" "C" fn pthread_rwlock_tryrdlock(__rwlock : *const pthread_rwlock_t) -> i32);
windows_link::link!("c" "C" fn pthread_rwlock_trywrlock(__rwlock : *const pthread_rwlock_t) -> i32);
windows_link::link!("c" "C" fn pthread_rwlock_unlock(__rwlock : *const pthread_rwlock_t) -> i32);
windows_link::link!("c" "C" fn pthread_rwlock_wrlock(__rwlock : *const pthread_rwlock_t) -> i32);
windows_link::link!("c" "C" fn pthread_rwlockattr_destroy(__attr : *const pthread_rwlockattr_t) -> i32);
windows_link::link!("c" "C" fn pthread_rwlockattr_getkind_np(__attr : *const pthread_rwlockattr_t, __pref : *const i32) -> i32);
windows_link::link!("c" "C" fn pthread_rwlockattr_getpshared(__attr : *const pthread_rwlockattr_t, __pshared : *const i32) -> i32);
windows_link::link!("c" "C" fn pthread_rwlockattr_init(__attr : *const pthread_rwlockattr_t) -> i32);
windows_link::link!("c" "C" fn pthread_rwlockattr_setkind_np(__attr : *const pthread_rwlockattr_t, __pref : i32) -> i32);
windows_link::link!("c" "C" fn pthread_rwlockattr_setpshared(__attr : *const pthread_rwlockattr_t, __pshared : i32) -> i32);
windows_link::link!("c" "C" fn pthread_self() -> pthread_t);
windows_link::link!("c" "C" fn pthread_setcancelstate(__state : i32, __oldstate : *const i32) -> i32);
windows_link::link!("c" "C" fn pthread_setcanceltype(__type : i32, __oldtype : *const i32) -> i32);
#[cfg(feature = "sched")]
windows_link::link!("c" "C" fn pthread_setschedparam(__target_thread : pthread_t, __policy : i32, __param : *const super::sched:: sched_param) -> i32);
windows_link::link!("c" "C" fn pthread_setschedprio(__target_thread : pthread_t, __prio : i32) -> i32);
windows_link::link!("c" "C" fn pthread_setspecific(__key : pthread_key_t, __pointer : *const core::ffi::c_void) -> i32);
windows_link::link!("c" "C" fn pthread_spin_destroy(__lock : *const pthread_spinlock_t) -> i32);
windows_link::link!("c" "C" fn pthread_spin_init(__lock : *const pthread_spinlock_t, __pshared : i32) -> i32);
windows_link::link!("c" "C" fn pthread_spin_lock(__lock : *const pthread_spinlock_t) -> i32);
windows_link::link!("c" "C" fn pthread_spin_trylock(__lock : *const pthread_spinlock_t) -> i32);
windows_link::link!("c" "C" fn pthread_spin_unlock(__lock : *const pthread_spinlock_t) -> i32);
windows_link::link!("c" "C" fn pthread_testcancel());
pub const PTHREAD_BARRIER_SERIAL_THREAD: i32 = -1i32;
pub const PTHREAD_CANCEL_ASYNCHRONOUS: u32 = 1u32;
pub const PTHREAD_CANCEL_DEFERRED: u32 = 0u32;
pub const PTHREAD_CANCEL_DISABLE: u32 = 1u32;
pub const PTHREAD_CANCEL_ENABLE: u32 = 0u32;
pub const PTHREAD_CREATE_DETACHED: u32 = 1u32;
pub const PTHREAD_CREATE_JOINABLE: u32 = 0u32;
pub const PTHREAD_EXPLICIT_SCHED: u32 = 1u32;
pub const PTHREAD_INHERIT_SCHED: u32 = 0u32;
pub const PTHREAD_MUTEX_ADAPTIVE_NP: u32 = 3u32;
pub const PTHREAD_MUTEX_DEFAULT: u32 = 0u32;
pub const PTHREAD_MUTEX_ERRORCHECK: u32 = 2u32;
pub const PTHREAD_MUTEX_ERRORCHECK_NP: u32 = 2u32;
pub const PTHREAD_MUTEX_NORMAL: u32 = 0u32;
pub const PTHREAD_MUTEX_RECURSIVE: u32 = 1u32;
pub const PTHREAD_MUTEX_RECURSIVE_NP: u32 = 1u32;
pub const PTHREAD_MUTEX_ROBUST: u32 = 1u32;
pub const PTHREAD_MUTEX_ROBUST_NP: u32 = 1u32;
pub const PTHREAD_MUTEX_STALLED: u32 = 0u32;
pub const PTHREAD_MUTEX_STALLED_NP: u32 = 0u32;
pub const PTHREAD_MUTEX_TIMED_NP: u32 = 0u32;
pub const PTHREAD_ONCE_INIT: i32 = 0i32;
pub const PTHREAD_PRIO_INHERIT: u32 = 1u32;
pub const PTHREAD_PRIO_NONE: u32 = 0u32;
pub const PTHREAD_PRIO_PROTECT: u32 = 2u32;
pub const PTHREAD_PROCESS_PRIVATE: u32 = 0u32;
pub const PTHREAD_PROCESS_SHARED: u32 = 1u32;
pub const PTHREAD_RWLOCK_DEFAULT_NP: u32 = 0u32;
pub const PTHREAD_RWLOCK_PREFER_READER_NP: u32 = 0u32;
pub const PTHREAD_RWLOCK_PREFER_WRITER_NONRECURSIVE_NP: u32 = 2u32;
pub const PTHREAD_RWLOCK_PREFER_WRITER_NP: u32 = 1u32;
pub const PTHREAD_SCOPE_PROCESS: u32 = 1u32;
pub const PTHREAD_SCOPE_SYSTEM: u32 = 0u32;
pub const PTHREAD_STACK_MIN: i32 = 16384i32;
pub const _BITS_PTHREADTYPES_ARCH_H: i32 = 1i32;
pub const _BITS_PTHREADTYPES_COMMON_H: i32 = 1i32;
pub const _PTHREAD_H: i32 = 1i32;
pub const _THREAD_MUTEX_INTERNAL_H: i32 = 1i32;
pub const _THREAD_SHARED_TYPES_H: i32 = 1i32;
pub const __PTHREAD_MUTEX_HAVE_PREV: i32 = 1i32;
pub const __SIZEOF_PTHREAD_ATTR_T: i32 = 56i32;
pub const __SIZEOF_PTHREAD_BARRIERATTR_T: i32 = 4i32;
pub const __SIZEOF_PTHREAD_BARRIER_T: i32 = 32i32;
pub const __SIZEOF_PTHREAD_CONDATTR_T: i32 = 4i32;
pub const __SIZEOF_PTHREAD_COND_T: i32 = 48i32;
pub const __SIZEOF_PTHREAD_MUTEXATTR_T: i32 = 4i32;
pub const __SIZEOF_PTHREAD_MUTEX_T: i32 = 40i32;
pub const __SIZEOF_PTHREAD_RWLOCKATTR_T: i32 = 8i32;
pub const __SIZEOF_PTHREAD_RWLOCK_T: i32 = 56i32;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub union __atomic_wide_counter {
    pub __value64: u64,
    pub __value32: __atomic_wide_counter___value32,
}
impl Default for __atomic_wide_counter {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[derive(Clone, Copy, Default)]
pub struct __atomic_wide_counter___value32 {
    pub __low: u32,
    pub __high: u32,
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct __cancel_jmp_buf_tag {
    pub __cancel_jmp_buf: [i64; 8],
    pub __mask_was_saved: i32,
}
impl Default for __cancel_jmp_buf_tag {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub const __have_pthread_attr_t: i32 = 1i32;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct __jmp_buf_tag {
    pub __jmpbuf: [i64; 8],
    pub __mask_was_saved: i32,
    pub __saved_mask: __sigset_t,
}
impl Default for __jmp_buf_tag {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub const __jmp_buf_tag_defined: i32 = 1i32;
#[repr(C, packed(4))]
#[derive(Clone, Copy, Default)]
pub struct __once_flag {
    pub __data: i32,
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct __pthread_cleanup_frame {
    pub __cancel_routine: *mut isize,
    pub __cancel_arg: *mut core::ffi::c_void,
    pub __do_it: i32,
    pub __cancel_type: i32,
}
impl Default for __pthread_cleanup_frame {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct __pthread_cond_s {
    pub __wseq: __atomic_wide_counter,
    pub __g1_start: __atomic_wide_counter,
    pub __g_refs: [u32; 2],
    pub __g_size: [u32; 2],
    pub __g1_orig_size: u32,
    pub __wrefs: u32,
    pub __g_signals: [u32; 2],
}
impl Default for __pthread_cond_s {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct __pthread_internal_list {
    pub __prev: *mut __pthread_internal_list,
    pub __next: *mut __pthread_internal_list,
}
impl Default for __pthread_internal_list {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct __pthread_internal_slist {
    pub __next: *mut __pthread_internal_slist,
}
impl Default for __pthread_internal_slist {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct __pthread_list_t {
    pub Value: __pthread_internal_list,
}
#[repr(C, packed(8))]
#[derive(Clone, Copy, Default)]
pub struct __pthread_mutex_s {
    pub __lock: i32,
    pub __count: u32,
    pub __owner: i32,
    pub __nusers: u32,
    pub __kind: i32,
    pub __spins: i16,
    pub __elision: i16,
    pub __list: __pthread_list_t,
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct __pthread_rwlock_arch_t {
    pub __readers: u32,
    pub __writers: u32,
    pub __wrphase_futex: u32,
    pub __writers_futex: u32,
    pub __pad3: u32,
    pub __pad4: u32,
    pub __cur_writer: i32,
    pub __shared: i32,
    pub __rwelision: i8,
    pub __pad1: [u8; 7],
    pub __pad2: u64,
    pub __flags: u32,
}
impl Default for __pthread_rwlock_arch_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct __pthread_slist_t {
    pub Value: __pthread_internal_slist,
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct __pthread_unwind_buf_t {
    pub __cancel_jmp_buf: [__cancel_jmp_buf_tag; 1],
    pub __pad: [*mut core::ffi::c_void; 4],
}
impl Default for __pthread_unwind_buf_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct __sigset_t {
    pub __val: [u64; 16],
}
impl Default for __sigset_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type __thrd_t = u64;
pub type __tss_t = u32;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct _pthread_cleanup_buffer {
    pub __routine: *mut isize,
    pub __arg: *mut core::ffi::c_void,
    pub __canceltype: i32,
    pub __prev: *mut _pthread_cleanup_buffer,
}
impl Default for _pthread_cleanup_buffer {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub union pthread_attr_t {
    pub __size: [i8; 56],
    pub __align: i64,
}
impl Default for pthread_attr_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub union pthread_barrier_t {
    pub __size: [i8; 32],
    pub __align: i64,
}
impl Default for pthread_barrier_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub union pthread_barrierattr_t {
    pub __size: [i8; 4],
    pub __align: i32,
}
impl Default for pthread_barrierattr_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub union pthread_cond_t {
    pub __data: __pthread_cond_s,
    pub __size: [i8; 48],
    pub __align: i64,
}
impl Default for pthread_cond_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub union pthread_condattr_t {
    pub __size: [i8; 4],
    pub __align: i32,
}
impl Default for pthread_condattr_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type pthread_key_t = u32;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub union pthread_mutex_t {
    pub __data: __pthread_mutex_s,
    pub __size: [i8; 40],
    pub __align: i64,
}
impl Default for pthread_mutex_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub union pthread_mutexattr_t {
    pub __size: [i8; 4],
    pub __align: i32,
}
impl Default for pthread_mutexattr_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type pthread_once_t = i32;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub union pthread_rwlock_t {
    pub __data: __pthread_rwlock_arch_t,
    pub __size: [i8; 56],
    pub __align: i64,
}
impl Default for pthread_rwlock_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub union pthread_rwlockattr_t {
    pub __size: [i8; 8],
    pub __align: i64,
}
impl Default for pthread_rwlockattr_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type pthread_spinlock_t = i32;
pub type pthread_t = u64;
