// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("c" "C" fn alphasort(__e1 : *const *const dirent, __e2 : *const *const dirent) -> i32);
windows_link::link!("c" "C" fn closedir(__dirp : *const DIR) -> i32);
windows_link::link!("c" "C" fn dirfd(__dirp : *const DIR) -> i32);
windows_link::link!("c" "C" fn fdopendir(__fd : i32) -> *mut DIR);
windows_link::link!("c" "C" fn getdirentries(__fd : i32, __buf : *const i8, __nbytes : u64, __basep : *const i64) -> i64);
windows_link::link!("c" "C" fn opendir(__name : *const i8) -> *mut DIR);
windows_link::link!("c" "C" fn readdir(__dirp : *const DIR) -> *mut dirent);
windows_link::link!("c" "C" fn readdir_r(__dirp : *const DIR, __entry : *const dirent, __result : *const *const dirent) -> i32);
windows_link::link!("c" "C" fn rewinddir(__dirp : *const DIR));
windows_link::link!("c" "C" fn scandir(__dir : *const i8, __namelist : *const *const *const dirent, __selector : *const isize, __cmp : *const isize) -> i32);
windows_link::link!("c" "C" fn seekdir(__dirp : *const DIR, __pos : i64));
windows_link::link!("c" "C" fn telldir(__dirp : *const DIR) -> i64);
pub type DIR = isize;
pub const DT_BLK: u32 = 6u32;
pub const DT_CHR: u32 = 2u32;
pub const DT_DIR: u32 = 4u32;
pub const DT_FIFO: u32 = 1u32;
pub const DT_LNK: u32 = 10u32;
pub const DT_REG: u32 = 8u32;
pub const DT_SOCK: u32 = 12u32;
pub const DT_UNKNOWN: u32 = 0u32;
pub const DT_WHT: u32 = 14u32;
pub const _DIRENT_H: i32 = 1i32;
pub const _DIRENT_MATCHES_DIRENT64: i32 = 1i32;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct dirent {
    pub d_ino: u64,
    pub d_off: i64,
    pub d_reclen: u16,
    pub d_type: u8,
    pub d_name: [i8; 256],
}
impl Default for dirent {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
