// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("c" "C" fn __h_errno_location() -> *mut i32);
windows_link::link!("c" "C" fn endhostent());
windows_link::link!("c" "C" fn endnetent());
windows_link::link!("c" "C" fn endnetgrent());
windows_link::link!("c" "C" fn endprotoent());
windows_link::link!("c" "C" fn endservent());
#[cfg(feature = "Socket")]
windows_link::link!("c" "C" fn freeaddrinfo(__ai : *const addrinfo));
windows_link::link!("c" "C" fn gai_strerror(__ecode : i32) -> *mut i8);
#[cfg(feature = "Socket")]
windows_link::link!("c" "C" fn getaddrinfo(__name : *const i8, __service : *const i8, __req : *const addrinfo, __pai : *const *const addrinfo) -> i32);
windows_link::link!("c" "C" fn gethostbyaddr(__addr : *const core::ffi::c_void, __len : u32, __type : i32) -> *mut hostent);
windows_link::link!("c" "C" fn gethostbyaddr_r(__addr : *const core::ffi::c_void, __len : u32, __type : i32, __result_buf : *const hostent, __buf : *const i8, __buflen : u64, __result : *const *const hostent, __h_errnop : *const i32) -> i32);
windows_link::link!("c" "C" fn gethostbyname(__name : *const i8) -> *mut hostent);
windows_link::link!("c" "C" fn gethostbyname2(__name : *const i8, __af : i32) -> *mut hostent);
windows_link::link!("c" "C" fn gethostbyname2_r(__name : *const i8, __af : i32, __result_buf : *const hostent, __buf : *const i8, __buflen : u64, __result : *const *const hostent, __h_errnop : *const i32) -> i32);
windows_link::link!("c" "C" fn gethostbyname_r(__name : *const i8, __result_buf : *const hostent, __buf : *const i8, __buflen : u64, __result : *const *const hostent, __h_errnop : *const i32) -> i32);
windows_link::link!("c" "C" fn gethostent() -> *mut hostent);
windows_link::link!("c" "C" fn gethostent_r(__result_buf : *const hostent, __buf : *const i8, __buflen : u64, __result : *const *const hostent, __h_errnop : *const i32) -> i32);
#[cfg(feature = "Socket")]
windows_link::link!("c" "C" fn getnameinfo(__sa : *const super::Socket:: sockaddr, __salen : super::Socket:: socklen_t, __host : *const i8, __hostlen : super::Socket:: socklen_t, __serv : *const i8, __servlen : super::Socket:: socklen_t, __flags : i32) -> i32);
windows_link::link!("c" "C" fn getnetbyaddr(__net : u32, __type : i32) -> *mut netent);
windows_link::link!("c" "C" fn getnetbyaddr_r(__net : u32, __type : i32, __result_buf : *const netent, __buf : *const i8, __buflen : u64, __result : *const *const netent, __h_errnop : *const i32) -> i32);
windows_link::link!("c" "C" fn getnetbyname(__name : *const i8) -> *mut netent);
windows_link::link!("c" "C" fn getnetbyname_r(__name : *const i8, __result_buf : *const netent, __buf : *const i8, __buflen : u64, __result : *const *const netent, __h_errnop : *const i32) -> i32);
windows_link::link!("c" "C" fn getnetent() -> *mut netent);
windows_link::link!("c" "C" fn getnetent_r(__result_buf : *const netent, __buf : *const i8, __buflen : u64, __result : *const *const netent, __h_errnop : *const i32) -> i32);
windows_link::link!("c" "C" fn getnetgrent(__hostp : *const *const i8, __userp : *const *const i8, __domainp : *const *const i8) -> i32);
windows_link::link!("c" "C" fn getnetgrent_r(__hostp : *const *const i8, __userp : *const *const i8, __domainp : *const *const i8, __buffer : *const i8, __buflen : u64) -> i32);
windows_link::link!("c" "C" fn getprotobyname(__name : *const i8) -> *mut protoent);
windows_link::link!("c" "C" fn getprotobyname_r(__name : *const i8, __result_buf : *const protoent, __buf : *const i8, __buflen : u64, __result : *const *const protoent) -> i32);
windows_link::link!("c" "C" fn getprotobynumber(__proto : i32) -> *mut protoent);
windows_link::link!("c" "C" fn getprotobynumber_r(__proto : i32, __result_buf : *const protoent, __buf : *const i8, __buflen : u64, __result : *const *const protoent) -> i32);
windows_link::link!("c" "C" fn getprotoent() -> *mut protoent);
windows_link::link!("c" "C" fn getprotoent_r(__result_buf : *const protoent, __buf : *const i8, __buflen : u64, __result : *const *const protoent) -> i32);
windows_link::link!("c" "C" fn getservbyname(__name : *const i8, __proto : *const i8) -> *mut servent);
windows_link::link!("c" "C" fn getservbyname_r(__name : *const i8, __proto : *const i8, __result_buf : *const servent, __buf : *const i8, __buflen : u64, __result : *const *const servent) -> i32);
windows_link::link!("c" "C" fn getservbyport(__port : i32, __proto : *const i8) -> *mut servent);
windows_link::link!("c" "C" fn getservbyport_r(__port : i32, __proto : *const i8, __result_buf : *const servent, __buf : *const i8, __buflen : u64, __result : *const *const servent) -> i32);
windows_link::link!("c" "C" fn getservent() -> *mut servent);
windows_link::link!("c" "C" fn getservent_r(__result_buf : *const servent, __buf : *const i8, __buflen : u64, __result : *const *const servent) -> i32);
windows_link::link!("c" "C" fn herror(__str : *const i8));
windows_link::link!("c" "C" fn hstrerror(__err_num : i32) -> *mut i8);
windows_link::link!("c" "C" fn innetgr(__netgroup : *const i8, __host : *const i8, __user : *const i8, __domain : *const i8) -> i32);
windows_link::link!("c" "C" fn iruserok(__raddr : u32, __suser : i32, __remuser : *const i8, __locuser : *const i8) -> i32);
windows_link::link!("c" "C" fn iruserok_af(__raddr : *const core::ffi::c_void, __suser : i32, __remuser : *const i8, __locuser : *const i8, __af : u16) -> i32);
windows_link::link!("c" "C" fn rcmd(__ahost : *const *const i8, __rport : u16, __locuser : *const i8, __remuser : *const i8, __cmd : *const i8, __fd2p : *const i32) -> i32);
windows_link::link!("c" "C" fn rcmd_af(__ahost : *const *const i8, __rport : u16, __locuser : *const i8, __remuser : *const i8, __cmd : *const i8, __fd2p : *const i32, __af : u16) -> i32);
windows_link::link!("c" "C" fn rexec(__ahost : *const *const i8, __rport : i32, __name : *const i8, __pass : *const i8, __cmd : *const i8, __fd2p : *const i32) -> i32);
windows_link::link!("c" "C" fn rexec_af(__ahost : *const *const i8, __rport : i32, __name : *const i8, __pass : *const i8, __cmd : *const i8, __fd2p : *const i32, __af : u16) -> i32);
windows_link::link!("c" "C" fn rresvport(__alport : *const i32) -> i32);
windows_link::link!("c" "C" fn rresvport_af(__alport : *const i32, __af : u16) -> i32);
windows_link::link!("c" "C" fn ruserok(__rhost : *const i8, __suser : i32, __remuser : *const i8, __locuser : *const i8) -> i32);
windows_link::link!("c" "C" fn ruserok_af(__rhost : *const i8, __suser : i32, __remuser : *const i8, __locuser : *const i8, __af : u16) -> i32);
windows_link::link!("c" "C" fn sethostent(__stay_open : i32));
windows_link::link!("c" "C" fn setnetent(__stay_open : i32));
windows_link::link!("c" "C" fn setnetgrent(__netgroup : *const i8) -> i32);
windows_link::link!("c" "C" fn setprotoent(__stay_open : i32));
windows_link::link!("c" "C" fn setservent(__stay_open : i32));
pub const AI_ADDRCONFIG: i32 = 32i32;
pub const AI_ALL: i32 = 16i32;
pub const AI_CANONNAME: i32 = 2i32;
pub const AI_NUMERICHOST: i32 = 4i32;
pub const AI_NUMERICSERV: i32 = 1024i32;
pub const AI_PASSIVE: i32 = 1i32;
pub const AI_V4MAPPED: i32 = 8i32;
pub const EAI_AGAIN: i32 = -3i32;
pub const EAI_BADFLAGS: i32 = -1i32;
pub const EAI_FAIL: i32 = -4i32;
pub const EAI_FAMILY: i32 = -6i32;
pub const EAI_MEMORY: i32 = -10i32;
pub const EAI_NONAME: i32 = -2i32;
pub const EAI_OVERFLOW: i32 = -12i32;
pub const EAI_SERVICE: i32 = -8i32;
pub const EAI_SOCKTYPE: i32 = -7i32;
pub const EAI_SYSTEM: i32 = -11i32;
pub const HOST_NOT_FOUND: i32 = 1i32;
pub const IPPORT_RESERVED: i32 = 1024i32;
pub const NETDB_INTERNAL: i32 = -1i32;
pub const NETDB_SUCCESS: i32 = 0i32;
pub const NI_DGRAM: i32 = 16i32;
pub const NI_MAXHOST: i32 = 1025i32;
pub const NI_MAXSERV: i32 = 32i32;
pub const NI_NAMEREQD: i32 = 8i32;
pub const NI_NOFQDN: i32 = 4i32;
pub const NI_NUMERICHOST: i32 = 1i32;
pub const NI_NUMERICSERV: i32 = 2i32;
pub const NO_DATA: i32 = 4i32;
pub const NO_RECOVERY: i32 = 3i32;
pub const TRY_AGAIN: i32 = 2i32;
pub const _NETDB_H: i32 = 1i32;
#[repr(C, packed(8))]
#[cfg(feature = "Socket")]
#[derive(Clone, Copy)]
pub struct addrinfo {
    pub ai_flags: i32,
    pub ai_family: i32,
    pub ai_socktype: i32,
    pub ai_protocol: i32,
    pub ai_addrlen: super::Socket::socklen_t,
    pub ai_addr: *mut super::Socket::sockaddr,
    pub ai_canonname: *mut i8,
    pub ai_next: *mut addrinfo,
}
#[cfg(feature = "Socket")]
impl Default for addrinfo {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct hostent {
    pub h_name: *mut i8,
    pub h_aliases: *mut *mut i8,
    pub h_addrtype: i32,
    pub h_length: i32,
    pub h_addr_list: *mut *mut i8,
}
impl Default for hostent {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct netent {
    pub n_name: *mut i8,
    pub n_aliases: *mut *mut i8,
    pub n_addrtype: i32,
    pub n_net: u32,
}
impl Default for netent {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct protoent {
    pub p_name: *mut i8,
    pub p_aliases: *mut *mut i8,
    pub p_proto: i32,
}
impl Default for protoent {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct servent {
    pub s_name: *mut i8,
    pub s_aliases: *mut *mut i8,
    pub s_port: i32,
    pub s_proto: *mut i8,
}
impl Default for servent {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
