// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(feature = "Stat")]
windows_link::link!("c" "C" fn creat(__file : *const i8, __mode : super::Stat:: mode_t) -> i32);
#[cfg(feature = "Stat")]
windows_link::link!("c" "C" fn lockf(__fd : i32, __cmd : i32, __len : super::Stat:: off_t) -> i32);
#[cfg(feature = "Stat")]
windows_link::link!("c" "C" fn posix_fadvise(__fd : i32, __offset : super::Stat:: off_t, __len : super::Stat:: off_t, __advise : i32) -> i32);
#[cfg(feature = "Stat")]
windows_link::link!("c" "C" fn posix_fallocate(__fd : i32, __offset : super::Stat:: off_t, __len : super::Stat:: off_t) -> i32);
pub const AT_FDCWD: i32 = -100i32;
pub const FD_CLOEXEC: i32 = 1i32;
pub const F_DUPFD: i32 = 0i32;
pub const F_DUPFD_CLOEXEC: i32 = 1030i32;
pub const F_EXLCK: i32 = 4i32;
pub const F_GETFD: i32 = 1i32;
pub const F_GETFL: i32 = 3i32;
pub const F_LOCK: i32 = 1i32;
pub const F_OK: i32 = 0i32;
pub const F_RDLCK: i32 = 0i32;
pub const F_SETFD: i32 = 2i32;
pub const F_SETFL: i32 = 4i32;
pub const F_SHLCK: i32 = 8i32;
pub const F_TEST: i32 = 3i32;
pub const F_TLOCK: i32 = 2i32;
pub const F_ULOCK: i32 = 0i32;
pub const F_UNLCK: i32 = 2i32;
pub const F_WRLCK: i32 = 1i32;
pub const LOCK_EX: i32 = 2i32;
pub const LOCK_NB: i32 = 4i32;
pub const LOCK_SH: i32 = 1i32;
pub const LOCK_UN: i32 = 8i32;
pub const O_ACCMODE: i32 = 3i32;
pub const O_APPEND: i32 = 2000i32;
pub const O_ASYNC: i32 = 20000i32;
pub const O_CREAT: i32 = 100i32;
pub const O_EXCL: i32 = 200i32;
pub const O_NOCTTY: i32 = 400i32;
pub const O_NONBLOCK: i32 = 4000i32;
pub const O_RDONLY: i32 = 0i32;
pub const O_RDWR: i32 = 2i32;
pub const O_SYNC: i32 = 4010000i32;
pub const O_TRUNC: i32 = 1000i32;
pub const O_WRONLY: i32 = 1i32;
pub const POSIX_FADV_NORMAL: i32 = 0i32;
pub const POSIX_FADV_RANDOM: i32 = 1i32;
pub const POSIX_FADV_SEQUENTIAL: i32 = 2i32;
pub const POSIX_FADV_WILLNEED: i32 = 3i32;
pub const R_OK: i32 = 4i32;
pub const SEEK_CUR: i32 = 1i32;
pub const SEEK_END: i32 = 2i32;
pub const SEEK_SET: i32 = 0i32;
pub const W_OK: i32 = 2i32;
pub const X_OK: i32 = 1i32;
pub const _FCNTL_H: i32 = 1i32;
pub const __F_GETOWN: i32 = 9i32;
pub const __F_GETOWN_EX: i32 = 16i32;
pub const __F_GETSIG: i32 = 11i32;
pub const __F_SETOWN: i32 = 8i32;
pub const __F_SETOWN_EX: i32 = 15i32;
pub const __F_SETSIG: i32 = 10i32;
pub const __O_CLOEXEC: i32 = 2000000i32;
pub const __O_DIRECT: i32 = 40000i32;
pub const __O_DIRECTORY: i32 = 200000i32;
pub const __O_DSYNC: i32 = 10000i32;
pub const __O_NOATIME: i32 = 1000000i32;
pub const __O_NOFOLLOW: i32 = 400000i32;
pub const __O_PATH: i32 = 10000000i32;
pub const __POSIX_FADV_DONTNEED: i32 = 4i32;
pub const __POSIX_FADV_NOREUSE: i32 = 5i32;
pub type mode_t = u32;
pub type off_t = i64;
pub type pid_t = i32;
