// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("c" "C" fn inotify_add_watch(__fd : i32, __name : *const i8, __mask : u32) -> i32);
windows_link::link!("c" "C" fn inotify_init() -> i32);
windows_link::link!("c" "C" fn inotify_init1(__flags : i32) -> i32);
windows_link::link!("c" "C" fn inotify_rm_watch(__fd : i32, __wd : i32) -> i32);
pub const IN_ACCESS: i32 = 1i32;
pub const IN_ATTRIB: i32 = 4i32;
pub const IN_CLOSE_NOWRITE: i32 = 16i32;
pub const IN_CLOSE_WRITE: i32 = 8i32;
pub const IN_CREATE: i32 = 256i32;
pub const IN_DELETE: i32 = 512i32;
pub const IN_DELETE_SELF: i32 = 1024i32;
pub const IN_DONT_FOLLOW: i32 = 33554432i32;
pub const IN_EXCL_UNLINK: i32 = 67108864i32;
pub const IN_IGNORED: i32 = 32768i32;
pub const IN_ISDIR: i32 = 1073741824i32;
pub const IN_MASK_ADD: i32 = 536870912i32;
pub const IN_MASK_CREATE: i32 = 268435456i32;
pub const IN_MODIFY: i32 = 2i32;
pub const IN_MOVED_FROM: i32 = 64i32;
pub const IN_MOVED_TO: i32 = 128i32;
pub const IN_MOVE_SELF: i32 = 2048i32;
pub const IN_ONESHOT: i32 = -2147483648i32;
pub const IN_ONLYDIR: i32 = 16777216i32;
pub const IN_OPEN: i32 = 32i32;
pub const IN_Q_OVERFLOW: i32 = 16384i32;
pub const IN_UNMOUNT: i32 = 8192i32;
pub const _SYS_INOTIFY_H: i32 = 1i32;
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub struct inotify_event {
    pub wd: i32,
    pub mask: u32,
    pub cookie: u32,
    pub len: u32,
    pub name: *mut i8,
}
impl Default for inotify_event {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
