// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("c" "C" fn madvise(__addr : *const core::ffi::c_void, __len : u64, __advice : i32) -> i32);
windows_link::link!("c" "C" fn mincore(__start : *const core::ffi::c_void, __len : u64, __vec : *const u8) -> i32);
windows_link::link!("c" "C" fn mlock(__addr : *const core::ffi::c_void, __len : u64) -> i32);
windows_link::link!("c" "C" fn mlockall(__flags : i32) -> i32);
windows_link::link!("c" "C" fn mmap(__addr : *const core::ffi::c_void, __len : u64, __prot : i32, __flags : i32, __fd : i32, __offset : i64) -> *mut core::ffi::c_void);
windows_link::link!("c" "C" fn mprotect(__addr : *const core::ffi::c_void, __len : u64, __prot : i32) -> i32);
windows_link::link!("c" "C" fn msync(__addr : *const core::ffi::c_void, __len : u64, __flags : i32) -> i32);
windows_link::link!("c" "C" fn munlock(__addr : *const core::ffi::c_void, __len : u64) -> i32);
windows_link::link!("c" "C" fn munlockall() -> i32);
windows_link::link!("c" "C" fn munmap(__addr : *const core::ffi::c_void, __len : u64) -> i32);
windows_link::link!("c" "C" fn posix_madvise(__addr : *const core::ffi::c_void, __len : u64, __advice : i32) -> i32);
windows_link::link!("c" "C" fn shm_open(__name : *const i8, __oflag : i32, __mode : mode_t) -> i32);
windows_link::link!("c" "C" fn shm_unlink(__name : *const i8) -> i32);
pub const MADV_COLD: i32 = 20i32;
pub const MADV_COLLAPSE: i32 = 25i32;
pub const MADV_DODUMP: i32 = 17i32;
pub const MADV_DOFORK: i32 = 11i32;
pub const MADV_DONTDUMP: i32 = 16i32;
pub const MADV_DONTFORK: i32 = 10i32;
pub const MADV_DONTNEED: i32 = 4i32;
pub const MADV_DONTNEED_LOCKED: i32 = 24i32;
pub const MADV_FREE: i32 = 8i32;
pub const MADV_HUGEPAGE: i32 = 14i32;
pub const MADV_HWPOISON: i32 = 100i32;
pub const MADV_KEEPONFORK: i32 = 19i32;
pub const MADV_MERGEABLE: i32 = 12i32;
pub const MADV_NOHUGEPAGE: i32 = 15i32;
pub const MADV_NORMAL: i32 = 0i32;
pub const MADV_PAGEOUT: i32 = 21i32;
pub const MADV_POPULATE_READ: i32 = 22i32;
pub const MADV_POPULATE_WRITE: i32 = 23i32;
pub const MADV_RANDOM: i32 = 1i32;
pub const MADV_REMOVE: i32 = 9i32;
pub const MADV_SEQUENTIAL: i32 = 2i32;
pub const MADV_UNMERGEABLE: i32 = 13i32;
pub const MADV_WILLNEED: i32 = 3i32;
pub const MADV_WIPEONFORK: i32 = 18i32;
pub const MAP_ANONYMOUS: i32 = 32i32;
pub const MAP_DENYWRITE: i32 = 2048i32;
pub const MAP_EXECUTABLE: i32 = 4096i32;
pub const MAP_FILE: i32 = 0i32;
pub const MAP_FIXED: i32 = 16i32;
pub const MAP_FIXED_NOREPLACE: i32 = 1048576i32;
pub const MAP_GROWSDOWN: i32 = 256i32;
pub const MAP_HUGETLB: i32 = 262144i32;
pub const MAP_HUGE_MASK: i32 = 63i32;
pub const MAP_HUGE_SHIFT: i32 = 26i32;
pub const MAP_LOCKED: i32 = 8192i32;
pub const MAP_NONBLOCK: i32 = 65536i32;
pub const MAP_NORESERVE: i32 = 16384i32;
pub const MAP_POPULATE: i32 = 32768i32;
pub const MAP_PRIVATE: i32 = 2i32;
pub const MAP_SHARED: i32 = 1i32;
pub const MAP_SHARED_VALIDATE: i32 = 3i32;
pub const MAP_STACK: i32 = 131072i32;
pub const MAP_SYNC: i32 = 524288i32;
pub const MAP_TYPE: i32 = 15i32;
pub const MCL_CURRENT: i32 = 1i32;
pub const MCL_FUTURE: i32 = 2i32;
pub const MCL_ONFAULT: i32 = 4i32;
pub const MS_ASYNC: i32 = 1i32;
pub const MS_INVALIDATE: i32 = 2i32;
pub const MS_SYNC: i32 = 4i32;
pub const POSIX_MADV_DONTNEED: i32 = 4i32;
pub const POSIX_MADV_NORMAL: i32 = 0i32;
pub const POSIX_MADV_RANDOM: i32 = 1i32;
pub const POSIX_MADV_SEQUENTIAL: i32 = 2i32;
pub const POSIX_MADV_WILLNEED: i32 = 3i32;
pub const PROT_EXEC: i32 = 4i32;
pub const PROT_GROWSDOWN: i32 = 16777216i32;
pub const PROT_GROWSUP: i32 = 33554432i32;
pub const PROT_NONE: i32 = 0i32;
pub const PROT_READ: i32 = 1i32;
pub const PROT_WRITE: i32 = 2i32;
pub const _SYS_MMAN_H: i32 = 1i32;
pub type mode_t = u32;
pub type off_t = i64;
