// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(feature = "dirent")]
pub mod dirent;
#[cfg(feature = "fcntl")]
pub mod fcntl;
#[cfg(feature = "inet")]
pub mod inet;
#[cfg(feature = "mmap")]
pub mod mmap;
#[cfg(feature = "netdb")]
pub mod netdb;
#[cfg(feature = "socket")]
pub mod socket;
#[cfg(feature = "stat")]
pub mod stat;
#[cfg(feature = "unistd")]
pub mod unistd;
