//! Rust FFI bindings for OpenSSL (libssl + libcrypto).
//!
//! Generated by `bnd-openssl-gen` — do not edit `src/openssl/` manually.
//!
//! ## Feature-gated modules
//!
//! Each OpenSSL partition is a separate Cargo feature:
//!
//! - **`types`** — opaque type forward declarations (`EVP_MD`, `SSL`, `BIO`, etc.)
//! - **`crypto`** — library version and core utilities
//! - **`rand`** — random number generation

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

pub mod openssl;

// Re-export bnd_macros as windows_link at the crate root so generated code
// that references `windows_link::link!` resolves to our own macro crate.
extern crate bnd_macros as windows_link;
