//! Rust FFI bindings for OpenSSL (libssl + libcrypto).
//!
//! Generated by `bnd-openssl-gen` through the direct-Clang pipeline. Do not
//! edit `src/openssl/` manually.

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(all(target_os = "linux", target_arch = "x86_64", target_env = "gnu"))]
pub mod openssl;

#[cfg(all(target_os = "linux", target_arch = "x86_64", target_env = "gnu"))]
extern crate bnd_macros as windows_link;
