// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(feature = "linux_epoll")]
pub mod epoll;
#[cfg(feature = "linux_eventfd")]
pub mod eventfd;
#[cfg(feature = "linux_inotify")]
pub mod inotify;
#[cfg(feature = "linux_mount")]
pub mod mount;
#[cfg(feature = "linux_sendfile")]
pub mod sendfile;
#[cfg(feature = "linux_signalfd")]
pub mod signalfd;
#[cfg(feature = "linux_timerfd")]
pub mod timerfd;
#[cfg(feature = "linux_types")]
pub mod types;
#[cfg(feature = "linux_xattr")]
pub mod xattr;
