//! POSIX system bindings generated as WinMD metadata.
//!
//! This crate provides Rust bindings for POSIX file I/O, stat, and process
//! APIs on Linux, generated from C system headers via [`bindscrape`] and
//! [`windows-bindgen`].
//!
//! The source tree under `src/PosixFile/` is auto-generated by `bns-posix-gen`.
//! Do not edit it by hand — run `cargo run -p bns-posix-gen` to regenerate.
//!
//! # Modules
//!
//! - [`PosixFile::Fcntl`] — File control (`creat`, `lockf`, `O_*` constants)
//! - [`PosixFile::Stat`] — File status (`stat`, `chmod`, `mkdir`, `struct stat`)
//! - [`PosixFile::Unistd`] — POSIX standard (`read`, `write`, `close`, `fork`, …)
//!
//! # Safety
//!
//! All function bindings are `unsafe` — they call directly into libc.
//!
//! # Example
//!
//! ```no_run
//! use bns_posix::PosixFile::{Fcntl, Unistd};
//!
//! let path = c"/tmp/example.txt";
//! let fd = unsafe { Fcntl::creat(path.as_ptr(), 0o644) };
//! assert!(fd >= 0);
//! unsafe { Unistd::close(fd) };
//! ```

pub mod PosixFile;
