//! POSIX system bindings generated as WinMD metadata.
//!
//! This crate provides Rust bindings for POSIX file I/O, stat, process, and
//! networking APIs on Linux, generated from C system headers via [`bindscrape`]
//! and [`windows-bindgen`].
//!
//! The source tree under `src/PosixFile/` is auto-generated by `bns-posix-gen`.
//! Do not edit it by hand — run `cargo run -p bns-posix-gen` to regenerate.
//!
//! # Modules
//! - [`PosixFile::Dirent`] — Directory entries (`opendir`, `readdir`, `closedir`, `DT_*` constants)
//! - [`PosixFile::Fcntl`] — File control (`creat`, `lockf`, `O_*` constants)
//! - [`PosixFile::Inet`] — Internet addresses (`inet_pton`, `htons`, `sockaddr_in`, `IPPROTO_*`)
//! - [`PosixFile::Mmap`] — Memory mapping (`mmap`, `munmap`, `mprotect`, `MAP_*`/`PROT_*` constants)
//! - [`PosixFile::Netdb`] — Network database (`getaddrinfo`, `gethostbyname`, `addrinfo`, `AI_*`)
//! - [`PosixFile::Socket`] — Sockets (`socket`, `bind`, `listen`, `accept`, `sockaddr`, `AF_*`/`SOCK_*`)
//! - [`PosixFile::Stat`] — File status (`stat`, `chmod`, `mkdir`, `struct stat`)
//! - [`PosixFile::Unistd`] — POSIX standard (`read`, `write`, `close`, `fork`, …)
//!
//! # Safety
//!
//! All function bindings are `unsafe` — they call directly into libc.
//!
//! # Example
//!
//! ```no_run
//! use bns_posix::PosixFile::{Fcntl, Unistd};
//!
//! let path = c"/tmp/example.txt";
//! let fd = unsafe { Fcntl::creat(path.as_ptr(), 0o644) };
//! assert!(fd >= 0);
//! unsafe { Unistd::close(fd) };
//! ```

pub mod PosixFile;
