// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("c" "C" fn sendfile(__out_fd : i32, __in_fd : i32, __offset : *mut bnd_posix::posix::types:: off_t, __count : u64) -> bnd_posix::posix::types:: ssize_t);
pub const _SYS_SENDFILE_H: i32 = 1i32;
