// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("c" "C" fn signalfd(__fd : i32, __mask : *const bnd_posix::posix::signal:: __sigset_t, __flags : i32) -> i32);
pub const SFD_CLOEXEC: u32 = 524288u32;
pub const SFD_NONBLOCK: u32 = 2048u32;
pub const _SYS_SIGNALFD_H: i32 = 1i32;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct signalfd_siginfo {
    pub ssi_signo: u32,
    pub ssi_errno: i32,
    pub ssi_code: i32,
    pub ssi_pid: u32,
    pub ssi_uid: u32,
    pub ssi_fd: i32,
    pub ssi_tid: u32,
    pub ssi_band: u32,
    pub ssi_overrun: u32,
    pub ssi_trapno: u32,
    pub ssi_status: i32,
    pub ssi_int: i32,
    pub ssi_ptr: u64,
    pub ssi_utime: u64,
    pub ssi_stime: u64,
    pub ssi_addr: u64,
    pub ssi_addr_lsb: u16,
    pub __pad2: u16,
    pub ssi_syscall: i32,
    pub ssi_call_addr: u64,
    pub ssi_arch: u32,
    pub __pad: [u8; 28],
}
impl Default for signalfd_siginfo {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
