windows_link::link!("c" "C" fn madvise(__addr : *mut core::ffi::c_void, __len : u64, __advice : i32) -> i32);
windows_link::link!("c" "C" fn mincore(__start : *mut core::ffi::c_void, __len : u64, __vec : *mut u8) -> i32);
windows_link::link!("c" "C" fn mlock(__addr : *const core::ffi::c_void, __len : u64) -> i32);
windows_link::link!("c" "C" fn mlockall(__flags : i32) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn mmap(__addr : *mut core::ffi::c_void, __len : u64, __prot : i32, __flags : i32, __fd : i32, __offset : super::types::__off_t) -> *mut core::ffi::c_void);
windows_link::link!("c" "C" fn mprotect(__addr : *mut core::ffi::c_void, __len : u64, __prot : i32) -> i32);
windows_link::link!("c" "C" fn msync(__addr : *mut core::ffi::c_void, __len : u64, __flags : i32) -> i32);
windows_link::link!("c" "C" fn munlock(__addr : *const core::ffi::c_void, __len : u64) -> i32);
windows_link::link!("c" "C" fn munlockall() -> i32);
windows_link::link!("c" "C" fn munmap(__addr : *mut core::ffi::c_void, __len : u64) -> i32);
windows_link::link!("c" "C" fn posix_madvise(__addr : *mut core::ffi::c_void, __len : u64, __advice : i32) -> i32);
#[cfg(feature = "posix_types")]
windows_link::link!("c" "C" fn shm_open(__name : *const i8, __oflag : i32, __mode : super::types::mode_t) -> i32);
windows_link::link!("c" "C" fn shm_unlink(__name : *const i8) -> i32);
pub const MADV_COLD: i32 = 20;
pub const MADV_COLLAPSE: i32 = 25;
pub const MADV_DODUMP: i32 = 17;
pub const MADV_DOFORK: i32 = 11;
pub const MADV_DONTDUMP: i32 = 16;
pub const MADV_DONTFORK: i32 = 10;
pub const MADV_DONTNEED: i32 = 4;
pub const MADV_DONTNEED_LOCKED: i32 = 24;
pub const MADV_FREE: i32 = 8;
pub const MADV_GUARD_INSTALL: i32 = 102;
pub const MADV_GUARD_REMOVE: i32 = 103;
pub const MADV_HUGEPAGE: i32 = 14;
pub const MADV_HWPOISON: i32 = 100;
pub const MADV_KEEPONFORK: i32 = 19;
pub const MADV_MERGEABLE: i32 = 12;
pub const MADV_NOHUGEPAGE: i32 = 15;
pub const MADV_NORMAL: i32 = 0;
pub const MADV_PAGEOUT: i32 = 21;
pub const MADV_POPULATE_READ: i32 = 22;
pub const MADV_POPULATE_WRITE: i32 = 23;
pub const MADV_RANDOM: i32 = 1;
pub const MADV_REMOVE: i32 = 9;
pub const MADV_SEQUENTIAL: i32 = 2;
pub const MADV_UNMERGEABLE: i32 = 13;
pub const MADV_WILLNEED: i32 = 3;
pub const MADV_WIPEONFORK: i32 = 18;
pub const MAP_ANONYMOUS: i32 = 32;
pub const MAP_DENYWRITE: i32 = 2048;
pub const MAP_DROPPABLE: i32 = 8;
pub const MAP_EXECUTABLE: i32 = 4096;
pub const MAP_FILE: i32 = 0;
pub const MAP_FIXED: i32 = 16;
pub const MAP_FIXED_NOREPLACE: i32 = 1048576;
pub const MAP_GROWSDOWN: i32 = 256;
pub const MAP_HUGETLB: i32 = 262144;
pub const MAP_HUGE_MASK: i32 = 63;
pub const MAP_HUGE_SHIFT: i32 = 26;
pub const MAP_LOCKED: i32 = 8192;
pub const MAP_NONBLOCK: i32 = 65536;
pub const MAP_NORESERVE: i32 = 16384;
pub const MAP_POPULATE: i32 = 32768;
pub const MAP_PRIVATE: i32 = 2;
pub const MAP_SHARED: i32 = 1;
pub const MAP_SHARED_VALIDATE: i32 = 3;
pub const MAP_STACK: i32 = 131072;
pub const MAP_SYNC: i32 = 524288;
pub const MAP_TYPE: i32 = 15;
pub const MCL_CURRENT: i32 = 1;
pub const MCL_FUTURE: i32 = 2;
pub const MCL_ONFAULT: i32 = 4;
pub const MS_ASYNC: i32 = 1;
pub const MS_INVALIDATE: i32 = 2;
pub const MS_SYNC: i32 = 4;
pub const POSIX_MADV_DONTNEED: i32 = 4;
pub const POSIX_MADV_NORMAL: i32 = 0;
pub const POSIX_MADV_RANDOM: i32 = 1;
pub const POSIX_MADV_SEQUENTIAL: i32 = 2;
pub const POSIX_MADV_WILLNEED: i32 = 3;
pub const PROT_EXEC: i32 = 4;
pub const PROT_GROWSDOWN: i32 = 16777216;
pub const PROT_GROWSUP: i32 = 33554432;
pub const PROT_NONE: i32 = 0;
pub const PROT_READ: i32 = 1;
pub const PROT_WRITE: i32 = 2;
pub const _SYS_MMAN_H: i32 = 1;
