// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("c" "C" fn fgetxattr(__fd : i32, __name : *const i8, __value : *mut core::ffi::c_void, __size : u64) -> bnd_posix::posix::types:: ssize_t);
windows_link::link!("c" "C" fn flistxattr(__fd : i32, __list : *mut i8, __size : u64) -> bnd_posix::posix::types:: ssize_t);
windows_link::link!("c" "C" fn fremovexattr(__fd : i32, __name : *const i8) -> i32);
windows_link::link!("c" "C" fn fsetxattr(__fd : i32, __name : *const i8, __value : *const core::ffi::c_void, __size : u64, __flags : i32) -> i32);
windows_link::link!("c" "C" fn getxattr(__path : *const i8, __name : *const i8, __value : *mut core::ffi::c_void, __size : u64) -> bnd_posix::posix::types:: ssize_t);
windows_link::link!("c" "C" fn lgetxattr(__path : *const i8, __name : *const i8, __value : *mut core::ffi::c_void, __size : u64) -> bnd_posix::posix::types:: ssize_t);
windows_link::link!("c" "C" fn listxattr(__path : *const i8, __list : *mut i8, __size : u64) -> bnd_posix::posix::types:: ssize_t);
windows_link::link!("c" "C" fn llistxattr(__path : *const i8, __list : *mut i8, __size : u64) -> bnd_posix::posix::types:: ssize_t);
windows_link::link!("c" "C" fn lremovexattr(__path : *const i8, __name : *const i8) -> i32);
windows_link::link!("c" "C" fn lsetxattr(__path : *const i8, __name : *const i8, __value : *const core::ffi::c_void, __size : u64, __flags : i32) -> i32);
windows_link::link!("c" "C" fn removexattr(__path : *const i8, __name : *const i8) -> i32);
windows_link::link!("c" "C" fn setxattr(__path : *const i8, __name : *const i8, __value : *const core::ffi::c_void, __size : u64, __flags : i32) -> i32);
pub const XATTR_CREATE: u32 = 1u32;
pub const XATTR_REPLACE: u32 = 2u32;
pub const _SYS_XATTR_H: i32 = 1i32;
