// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

pub const _BITS_TYPES_H: i32 = 1i32;
pub const _SYS_TYPES_H: i32 = 1i32;
pub const __BIT_TYPES_DEFINED__: i32 = 1i32;
pub type __blkcnt64_t = i64;
pub type __blkcnt_t = i64;
pub type __blksize_t = i64;
pub type __caddr_t = *mut i8;
pub type __clock_t = i64;
pub type __clockid_t = i32;
pub type __daddr_t = i32;
pub type __dev_t = u64;
pub type __fsblkcnt64_t = u64;
pub type __fsblkcnt_t = u64;
pub type __fsfilcnt64_t = u64;
pub type __fsfilcnt_t = u64;
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub struct __fsid_t {
    pub __val: [i32; 2],
}
impl Default for __fsid_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type __fsword_t = i64;
pub type __gid_t = u32;
pub type __id_t = u32;
pub type __ino64_t = u64;
pub type __ino_t = u64;
pub type __int16_t = i16;
pub type __int32_t = i32;
pub type __int64_t = i64;
pub type __int8_t = i8;
pub type __int_least16_t = __int16_t;
pub type __int_least32_t = __int32_t;
pub type __int_least64_t = __int64_t;
pub type __int_least8_t = __int8_t;
pub type __intmax_t = i64;
pub type __intptr_t = i64;
pub type __key_t = i32;
pub type __loff_t = __off64_t;
pub type __mode_t = u32;
pub type __nlink_t = u64;
pub type __off64_t = i64;
pub type __off_t = i64;
pub type __pid_t = i32;
pub type __quad_t = i64;
pub type __rlim64_t = u64;
pub type __rlim_t = u64;
pub type __sig_atomic_t = i32;
pub type __socklen_t = u32;
pub type __ssize_t = i64;
pub type __suseconds64_t = i64;
pub type __suseconds_t = i64;
pub type __syscall_slong_t = i64;
pub type __syscall_ulong_t = u64;
pub type __time_t = i64;
pub type __timer_t = *mut core::ffi::c_void;
pub type __u_char = u8;
pub type __u_int = u32;
pub type __u_long = u64;
pub type __u_quad_t = u64;
pub type __u_short = u16;
pub type __uid_t = u32;
pub type __uint16_t = u16;
pub type __uint32_t = u32;
pub type __uint64_t = u64;
pub type __uint8_t = u8;
pub type __uint_least16_t = __uint16_t;
pub type __uint_least32_t = __uint32_t;
pub type __uint_least64_t = __uint64_t;
pub type __uint_least8_t = __uint8_t;
pub type __uintmax_t = u64;
pub type __useconds_t = u32;
pub type blkcnt_t = __blkcnt_t;
pub type blksize_t = __blksize_t;
pub type caddr_t = __caddr_t;
pub type daddr_t = __daddr_t;
pub type dev_t = __dev_t;
pub type fsblkcnt_t = __fsblkcnt_t;
pub type fsfilcnt_t = __fsfilcnt_t;
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct fsid_t {
    pub Value: __fsid_t,
}
pub type gid_t = __gid_t;
pub type id_t = __id_t;
pub type ino_t = __ino_t;
pub type key_t = __key_t;
pub type loff_t = __loff_t;
pub type mode_t = __mode_t;
pub type nlink_t = __nlink_t;
pub type off_t = __off_t;
pub type pid_t = __pid_t;
pub type quad_t = __quad_t;
pub type register_t = i64;
pub type ssize_t = __ssize_t;
pub type u_char = __u_char;
pub type u_int = __u_int;
pub type u_int16_t = __uint16_t;
pub type u_int32_t = __uint32_t;
pub type u_int64_t = __uint64_t;
pub type u_int8_t = __uint8_t;
pub type u_long = __u_long;
pub type u_quad_t = __u_quad_t;
pub type u_short = __u_short;
pub type uid_t = __uid_t;
pub type uint = u32;
pub type ulong = u64;
pub type ushort = u16;
