// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("crypto" "C" fn CRYPTO_THREAD_cleanup_local(key : *mut CRYPTO_THREAD_LOCAL) -> i32);
windows_link::link!("crypto" "C" fn CRYPTO_THREAD_compare_id(a : CRYPTO_THREAD_ID, b : CRYPTO_THREAD_ID) -> i32);
windows_link::link!("crypto" "C" fn CRYPTO_THREAD_get_current_id() -> CRYPTO_THREAD_ID);
windows_link::link!("crypto" "C" fn CRYPTO_THREAD_get_local(key : *mut CRYPTO_THREAD_LOCAL) -> *mut core::ffi::c_void);
windows_link::link!("crypto" "C" fn CRYPTO_THREAD_init_local(key : *mut CRYPTO_THREAD_LOCAL, cleanup : *mut isize) -> i32);
windows_link::link!("crypto" "C" fn CRYPTO_THREAD_lock_free(lock : *mut CRYPTO_RWLOCK));
windows_link::link!("crypto" "C" fn CRYPTO_THREAD_lock_new() -> *mut CRYPTO_RWLOCK);
windows_link::link!("crypto" "C" fn CRYPTO_THREAD_read_lock(lock : *mut CRYPTO_RWLOCK) -> i32);
windows_link::link!("crypto" "C" fn CRYPTO_THREAD_run_once(once : *mut CRYPTO_ONCE, init : *mut isize) -> i32);
windows_link::link!("crypto" "C" fn CRYPTO_THREAD_set_local(key : *mut CRYPTO_THREAD_LOCAL, val : *mut core::ffi::c_void) -> i32);
windows_link::link!("crypto" "C" fn CRYPTO_THREAD_unlock(lock : *mut CRYPTO_RWLOCK) -> i32);
windows_link::link!("crypto" "C" fn CRYPTO_THREAD_write_lock(lock : *mut CRYPTO_RWLOCK) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn CRYPTO_alloc_ex_data(class_index : i32, obj : *mut core::ffi::c_void, ad : *mut super::types:: CRYPTO_EX_DATA, idx : i32) -> i32);
windows_link::link!("crypto" "C" fn CRYPTO_atomic_add(val : *mut i32, amount : i32, ret : *mut i32, lock : *mut CRYPTO_RWLOCK) -> i32);
windows_link::link!("crypto" "C" fn CRYPTO_atomic_load(val : *mut u64, ret : *mut u64, lock : *mut CRYPTO_RWLOCK) -> i32);
windows_link::link!("crypto" "C" fn CRYPTO_atomic_or(val : *mut u64, op : u64, ret : *mut u64, lock : *mut CRYPTO_RWLOCK) -> i32);
windows_link::link!("crypto" "C" fn CRYPTO_clear_free(ptr : *mut core::ffi::c_void, num : u64, file : *const i8, line : i32));
windows_link::link!("crypto" "C" fn CRYPTO_clear_realloc(addr : *mut core::ffi::c_void, old_num : u64, num : u64, file : *const i8, line : i32) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn CRYPTO_dup_ex_data(class_index : i32, to : *mut super::types:: CRYPTO_EX_DATA, from : *const super::types:: CRYPTO_EX_DATA) -> i32);
windows_link::link!("crypto" "C" fn CRYPTO_free(ptr : *mut core::ffi::c_void, file : *const i8, line : i32));
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn CRYPTO_free_ex_data(class_index : i32, obj : *mut core::ffi::c_void, ad : *mut super::types:: CRYPTO_EX_DATA));
windows_link::link!("crypto" "C" fn CRYPTO_free_ex_index(class_index : i32, idx : i32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn CRYPTO_get_ex_data(ad : *const super::types:: CRYPTO_EX_DATA, idx : i32) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn CRYPTO_get_ex_new_index(class_index : i32, argl : i64, argp : *mut core::ffi::c_void, new_func : *mut CRYPTO_EX_new, dup_func : *mut CRYPTO_EX_dup, free_func : *mut CRYPTO_EX_free) -> i32);
windows_link::link!("crypto" "C" fn CRYPTO_get_mem_functions(malloc_fn : *mut CRYPTO_malloc_fn, realloc_fn : *mut CRYPTO_realloc_fn, free_fn : *mut CRYPTO_free_fn));
windows_link::link!("crypto" "C" fn CRYPTO_malloc(num : u64, file : *const i8, line : i32) -> *mut core::ffi::c_void);
windows_link::link!("crypto" "C" fn CRYPTO_memcmp(in_a : *const core::ffi::c_void, in_b : *const core::ffi::c_void, len : u64) -> i32);
windows_link::link!("crypto" "C" fn CRYPTO_memdup(str : *const core::ffi::c_void, siz : u64, file : *const i8, line : i32) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn CRYPTO_new_ex_data(class_index : i32, obj : *mut core::ffi::c_void, ad : *mut super::types:: CRYPTO_EX_DATA) -> i32);
windows_link::link!("crypto" "C" fn CRYPTO_realloc(addr : *mut core::ffi::c_void, num : u64, file : *const i8, line : i32) -> *mut core::ffi::c_void);
windows_link::link!("crypto" "C" fn CRYPTO_secure_actual_size(ptr : *mut core::ffi::c_void) -> u64);
windows_link::link!("crypto" "C" fn CRYPTO_secure_allocated(ptr : *const core::ffi::c_void) -> i32);
windows_link::link!("crypto" "C" fn CRYPTO_secure_clear_free(ptr : *mut core::ffi::c_void, num : u64, file : *const i8, line : i32));
windows_link::link!("crypto" "C" fn CRYPTO_secure_free(ptr : *mut core::ffi::c_void, file : *const i8, line : i32));
windows_link::link!("crypto" "C" fn CRYPTO_secure_malloc(num : u64, file : *const i8, line : i32) -> *mut core::ffi::c_void);
windows_link::link!("crypto" "C" fn CRYPTO_secure_malloc_done() -> i32);
windows_link::link!("crypto" "C" fn CRYPTO_secure_malloc_init(sz : u64, minsize : u64) -> i32);
windows_link::link!("crypto" "C" fn CRYPTO_secure_malloc_initialized() -> i32);
windows_link::link!("crypto" "C" fn CRYPTO_secure_used() -> u64);
windows_link::link!("crypto" "C" fn CRYPTO_secure_zalloc(num : u64, file : *const i8, line : i32) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn CRYPTO_set_ex_data(ad : *mut super::types:: CRYPTO_EX_DATA, idx : i32, val : *mut core::ffi::c_void) -> i32);
windows_link::link!("crypto" "C" fn CRYPTO_set_mem_functions(malloc_fn : CRYPTO_malloc_fn, realloc_fn : CRYPTO_realloc_fn, free_fn : CRYPTO_free_fn) -> i32);
windows_link::link!("crypto" "C" fn CRYPTO_strdup(str : *const i8, file : *const i8, line : i32) -> *mut i8);
windows_link::link!("crypto" "C" fn CRYPTO_strndup(str : *const i8, s : u64, file : *const i8, line : i32) -> *mut i8);
windows_link::link!("crypto" "C" fn CRYPTO_zalloc(num : u64, file : *const i8, line : i32) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn OPENSSL_INIT_free(settings : *mut super::types:: OPENSSL_INIT_SETTINGS));
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn OPENSSL_INIT_new() -> *mut super::types:: OPENSSL_INIT_SETTINGS);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn OPENSSL_INIT_set_config_appname(settings : *mut super::types:: OPENSSL_INIT_SETTINGS, config_appname : *const i8) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn OPENSSL_INIT_set_config_file_flags(settings : *mut super::types:: OPENSSL_INIT_SETTINGS, flags : u64));
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn OPENSSL_INIT_set_config_filename(settings : *mut super::types:: OPENSSL_INIT_SETTINGS, config_filename : *const i8) -> i32);
windows_link::link!("crypto" "C" fn OPENSSL_atexit(handler : *mut isize) -> i32);
windows_link::link!("crypto" "C" fn OPENSSL_buf2hexstr(buf : *const u8, buflen : i64) -> *mut i8);
windows_link::link!("crypto" "C" fn OPENSSL_buf2hexstr_ex(str : *mut i8, str_n : u64, strlength : *mut u64, buf : *const u8, buflen : u64, sep : i8) -> i32);
windows_link::link!("crypto" "C" fn OPENSSL_cleanse(ptr : *mut core::ffi::c_void, len : u64));
windows_link::link!("crypto" "C" fn OPENSSL_cleanup());
windows_link::link!("crypto" "C" fn OPENSSL_die(assertion : *const i8, file : *const i8, line : i32));
windows_link::link!("crypto" "C" fn OPENSSL_fork_child());
windows_link::link!("crypto" "C" fn OPENSSL_fork_parent());
windows_link::link!("crypto" "C" fn OPENSSL_fork_prepare());
windows_link::link!("crypto" "C" fn OPENSSL_gmtime(timer : *const i64, result : *mut tm) -> *mut tm);
windows_link::link!("crypto" "C" fn OPENSSL_gmtime_adj(tm : *mut tm, offset_day : i32, offset_sec : i64) -> i32);
windows_link::link!("crypto" "C" fn OPENSSL_gmtime_diff(pday : *mut i32, psec : *mut i32, from : *const tm, to : *const tm) -> i32);
windows_link::link!("crypto" "C" fn OPENSSL_hexchar2int(c : u8) -> i32);
windows_link::link!("crypto" "C" fn OPENSSL_hexstr2buf(str : *const i8, buflen : *mut i64) -> *mut u8);
windows_link::link!("crypto" "C" fn OPENSSL_hexstr2buf_ex(buf : *mut u8, buf_n : u64, buflen : *mut u64, str : *const i8, sep : i8) -> i32);
windows_link::link!("crypto" "C" fn OPENSSL_info(r#type : i32) -> *mut i8);
windows_link::link!("crypto" "C" fn OPENSSL_init());
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn OPENSSL_init_crypto(opts : u64, settings : *const super::types:: OPENSSL_INIT_SETTINGS) -> i32);
windows_link::link!("crypto" "C" fn OPENSSL_isservice() -> i32);
windows_link::link!("crypto" "C" fn OPENSSL_issetugid() -> i32);
windows_link::link!("crypto" "C" fn OPENSSL_strcasecmp(s1 : *const i8, s2 : *const i8) -> i32);
windows_link::link!("crypto" "C" fn OPENSSL_strlcat(dst : *mut i8, src : *const i8, siz : u64) -> u64);
windows_link::link!("crypto" "C" fn OPENSSL_strlcpy(dst : *mut i8, src : *const i8, siz : u64) -> u64);
windows_link::link!("crypto" "C" fn OPENSSL_strncasecmp(s1 : *const i8, s2 : *const i8, n : u64) -> i32);
windows_link::link!("crypto" "C" fn OPENSSL_strnlen(str : *const i8, maxlen : u64) -> u64);
windows_link::link!("crypto" "C" fn OPENSSL_thread_stop());
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn OPENSSL_thread_stop_ex(ctx : *mut super::types:: OSSL_LIB_CTX));
windows_link::link!("crypto" "C" fn OPENSSL_version_build_metadata() -> *mut i8);
windows_link::link!("crypto" "C" fn OPENSSL_version_major() -> u32);
windows_link::link!("crypto" "C" fn OPENSSL_version_minor() -> u32);
windows_link::link!("crypto" "C" fn OPENSSL_version_patch() -> u32);
windows_link::link!("crypto" "C" fn OPENSSL_version_pre_release() -> *mut i8);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn OSSL_LIB_CTX_free(param0 : *mut super::types:: OSSL_LIB_CTX));
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn OSSL_LIB_CTX_get0_global_default() -> *mut super::types:: OSSL_LIB_CTX);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn OSSL_LIB_CTX_load_config(ctx : *mut super::types:: OSSL_LIB_CTX, config_file : *const i8) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn OSSL_LIB_CTX_new() -> *mut super::types:: OSSL_LIB_CTX);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn OSSL_LIB_CTX_new_child(handle : *const core::ffi::c_void, r#in : *const super::types:: OSSL_DISPATCH) -> *mut super::types:: OSSL_LIB_CTX);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn OSSL_LIB_CTX_new_from_dispatch(handle : *const core::ffi::c_void, r#in : *const super::types:: OSSL_DISPATCH) -> *mut super::types:: OSSL_LIB_CTX);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn OSSL_LIB_CTX_set0_default(libctx : *mut super::types:: OSSL_LIB_CTX) -> *mut super::types:: OSSL_LIB_CTX);
windows_link::link!("crypto" "C" fn OpenSSL_version(r#type : i32) -> *mut i8);
windows_link::link!("crypto" "C" fn OpenSSL_version_num() -> u64);
windows_link::link!("crypto" "C" fn ossl_check_const_void_sk_type(sk : *const core::ffi::c_void) -> *mut core::ffi::c_void);
windows_link::link!("crypto" "C" fn ossl_check_void_compfunc_type(cmp : sk_void_compfunc) -> *mut isize);
windows_link::link!("crypto" "C" fn ossl_check_void_copyfunc_type(cpy : sk_void_copyfunc) -> *mut isize);
windows_link::link!("crypto" "C" fn ossl_check_void_freefunc_type(fr : sk_void_freefunc) -> *mut isize);
windows_link::link!("crypto" "C" fn ossl_check_void_sk_type(sk : *mut core::ffi::c_void) -> *mut core::ffi::c_void);
windows_link::link!("crypto" "C" fn ossl_check_void_type(ptr : *mut core::ffi::c_void) -> *mut core::ffi::c_void);
pub const CRYPTO_EX_INDEX_APP: i32 = 13i32;
pub const CRYPTO_EX_INDEX_BIO: i32 = 12i32;
pub const CRYPTO_EX_INDEX_DH: i32 = 6i32;
pub const CRYPTO_EX_INDEX_DSA: i32 = 7i32;
pub const CRYPTO_EX_INDEX_EC_KEY: i32 = 8i32;
pub const CRYPTO_EX_INDEX_ENGINE: i32 = 10i32;
pub const CRYPTO_EX_INDEX_EVP_PKEY: i32 = 17i32;
pub const CRYPTO_EX_INDEX_OSSL_LIB_CTX: i32 = 16i32;
pub const CRYPTO_EX_INDEX_RAND_DRBG: i32 = 15i32;
pub const CRYPTO_EX_INDEX_RSA: i32 = 9i32;
pub const CRYPTO_EX_INDEX_SSL: i32 = 0i32;
pub const CRYPTO_EX_INDEX_SSL_CTX: i32 = 1i32;
pub const CRYPTO_EX_INDEX_SSL_SESSION: i32 = 2i32;
pub const CRYPTO_EX_INDEX_UI: i32 = 11i32;
pub const CRYPTO_EX_INDEX_UI_METHOD: i32 = 14i32;
pub const CRYPTO_EX_INDEX_X509: i32 = 3i32;
pub const CRYPTO_EX_INDEX_X509_STORE: i32 = 4i32;
pub const CRYPTO_EX_INDEX_X509_STORE_CTX: i32 = 5i32;
pub const CRYPTO_EX_INDEX__COUNT: i32 = 18i32;
#[cfg(feature = "types")]
pub type CRYPTO_EX_dup = Option<
    unsafe extern "system" fn(
        param0: *const super::types::CRYPTO_EX_DATA,
        param1: *const super::types::CRYPTO_EX_DATA,
        param2: *const *const core::ffi::c_void,
        param3: i32,
        param4: i64,
        param5: *const core::ffi::c_void,
    ) -> i32,
>;
#[cfg(feature = "types")]
pub type CRYPTO_EX_free = Option<
    unsafe extern "system" fn(
        param0: *const core::ffi::c_void,
        param1: *const core::ffi::c_void,
        param2: *const super::types::CRYPTO_EX_DATA,
        param3: i32,
        param4: i64,
        param5: *const core::ffi::c_void,
    ),
>;
#[cfg(feature = "types")]
pub type CRYPTO_EX_new = Option<
    unsafe extern "system" fn(
        param0: *const core::ffi::c_void,
        param1: *const core::ffi::c_void,
        param2: *const super::types::CRYPTO_EX_DATA,
        param3: i32,
        param4: i64,
        param5: *const core::ffi::c_void,
    ),
>;
pub const CRYPTO_LOCK: i32 = 1i32;
pub type CRYPTO_ONCE = i32;
pub const CRYPTO_READ: i32 = 4i32;
pub type CRYPTO_RWLOCK = isize;
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct CRYPTO_THREADID {
    pub Value: crypto_threadid_st,
}
pub type CRYPTO_THREAD_ID = u64;
pub type CRYPTO_THREAD_LOCAL = u32;
pub const CRYPTO_UNLOCK: i32 = 2i32;
pub const CRYPTO_WRITE: i32 = 8i32;
#[repr(C, packed(4))]
#[derive(Clone, Copy, Default)]
pub struct CRYPTO_dynlock {
    pub dummy: i32,
}
pub type CRYPTO_free_fn = Option<
    unsafe extern "system" fn(param0: *const core::ffi::c_void, param1: *const i8, param2: i32),
>;
pub type CRYPTO_malloc_fn = Option<
    unsafe extern "system" fn(
        param0: u64,
        param1: *const i8,
        param2: i32,
    ) -> *mut core::ffi::c_void,
>;
pub type CRYPTO_realloc_fn = Option<
    unsafe extern "system" fn(
        param0: *const core::ffi::c_void,
        param1: u64,
        param2: *const i8,
        param3: i32,
    ) -> *mut core::ffi::c_void,
>;
pub const OPENSSL_BUILT_ON: i32 = 2i32;
pub const OPENSSL_CFLAGS: i32 = 1i32;
pub const OPENSSL_CPU_INFO: i32 = 9i32;
pub const OPENSSL_DIR: i32 = 4i32;
pub const OPENSSL_ENGINES_DIR: i32 = 5i32;
pub const OPENSSL_FULL_VERSION_STRING: i32 = 7i32;
pub const OPENSSL_INFO_CONFIG_DIR: i32 = 1001i32;
pub const OPENSSL_INFO_CPU_SETTINGS: i32 = 1008i32;
pub const OPENSSL_INFO_DIR_FILENAME_SEPARATOR: i32 = 1005i32;
pub const OPENSSL_INFO_DSO_EXTENSION: i32 = 1004i32;
pub const OPENSSL_INFO_ENGINES_DIR: i32 = 1002i32;
pub const OPENSSL_INFO_LIST_SEPARATOR: i32 = 1006i32;
pub const OPENSSL_INFO_MODULES_DIR: i32 = 1003i32;
pub const OPENSSL_INFO_SEED_SOURCE: i32 = 1007i32;
pub const OPENSSL_INIT_ADD_ALL_CIPHERS: i32 = 4i32;
pub const OPENSSL_INIT_ADD_ALL_DIGESTS: i32 = 8i32;
pub const OPENSSL_INIT_ASYNC: i32 = 256i32;
pub const OPENSSL_INIT_ATFORK: i32 = 131072i32;
pub const OPENSSL_INIT_ENGINE_AFALG: i32 = 32768i32;
pub const OPENSSL_INIT_ENGINE_CAPI: i32 = 8192i32;
pub const OPENSSL_INIT_ENGINE_CRYPTODEV: i32 = 4096i32;
pub const OPENSSL_INIT_ENGINE_DYNAMIC: i32 = 1024i32;
pub const OPENSSL_INIT_ENGINE_OPENSSL: i32 = 2048i32;
pub const OPENSSL_INIT_ENGINE_PADLOCK: i32 = 16384i32;
pub const OPENSSL_INIT_ENGINE_RDRAND: i32 = 512i32;
pub const OPENSSL_INIT_LOAD_CONFIG: i32 = 64i32;
pub const OPENSSL_INIT_LOAD_CRYPTO_STRINGS: i32 = 2i32;
pub const OPENSSL_INIT_NO_ADD_ALL_CIPHERS: i32 = 16i32;
pub const OPENSSL_INIT_NO_ADD_ALL_DIGESTS: i32 = 32i32;
pub const OPENSSL_INIT_NO_ATEXIT: i32 = 524288i32;
pub const OPENSSL_INIT_NO_LOAD_CONFIG: i32 = 128i32;
pub const OPENSSL_INIT_NO_LOAD_CRYPTO_STRINGS: i32 = 1i32;
pub const OPENSSL_MODULES_DIR: i32 = 8i32;
pub const OPENSSL_PLATFORM: i32 = 3i32;
pub const OPENSSL_VERSION: i32 = 0i32;
pub const OPENSSL_VERSION_STRING: i32 = 6i32;
pub const _IO_EOF_SEEN: i32 = 16i32;
pub const _IO_ERR_SEEN: i32 = 32i32;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct _IO_FILE {
    pub _flags: i32,
    pub _IO_read_ptr: *mut i8,
    pub _IO_read_end: *mut i8,
    pub _IO_read_base: *mut i8,
    pub _IO_write_base: *mut i8,
    pub _IO_write_ptr: *mut i8,
    pub _IO_write_end: *mut i8,
    pub _IO_buf_base: *mut i8,
    pub _IO_buf_end: *mut i8,
    pub _IO_save_base: *mut i8,
    pub _IO_backup_base: *mut i8,
    pub _IO_save_end: *mut i8,
    pub _markers: *mut core::ffi::c_void,
    pub _chain: *mut _IO_FILE,
    pub _fileno: i32,
    pub _flags2: i32,
    pub _old_offset: i64,
    pub _cur_column: u16,
    pub _vtable_offset: i8,
    pub _shortbuf: [i8; 1],
    pub _lock: *mut _IO_lock_t,
    pub _offset: i64,
    pub _codecvt: *mut core::ffi::c_void,
    pub _wide_data: *mut core::ffi::c_void,
    pub _freeres_list: *mut _IO_FILE,
    pub _freeres_buf: *mut core::ffi::c_void,
    pub __pad5: u64,
    pub _mode: i32,
    pub _unused2: [i8; 20],
}
impl Default for _IO_FILE {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub const _IO_USER_LOCK: i32 = 32768i32;
pub type _IO_lock_t = isize;
pub const __struct_FILE_defined: i32 = 1i32;
pub const __struct_tm_defined: i32 = 1i32;
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct crypto_ex_data_st {
    pub ctx: *mut super::types::OSSL_LIB_CTX,
    pub sk: *mut core::ffi::c_void,
}
#[cfg(feature = "types")]
impl Default for crypto_ex_data_st {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[derive(Clone, Copy, Default)]
pub struct crypto_threadid_st {
    pub dummy: i32,
}
pub type sk_void_compfunc = Option<
    unsafe extern "system" fn(
        param0: *const *const core::ffi::c_void,
        param1: *const *const core::ffi::c_void,
    ) -> i32,
>;
pub type sk_void_copyfunc =
    Option<unsafe extern "system" fn(param0: *const core::ffi::c_void) -> *mut core::ffi::c_void>;
pub type sk_void_freefunc = Option<unsafe extern "system" fn(param0: *const core::ffi::c_void)>;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct tm {
    pub tm_sec: i32,
    pub tm_min: i32,
    pub tm_hour: i32,
    pub tm_mday: i32,
    pub tm_mon: i32,
    pub tm_year: i32,
    pub tm_wday: i32,
    pub tm_yday: i32,
    pub tm_isdst: i32,
    pub tm_gmtoff: i64,
    pub tm_zone: *mut i8,
}
impl Default for tm {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
