// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("c" "C" fn __cmsg_nxthdr(__mhdr : *const msghdr, __cmsg : *const cmsghdr) -> *mut cmsghdr);
windows_link::link!("c" "C" fn accept(__fd : i32, __addr : *const sockaddr, __addr_len : *const socklen_t) -> i32);
windows_link::link!("c" "C" fn bind(__fd : i32, __addr : *const sockaddr, __len : socklen_t) -> i32);
windows_link::link!("c" "C" fn connect(__fd : i32, __addr : *const sockaddr, __len : socklen_t) -> i32);
windows_link::link!("c" "C" fn getpeername(__fd : i32, __addr : *const sockaddr, __len : *const socklen_t) -> i32);
windows_link::link!("c" "C" fn getsockname(__fd : i32, __addr : *const sockaddr, __len : *const socklen_t) -> i32);
windows_link::link!("c" "C" fn getsockopt(__fd : i32, __level : i32, __optname : i32, __optval : *const core::ffi::c_void, __optlen : *const socklen_t) -> i32);
windows_link::link!("c" "C" fn isfdtype(__fd : i32, __fdtype : i32) -> i32);
windows_link::link!("c" "C" fn listen(__fd : i32, __n : i32) -> i32);
#[cfg(feature = "unistd")]
windows_link::link!("c" "C" fn recv(__fd : i32, __buf : *const core::ffi::c_void, __n : u64, __flags : i32) -> super::unistd:: ssize_t);
#[cfg(feature = "unistd")]
windows_link::link!("c" "C" fn recvfrom(__fd : i32, __buf : *const core::ffi::c_void, __n : u64, __flags : i32, __addr : *const sockaddr, __addr_len : *const socklen_t) -> super::unistd:: ssize_t);
#[cfg(feature = "unistd")]
windows_link::link!("c" "C" fn recvmsg(__fd : i32, __message : *const msghdr, __flags : i32) -> super::unistd:: ssize_t);
#[cfg(feature = "unistd")]
windows_link::link!("c" "C" fn send(__fd : i32, __buf : *const core::ffi::c_void, __n : u64, __flags : i32) -> super::unistd:: ssize_t);
#[cfg(feature = "unistd")]
windows_link::link!("c" "C" fn sendmsg(__fd : i32, __message : *const msghdr, __flags : i32) -> super::unistd:: ssize_t);
#[cfg(feature = "unistd")]
windows_link::link!("c" "C" fn sendto(__fd : i32, __buf : *const core::ffi::c_void, __n : u64, __flags : i32, __addr : *const sockaddr, __addr_len : socklen_t) -> super::unistd:: ssize_t);
windows_link::link!("c" "C" fn setsockopt(__fd : i32, __level : i32, __optname : i32, __optval : *const core::ffi::c_void, __optlen : socklen_t) -> i32);
windows_link::link!("c" "C" fn shutdown(__fd : i32, __how : i32) -> i32);
windows_link::link!("c" "C" fn sockatmark(__fd : i32) -> i32);
windows_link::link!("c" "C" fn socket(__domain : i32, __type : i32, __protocol : i32) -> i32);
windows_link::link!("c" "C" fn socketpair(__domain : i32, __type : i32, __protocol : i32, __fds : *const i32) -> i32);
pub const MSG_BATCH: u32 = 262144u32;
pub const MSG_CMSG_CLOEXEC: u32 = 1073741824u32;
pub const MSG_CONFIRM: u32 = 2048u32;
pub const MSG_CTRUNC: u32 = 8u32;
pub const MSG_DONTROUTE: u32 = 4u32;
pub const MSG_DONTWAIT: u32 = 64u32;
pub const MSG_EOR: u32 = 128u32;
pub const MSG_ERRQUEUE: u32 = 8192u32;
pub const MSG_FASTOPEN: u32 = 536870912u32;
pub const MSG_FIN: u32 = 512u32;
pub const MSG_MORE: u32 = 32768u32;
pub const MSG_NOSIGNAL: u32 = 16384u32;
pub const MSG_OOB: u32 = 1u32;
pub const MSG_PEEK: u32 = 2u32;
pub const MSG_PROXY: u32 = 16u32;
pub const MSG_RST: u32 = 4096u32;
pub const MSG_SYN: u32 = 1024u32;
pub const MSG_TRUNC: u32 = 32u32;
pub const MSG_WAITALL: u32 = 256u32;
pub const MSG_WAITFORONE: u32 = 65536u32;
pub const MSG_ZEROCOPY: u32 = 67108864u32;
pub const PF_ALG: i32 = 38i32;
pub const PF_APPLETALK: i32 = 5i32;
pub const PF_ASH: i32 = 18i32;
pub const PF_ATMPVC: i32 = 8i32;
pub const PF_ATMSVC: i32 = 20i32;
pub const PF_AX25: i32 = 3i32;
pub const PF_BLUETOOTH: i32 = 31i32;
pub const PF_BRIDGE: i32 = 7i32;
pub const PF_CAIF: i32 = 37i32;
pub const PF_CAN: i32 = 29i32;
pub const PF_DECnet: i32 = 12i32;
pub const PF_ECONET: i32 = 19i32;
pub const PF_IB: i32 = 27i32;
pub const PF_IEEE802154: i32 = 36i32;
pub const PF_INET: i32 = 2i32;
pub const PF_INET6: i32 = 10i32;
pub const PF_IPX: i32 = 4i32;
pub const PF_IRDA: i32 = 23i32;
pub const PF_ISDN: i32 = 34i32;
pub const PF_IUCV: i32 = 32i32;
pub const PF_KCM: i32 = 41i32;
pub const PF_KEY: i32 = 15i32;
pub const PF_LLC: i32 = 26i32;
pub const PF_LOCAL: i32 = 1i32;
pub const PF_MAX: i32 = 46i32;
pub const PF_MCTP: i32 = 45i32;
pub const PF_MPLS: i32 = 28i32;
pub const PF_NETBEUI: i32 = 13i32;
pub const PF_NETLINK: i32 = 16i32;
pub const PF_NETROM: i32 = 6i32;
pub const PF_NFC: i32 = 39i32;
pub const PF_PACKET: i32 = 17i32;
pub const PF_PHONET: i32 = 35i32;
pub const PF_PPPOX: i32 = 24i32;
pub const PF_QIPCRTR: i32 = 42i32;
pub const PF_RDS: i32 = 21i32;
pub const PF_ROSE: i32 = 11i32;
pub const PF_RXRPC: i32 = 33i32;
pub const PF_SECURITY: i32 = 14i32;
pub const PF_SMC: i32 = 43i32;
pub const PF_SNA: i32 = 22i32;
pub const PF_TIPC: i32 = 30i32;
pub const PF_UNSPEC: i32 = 0i32;
pub const PF_VSOCK: i32 = 40i32;
pub const PF_WANPIPE: i32 = 25i32;
pub const PF_X25: i32 = 9i32;
pub const PF_XDP: i32 = 44i32;
pub const SCM_RIGHTS: u32 = 1u32;
pub const SHUT_RD: u32 = 0u32;
pub const SHUT_RDWR: u32 = 2u32;
pub const SHUT_WR: u32 = 1u32;
pub const SOCK_CLOEXEC: u32 = 524288u32;
pub const SOCK_DCCP: u32 = 6u32;
pub const SOCK_DGRAM: u32 = 2u32;
pub const SOCK_NONBLOCK: u32 = 2048u32;
pub const SOCK_PACKET: u32 = 10u32;
pub const SOCK_RAW: u32 = 3u32;
pub const SOCK_RDM: u32 = 4u32;
pub const SOCK_SEQPACKET: u32 = 5u32;
pub const SOCK_STREAM: u32 = 1u32;
pub const SOL_AAL: i32 = 265i32;
pub const SOL_ALG: i32 = 279i32;
pub const SOL_ATM: i32 = 264i32;
pub const SOL_BLUETOOTH: i32 = 274i32;
pub const SOL_CAIF: i32 = 278i32;
pub const SOL_DCCP: i32 = 269i32;
pub const SOL_DECNET: i32 = 261i32;
pub const SOL_IRDA: i32 = 266i32;
pub const SOL_IUCV: i32 = 277i32;
pub const SOL_KCM: i32 = 281i32;
pub const SOL_LLC: i32 = 268i32;
pub const SOL_MCTP: i32 = 285i32;
pub const SOL_MPTCP: i32 = 284i32;
pub const SOL_NETBEUI: i32 = 267i32;
pub const SOL_NETLINK: i32 = 270i32;
pub const SOL_NFC: i32 = 280i32;
pub const SOL_PACKET: i32 = 263i32;
pub const SOL_PNPIPE: i32 = 275i32;
pub const SOL_PPPOL2TP: i32 = 273i32;
pub const SOL_RAW: i32 = 255i32;
pub const SOL_RDS: i32 = 276i32;
pub const SOL_RXRPC: i32 = 272i32;
pub const SOL_SMC: i32 = 286i32;
pub const SOL_TIPC: i32 = 271i32;
pub const SOL_TLS: i32 = 282i32;
pub const SOL_X25: i32 = 262i32;
pub const SOL_XDP: i32 = 283i32;
pub const SOMAXCONN: i32 = 4096i32;
pub const _SYS_SOCKET_H: i32 = 1i32;
pub const __iovec_defined: i32 = 1i32;
pub type __socket_type = u32;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct cmsghdr {
    pub cmsg_len: u64,
    pub cmsg_level: i32,
    pub cmsg_type: i32,
    pub __cmsg_data: *mut u8,
}
impl Default for cmsghdr {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct iovec {
    pub iov_base: *mut core::ffi::c_void,
    pub iov_len: u64,
}
impl Default for iovec {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[derive(Clone, Copy, Default)]
pub struct linger {
    pub l_onoff: i32,
    pub l_linger: i32,
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct msghdr {
    pub msg_name: *mut core::ffi::c_void,
    pub msg_namelen: socklen_t,
    pub msg_iov: *mut iovec,
    pub msg_iovlen: u64,
    pub msg_control: *mut core::ffi::c_void,
    pub msg_controllen: u64,
    pub msg_flags: i32,
}
impl Default for msghdr {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(2))]
#[derive(Clone, Copy)]
pub struct sockaddr {
    pub sa_family: u16,
    pub sa_data: [i8; 14],
}
impl Default for sockaddr {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct sockaddr_storage {
    pub ss_family: u16,
    pub __ss_padding: [i8; 118],
    pub __ss_align: u64,
}
impl Default for sockaddr_storage {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type socklen_t = u32;
