// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("c" "C" fn bindresvport(__sockfd : i32, __sock_in : *const sockaddr_in) -> i32);
windows_link::link!("c" "C" fn bindresvport6(__sockfd : i32, __sock_in : *const sockaddr_in6) -> i32);
windows_link::link!("c" "C" fn htonl(__hostlong : u32) -> u32);
windows_link::link!("c" "C" fn htons(__hostshort : u16) -> u16);
windows_link::link!("c" "C" fn inet_addr(__cp : *const i8) -> in_addr_t);
windows_link::link!("c" "C" fn inet_aton(__cp : *const i8, __inp : *const in_addr) -> i32);
windows_link::link!("c" "C" fn inet_lnaof(__in : in_addr) -> in_addr_t);
windows_link::link!("c" "C" fn inet_makeaddr(__net : in_addr_t, __host : in_addr_t) -> in_addr);
windows_link::link!("c" "C" fn inet_net_ntop(__af : i32, __cp : *const core::ffi::c_void, __bits : i32, __buf : *const i8, __len : u64) -> *mut i8);
windows_link::link!("c" "C" fn inet_net_pton(__af : i32, __cp : *const i8, __buf : *const core::ffi::c_void, __len : u64) -> i32);
windows_link::link!("c" "C" fn inet_neta(__net : in_addr_t, __buf : *const i8, __len : u64) -> *mut i8);
windows_link::link!("c" "C" fn inet_netof(__in : in_addr) -> in_addr_t);
windows_link::link!("c" "C" fn inet_network(__cp : *const i8) -> in_addr_t);
windows_link::link!("c" "C" fn inet_nsap_addr(__cp : *const i8, __buf : *const u8, __len : i32) -> u32);
windows_link::link!("c" "C" fn inet_nsap_ntoa(__len : i32, __cp : *const u8, __buf : *const i8) -> *mut i8);
windows_link::link!("c" "C" fn inet_ntoa(__in : in_addr) -> *mut i8);
#[cfg(feature = "Socket")]
windows_link::link!("c" "C" fn inet_ntop(__af : i32, __cp : *const core::ffi::c_void, __buf : *const i8, __len : super::Socket:: socklen_t) -> *mut i8);
windows_link::link!("c" "C" fn inet_pton(__af : i32, __cp : *const i8, __buf : *const core::ffi::c_void) -> i32);
windows_link::link!("c" "C" fn ntohl(__netlong : u32) -> u32);
windows_link::link!("c" "C" fn ntohs(__netshort : u16) -> u16);
pub const INET6_ADDRSTRLEN: i32 = 46i32;
pub const INET_ADDRSTRLEN: i32 = 16i32;
pub const IN_CLASSA_MAX: i32 = 128i32;
pub const IN_CLASSA_NET: i32 = -16777216i32;
pub const IN_CLASSA_NSHIFT: i32 = 24i32;
pub const IN_CLASSB_MAX: i32 = 65536i32;
pub const IN_CLASSB_NET: i32 = -65536i32;
pub const IN_CLASSB_NSHIFT: i32 = 16i32;
pub const IN_CLASSC_NET: i32 = -256i32;
pub const IN_CLASSC_NSHIFT: i32 = 8i32;
pub const IN_LOOPBACKNET: i32 = 127i32;
pub const IPPORT_BIFFUDP: u32 = 512u32;
pub const IPPORT_CMDSERVER: u32 = 514u32;
pub const IPPORT_DAYTIME: u32 = 13u32;
pub const IPPORT_DISCARD: u32 = 9u32;
pub const IPPORT_ECHO: u32 = 7u32;
pub const IPPORT_EFSSERVER: u32 = 520u32;
pub const IPPORT_EXECSERVER: u32 = 512u32;
pub const IPPORT_FINGER: u32 = 79u32;
pub const IPPORT_FTP: u32 = 21u32;
pub const IPPORT_LOGINSERVER: u32 = 513u32;
pub const IPPORT_MTP: u32 = 57u32;
pub const IPPORT_NAMESERVER: u32 = 42u32;
pub const IPPORT_NETSTAT: u32 = 15u32;
pub const IPPORT_RESERVED: u32 = 1024u32;
pub const IPPORT_RJE: u32 = 77u32;
pub const IPPORT_ROUTESERVER: u32 = 520u32;
pub const IPPORT_SMTP: u32 = 25u32;
pub const IPPORT_SUPDUP: u32 = 95u32;
pub const IPPORT_SYSTAT: u32 = 11u32;
pub const IPPORT_TELNET: u32 = 23u32;
pub const IPPORT_TFTP: u32 = 69u32;
pub const IPPORT_TIMESERVER: u32 = 37u32;
pub const IPPORT_TTYLINK: u32 = 87u32;
pub const IPPORT_USERRESERVED: u32 = 5000u32;
pub const IPPORT_WHOIS: u32 = 43u32;
pub const IPPORT_WHOSERVER: u32 = 513u32;
pub const IPPROTO_AH: u32 = 51u32;
pub const IPPROTO_BEETPH: u32 = 94u32;
pub const IPPROTO_COMP: u32 = 108u32;
pub const IPPROTO_DCCP: u32 = 33u32;
pub const IPPROTO_DSTOPTS: u32 = 60u32;
pub const IPPROTO_EGP: u32 = 8u32;
pub const IPPROTO_ENCAP: u32 = 98u32;
pub const IPPROTO_ESP: u32 = 50u32;
pub const IPPROTO_ETHERNET: u32 = 143u32;
pub const IPPROTO_FRAGMENT: u32 = 44u32;
pub const IPPROTO_GRE: u32 = 47u32;
pub const IPPROTO_HOPOPTS: u32 = 0u32;
pub const IPPROTO_ICMP: u32 = 1u32;
pub const IPPROTO_ICMPV6: u32 = 58u32;
pub const IPPROTO_IDP: u32 = 22u32;
pub const IPPROTO_IGMP: u32 = 2u32;
pub const IPPROTO_IP: u32 = 0u32;
pub const IPPROTO_IPIP: u32 = 4u32;
pub const IPPROTO_IPV6: u32 = 41u32;
pub const IPPROTO_L2TP: u32 = 115u32;
pub const IPPROTO_MAX: u32 = 263u32;
pub const IPPROTO_MH: u32 = 135u32;
pub const IPPROTO_MPLS: u32 = 137u32;
pub const IPPROTO_MPTCP: u32 = 262u32;
pub const IPPROTO_MTP: u32 = 92u32;
pub const IPPROTO_NONE: u32 = 59u32;
pub const IPPROTO_PIM: u32 = 103u32;
pub const IPPROTO_PUP: u32 = 12u32;
pub const IPPROTO_RAW: u32 = 255u32;
pub const IPPROTO_ROUTING: u32 = 43u32;
pub const IPPROTO_RSVP: u32 = 46u32;
pub const IPPROTO_SCTP: u32 = 132u32;
pub const IPPROTO_TCP: u32 = 6u32;
pub const IPPROTO_TP: u32 = 29u32;
pub const IPPROTO_UDP: u32 = 17u32;
pub const IPPROTO_UDPLITE: u32 = 136u32;
pub const _ARPA_INET_H: i32 = 1i32;
pub const _NETINET_IN_H: i32 = 1i32;
#[repr(C, packed(8))]
#[cfg(feature = "Socket")]
#[derive(Clone, Copy)]
pub struct group_filter {
    pub gf_interface: u32,
    pub gf_group: super::Socket::sockaddr_storage,
    pub gf_fmode: u32,
    pub gf_numsrc: u32,
    pub gf_slist: [super::Socket::sockaddr_storage; 1],
}
#[cfg(feature = "Socket")]
impl Default for group_filter {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "Socket")]
#[derive(Clone, Copy, Default)]
pub struct group_req {
    pub gr_interface: u32,
    pub gr_group: super::Socket::sockaddr_storage,
}
#[repr(C, packed(8))]
#[cfg(feature = "Socket")]
#[derive(Clone, Copy, Default)]
pub struct group_source_req {
    pub gsr_interface: u32,
    pub gsr_group: super::Socket::sockaddr_storage,
    pub gsr_source: super::Socket::sockaddr_storage,
}
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub struct in6_addr {
    pub __in6_u: in6_addr___in6_u,
}
impl Default for in6_addr {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub union in6_addr___in6_u {
    pub __u6_addr8: [u8; 16],
    pub __u6_addr16: [u16; 8],
    pub __u6_addr32: [u32; 4],
}
impl Default for in6_addr___in6_u {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[derive(Clone, Copy, Default)]
pub struct in_addr {
    pub s_addr: in_addr_t,
}
pub type in_addr_t = u32;
pub type in_port_t = u16;
#[repr(C, packed(4))]
#[derive(Clone, Copy, Default)]
pub struct ip_mreq {
    pub imr_multiaddr: in_addr,
    pub imr_interface: in_addr,
}
#[repr(C, packed(4))]
#[derive(Clone, Copy, Default)]
pub struct ip_mreq_source {
    pub imr_multiaddr: in_addr,
    pub imr_interface: in_addr,
    pub imr_sourceaddr: in_addr,
}
#[repr(C, packed(4))]
#[derive(Clone, Copy, Default)]
pub struct ip_mreqn {
    pub imr_multiaddr: in_addr,
    pub imr_address: in_addr,
    pub imr_ifindex: i32,
}
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub struct ip_msfilter {
    pub imsf_multiaddr: in_addr,
    pub imsf_interface: in_addr,
    pub imsf_fmode: u32,
    pub imsf_numsrc: u32,
    pub imsf_slist: [in_addr; 1],
}
impl Default for ip_msfilter {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub struct ipv6_mreq {
    pub ipv6mr_multiaddr: in6_addr,
    pub ipv6mr_interface: u32,
}
impl Default for ipv6_mreq {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub struct sockaddr_in {
    pub sin_family: u16,
    pub sin_port: in_port_t,
    pub sin_addr: in_addr,
    pub sin_zero: [u8; 8],
}
impl Default for sockaddr_in {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub struct sockaddr_in6 {
    pub sin6_family: u16,
    pub sin6_port: in_port_t,
    pub sin6_flowinfo: u32,
    pub sin6_addr: in6_addr,
    pub sin6_scope_id: u32,
}
impl Default for sockaddr_in6 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
