// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("crypto" "C" fn BIO_ADDRINFO_address(bai : *const BIO_ADDRINFO) -> *mut BIO_ADDR);
windows_link::link!("crypto" "C" fn BIO_ADDRINFO_family(bai : *const BIO_ADDRINFO) -> i32);
windows_link::link!("crypto" "C" fn BIO_ADDRINFO_free(bai : *mut BIO_ADDRINFO));
windows_link::link!("crypto" "C" fn BIO_ADDRINFO_next(bai : *const BIO_ADDRINFO) -> *mut BIO_ADDRINFO);
windows_link::link!("crypto" "C" fn BIO_ADDRINFO_protocol(bai : *const BIO_ADDRINFO) -> i32);
windows_link::link!("crypto" "C" fn BIO_ADDRINFO_socktype(bai : *const BIO_ADDRINFO) -> i32);
windows_link::link!("crypto" "C" fn BIO_ADDR_clear(ap : *mut BIO_ADDR));
windows_link::link!("crypto" "C" fn BIO_ADDR_family(ap : *const BIO_ADDR) -> i32);
windows_link::link!("crypto" "C" fn BIO_ADDR_free(param0 : *mut BIO_ADDR));
windows_link::link!("crypto" "C" fn BIO_ADDR_hostname_string(ap : *const BIO_ADDR, numeric : i32) -> *mut i8);
windows_link::link!("crypto" "C" fn BIO_ADDR_new() -> *mut BIO_ADDR);
windows_link::link!("crypto" "C" fn BIO_ADDR_path_string(ap : *const BIO_ADDR) -> *mut i8);
windows_link::link!("crypto" "C" fn BIO_ADDR_rawaddress(ap : *const BIO_ADDR, p : *mut core::ffi::c_void, l : *mut u64) -> i32);
windows_link::link!("crypto" "C" fn BIO_ADDR_rawmake(ap : *mut BIO_ADDR, family : i32, r#where : *const core::ffi::c_void, wherelen : u64, port : u16) -> i32);
windows_link::link!("crypto" "C" fn BIO_ADDR_rawport(ap : *const BIO_ADDR) -> u16);
windows_link::link!("crypto" "C" fn BIO_ADDR_service_string(ap : *const BIO_ADDR, numeric : i32) -> *mut i8);
windows_link::link!("crypto" "C" fn BIO_accept(sock : i32, ip_port : *mut *mut i8) -> i32);
windows_link::link!("crypto" "C" fn BIO_accept_ex(accept_sock : i32, addr : *mut BIO_ADDR, options : i32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_asn1_get_prefix(b : *mut super::types:: BIO, pprefix : *mut *mut asn1_ps_func, pprefix_free : *mut *mut asn1_ps_func) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_asn1_get_suffix(b : *mut super::types:: BIO, psuffix : *mut *mut asn1_ps_func, psuffix_free : *mut *mut asn1_ps_func) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_asn1_set_prefix(b : *mut super::types:: BIO, prefix : *mut asn1_ps_func, prefix_free : *mut asn1_ps_func) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_asn1_set_suffix(b : *mut super::types:: BIO, suffix : *mut asn1_ps_func, suffix_free : *mut asn1_ps_func) -> i32);
windows_link::link!("crypto" "C" fn BIO_bind(sock : i32, addr : *const BIO_ADDR, options : i32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_callback_ctrl(b : *mut super::types:: BIO, cmd : i32, fp : *mut BIO_info_cb) -> i64);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_clear_flags(b : *mut super::types:: BIO, flags : i32));
windows_link::link!("crypto" "C" fn BIO_closesocket(sock : i32) -> i32);
windows_link::link!("crypto" "C" fn BIO_connect(sock : i32, addr : *const BIO_ADDR, options : i32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_copy_next_retry(b : *mut super::types:: BIO));
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_ctrl(bp : *mut super::types:: BIO, cmd : i32, larg : i64, parg : *mut core::ffi::c_void) -> i64);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_ctrl_get_read_request(b : *mut super::types:: BIO) -> u64);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_ctrl_get_write_guarantee(b : *mut super::types:: BIO) -> u64);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_ctrl_pending(b : *mut super::types:: BIO) -> u64);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_ctrl_reset_read_request(b : *mut super::types:: BIO) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_ctrl_wpending(b : *mut super::types:: BIO) -> u64);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_debug_callback(bio : *mut super::types:: BIO, cmd : i32, argp : *const i8, argi : i32, argl : i64, ret : i64) -> i64);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_debug_callback_ex(bio : *mut super::types:: BIO, oper : i32, argp : *const i8, len : u64, argi : i32, argl : i64, ret : i32, processed : *mut u64) -> i64);
windows_link::link!("crypto" "C" fn BIO_dgram_non_fatal_error(error : i32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_do_connect_retry(bio : *mut super::types:: BIO, timeout : i32, nap_milliseconds : i32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_dump(b : *mut super::types:: BIO, bytes : *const core::ffi::c_void, len : i32) -> i32);
windows_link::link!("crypto" "C" fn BIO_dump_cb(cb : *mut isize, u : *mut core::ffi::c_void, s : *const core::ffi::c_void, len : i32) -> i32);
#[cfg(feature = "crypto")]
windows_link::link!("crypto" "C" fn BIO_dump_fp(fp : *mut super::crypto:: _IO_FILE, s : *const core::ffi::c_void, len : i32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_dump_indent(b : *mut super::types:: BIO, bytes : *const core::ffi::c_void, len : i32, indent : i32) -> i32);
windows_link::link!("crypto" "C" fn BIO_dump_indent_cb(cb : *mut isize, u : *mut core::ffi::c_void, s : *const core::ffi::c_void, len : i32, indent : i32) -> i32);
#[cfg(feature = "crypto")]
windows_link::link!("crypto" "C" fn BIO_dump_indent_fp(fp : *mut super::crypto:: _IO_FILE, s : *const core::ffi::c_void, len : i32, indent : i32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_dup_chain(r#in : *mut super::types:: BIO) -> *mut super::types:: BIO);
windows_link::link!("crypto" "C" fn BIO_f_buffer() -> *mut BIO_METHOD);
windows_link::link!("crypto" "C" fn BIO_f_linebuffer() -> *mut BIO_METHOD);
windows_link::link!("crypto" "C" fn BIO_f_nbio_test() -> *mut BIO_METHOD);
windows_link::link!("crypto" "C" fn BIO_f_null() -> *mut BIO_METHOD);
windows_link::link!("crypto" "C" fn BIO_f_prefix() -> *mut BIO_METHOD);
windows_link::link!("crypto" "C" fn BIO_f_readbuffer() -> *mut BIO_METHOD);
windows_link::link!("crypto" "C" fn BIO_fd_non_fatal_error(error : i32) -> i32);
windows_link::link!("crypto" "C" fn BIO_fd_should_retry(i : i32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_find_type(b : *mut super::types:: BIO, bio_type : i32) -> *mut super::types:: BIO);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_free(a : *mut super::types:: BIO) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_free_all(a : *mut super::types:: BIO));
windows_link::link!("crypto" "C" fn BIO_get_accept_socket(host_port : *mut i8, mode : i32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_get_callback(b : *const super::types:: BIO) -> BIO_callback_fn);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_get_callback_arg(b : *const super::types:: BIO) -> *mut i8);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_get_callback_ex(b : *const super::types:: BIO) -> BIO_callback_fn_ex);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_get_data(a : *mut super::types:: BIO) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_get_ex_data(bio : *const super::types:: BIO, idx : i32) -> *mut core::ffi::c_void);
windows_link::link!("crypto" "C" fn BIO_get_host_ip(str : *const i8, ip : *mut u8) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_get_init(a : *mut super::types:: BIO) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_get_line(bio : *mut super::types:: BIO, buf : *mut i8, size : i32) -> i32);
windows_link::link!("crypto" "C" fn BIO_get_new_index() -> i32);
windows_link::link!("crypto" "C" fn BIO_get_port(str : *const i8, port_ptr : *mut u16) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_get_retry_BIO(bio : *mut super::types:: BIO, reason : *mut i32) -> *mut super::types:: BIO);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_get_retry_reason(bio : *mut super::types:: BIO) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_get_shutdown(a : *mut super::types:: BIO) -> i32);
windows_link::link!("crypto" "C" fn BIO_gethostbyname(name : *const i8) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_gets(bp : *mut super::types:: BIO, buf : *mut i8, size : i32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_hex_string(out : *mut super::types:: BIO, indent : i32, width : i32, data : *const core::ffi::c_void, datalen : i32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_indent(b : *mut super::types:: BIO, indent : i32, max : i32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_int_ctrl(bp : *mut super::types:: BIO, cmd : i32, larg : i64, iarg : i32) -> i64);
windows_link::link!("crypto" "C" fn BIO_listen(sock : i32, addr : *const BIO_ADDR, options : i32) -> i32);
windows_link::link!("crypto" "C" fn BIO_lookup(host : *const i8, service : *const i8, lookup_type : BIO_lookup_type, family : i32, socktype : i32, res : *mut *mut BIO_ADDRINFO) -> i32);
windows_link::link!("crypto" "C" fn BIO_lookup_ex(host : *const i8, service : *const i8, lookup_type : i32, family : i32, socktype : i32, protocol : i32, res : *mut *mut BIO_ADDRINFO) -> i32);
windows_link::link!("crypto" "C" fn BIO_meth_free(biom : *mut BIO_METHOD));
windows_link::link!("crypto" "C" fn BIO_meth_get_callback_ctrl(biom : *const BIO_METHOD) -> *mut isize);
windows_link::link!("crypto" "C" fn BIO_meth_get_create(bion : *const BIO_METHOD) -> *mut isize);
windows_link::link!("crypto" "C" fn BIO_meth_get_ctrl(biom : *const BIO_METHOD) -> *mut isize);
windows_link::link!("crypto" "C" fn BIO_meth_get_destroy(biom : *const BIO_METHOD) -> *mut isize);
windows_link::link!("crypto" "C" fn BIO_meth_get_gets(biom : *const BIO_METHOD) -> *mut isize);
windows_link::link!("crypto" "C" fn BIO_meth_get_puts(biom : *const BIO_METHOD) -> *mut isize);
windows_link::link!("crypto" "C" fn BIO_meth_get_read(biom : *const BIO_METHOD) -> *mut isize);
windows_link::link!("crypto" "C" fn BIO_meth_get_read_ex(biom : *const BIO_METHOD) -> *mut isize);
windows_link::link!("crypto" "C" fn BIO_meth_get_write(biom : *const BIO_METHOD) -> *mut isize);
windows_link::link!("crypto" "C" fn BIO_meth_get_write_ex(biom : *const BIO_METHOD) -> *mut isize);
windows_link::link!("crypto" "C" fn BIO_meth_new(r#type : i32, name : *const i8) -> *mut BIO_METHOD);
windows_link::link!("crypto" "C" fn BIO_meth_set_callback_ctrl(biom : *mut BIO_METHOD, callback_ctrl : *mut isize) -> i32);
windows_link::link!("crypto" "C" fn BIO_meth_set_create(biom : *mut BIO_METHOD, create : *mut isize) -> i32);
windows_link::link!("crypto" "C" fn BIO_meth_set_ctrl(biom : *mut BIO_METHOD, ctrl : *mut isize) -> i32);
windows_link::link!("crypto" "C" fn BIO_meth_set_destroy(biom : *mut BIO_METHOD, destroy : *mut isize) -> i32);
windows_link::link!("crypto" "C" fn BIO_meth_set_gets(biom : *mut BIO_METHOD, ossl_gets : *mut isize) -> i32);
windows_link::link!("crypto" "C" fn BIO_meth_set_puts(biom : *mut BIO_METHOD, puts : *mut isize) -> i32);
windows_link::link!("crypto" "C" fn BIO_meth_set_read(biom : *mut BIO_METHOD, read : *mut isize) -> i32);
windows_link::link!("crypto" "C" fn BIO_meth_set_read_ex(biom : *mut BIO_METHOD, bread : *mut isize) -> i32);
windows_link::link!("crypto" "C" fn BIO_meth_set_write(biom : *mut BIO_METHOD, write : *mut isize) -> i32);
windows_link::link!("crypto" "C" fn BIO_meth_set_write_ex(biom : *mut BIO_METHOD, bwrite : *mut isize) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_method_name(b : *const super::types:: BIO) -> *mut i8);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_method_type(b : *const super::types:: BIO) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_new(r#type : *const BIO_METHOD) -> *mut super::types:: BIO);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_new_accept(host_port : *const i8) -> *mut super::types:: BIO);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_new_bio_pair(bio1 : *mut *mut super::types:: BIO, writebuf1 : u64, bio2 : *mut *mut super::types:: BIO, writebuf2 : u64) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_new_connect(host_port : *const i8) -> *mut super::types:: BIO);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_new_dgram(fd : i32, close_flag : i32) -> *mut super::types:: BIO);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_new_ex(libctx : *mut super::types:: OSSL_LIB_CTX, method : *const BIO_METHOD) -> *mut super::types:: BIO);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_new_fd(fd : i32, close_flag : i32) -> *mut super::types:: BIO);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_new_file(filename : *const i8, mode : *const i8) -> *mut super::types:: BIO);
#[cfg(all(feature = "crypto", feature = "types"))]
windows_link::link!("crypto" "C" fn BIO_new_fp(stream : *mut super::crypto:: _IO_FILE, close_flag : i32) -> *mut super::types:: BIO);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_new_from_core_bio(libctx : *mut super::types:: OSSL_LIB_CTX, corebio : *mut core::ffi::c_void) -> *mut super::types:: BIO);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_new_mem_buf(buf : *const core::ffi::c_void, len : i32) -> *mut super::types:: BIO);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_new_socket(sock : i32, close_flag : i32) -> *mut super::types:: BIO);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_next(b : *mut super::types:: BIO) -> *mut super::types:: BIO);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_nread(bio : *mut super::types:: BIO, buf : *mut *mut i8, num : i32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_nread0(bio : *mut super::types:: BIO, buf : *mut *mut i8) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_number_read(bio : *mut super::types:: BIO) -> u64);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_number_written(bio : *mut super::types:: BIO) -> u64);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_nwrite(bio : *mut super::types:: BIO, buf : *mut *mut i8, num : i32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_nwrite0(bio : *mut super::types:: BIO, buf : *mut *mut i8) -> i32);
windows_link::link!("crypto" "C" fn BIO_parse_hostserv(hostserv : *const i8, host : *mut *mut i8, service : *mut *mut i8, hostserv_prio : BIO_hostserv_priorities) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_pop(b : *mut super::types:: BIO) -> *mut super::types:: BIO);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_ptr_ctrl(bp : *mut super::types:: BIO, cmd : i32, larg : i64) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_push(b : *mut super::types:: BIO, append : *mut super::types:: BIO) -> *mut super::types:: BIO);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_puts(bp : *mut super::types:: BIO, buf : *const i8) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_read(b : *mut super::types:: BIO, data : *mut core::ffi::c_void, dlen : i32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_read_ex(b : *mut super::types:: BIO, data : *mut core::ffi::c_void, dlen : u64, readbytes : *mut u64) -> i32);
windows_link::link!("crypto" "C" fn BIO_s_accept() -> *mut BIO_METHOD);
windows_link::link!("crypto" "C" fn BIO_s_bio() -> *mut BIO_METHOD);
windows_link::link!("crypto" "C" fn BIO_s_connect() -> *mut BIO_METHOD);
windows_link::link!("crypto" "C" fn BIO_s_core() -> *mut BIO_METHOD);
windows_link::link!("crypto" "C" fn BIO_s_datagram() -> *mut BIO_METHOD);
windows_link::link!("crypto" "C" fn BIO_s_fd() -> *mut BIO_METHOD);
windows_link::link!("crypto" "C" fn BIO_s_file() -> *mut BIO_METHOD);
windows_link::link!("crypto" "C" fn BIO_s_log() -> *mut BIO_METHOD);
windows_link::link!("crypto" "C" fn BIO_s_mem() -> *mut BIO_METHOD);
windows_link::link!("crypto" "C" fn BIO_s_null() -> *mut BIO_METHOD);
windows_link::link!("crypto" "C" fn BIO_s_secmem() -> *mut BIO_METHOD);
windows_link::link!("crypto" "C" fn BIO_s_socket() -> *mut BIO_METHOD);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_set_callback(b : *mut super::types:: BIO, callback : BIO_callback_fn));
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_set_callback_arg(b : *mut super::types:: BIO, arg : *mut i8));
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_set_callback_ex(b : *mut super::types:: BIO, callback : BIO_callback_fn_ex));
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_set_data(a : *mut super::types:: BIO, ptr : *mut core::ffi::c_void));
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_set_ex_data(bio : *mut super::types:: BIO, idx : i32, data : *mut core::ffi::c_void) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_set_flags(b : *mut super::types:: BIO, flags : i32));
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_set_init(a : *mut super::types:: BIO, init : i32));
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_set_next(b : *mut super::types:: BIO, next : *mut super::types:: BIO));
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_set_retry_reason(bio : *mut super::types:: BIO, reason : i32));
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_set_shutdown(a : *mut super::types:: BIO, shut : i32));
windows_link::link!("crypto" "C" fn BIO_set_tcp_ndelay(sock : i32, turn_on : i32) -> i32);
windows_link::link!("crypto" "C" fn BIO_sock_error(sock : i32) -> i32);
windows_link::link!("crypto" "C" fn BIO_sock_info(sock : i32, r#type : BIO_sock_info_type, info : *mut BIO_sock_info_u) -> i32);
windows_link::link!("crypto" "C" fn BIO_sock_init() -> i32);
windows_link::link!("crypto" "C" fn BIO_sock_non_fatal_error(error : i32) -> i32);
windows_link::link!("crypto" "C" fn BIO_sock_should_retry(i : i32) -> i32);
windows_link::link!("crypto" "C" fn BIO_socket(domain : i32, socktype : i32, protocol : i32, options : i32) -> i32);
windows_link::link!("crypto" "C" fn BIO_socket_ioctl(fd : i32, r#type : i64, arg : *mut core::ffi::c_void) -> i32);
windows_link::link!("crypto" "C" fn BIO_socket_nbio(fd : i32, mode : i32) -> i32);
windows_link::link!("crypto" "C" fn BIO_socket_wait(fd : i32, for_read : i32, max_time : i64) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_test_flags(b : *const super::types:: BIO, flags : i32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_up_ref(a : *mut super::types:: BIO) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_vfree(a : *mut super::types:: BIO));
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_vprintf(bio : *mut super::types:: BIO, format : *const i8, args : *mut core::ffi::c_void) -> i32);
windows_link::link!("crypto" "C" fn BIO_vsnprintf(buf : *mut i8, n : u64, format : *const i8, args : *mut core::ffi::c_void) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_wait(bio : *mut super::types:: BIO, max_time : i64, nap_milliseconds : u32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_write(b : *mut super::types:: BIO, data : *const core::ffi::c_void, dlen : i32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn BIO_write_ex(b : *mut super::types:: BIO, data : *const core::ffi::c_void, dlen : u64, written : *mut u64) -> i32);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn ossl_check_BIO_compfunc_type(cmp : sk_BIO_compfunc) -> *mut isize);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn ossl_check_BIO_copyfunc_type(cpy : sk_BIO_copyfunc) -> *mut isize);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn ossl_check_BIO_freefunc_type(fr : sk_BIO_freefunc) -> *mut isize);
windows_link::link!("crypto" "C" fn ossl_check_BIO_sk_type(sk : *mut core::ffi::c_void) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("crypto" "C" fn ossl_check_BIO_type(ptr : *mut super::types:: BIO) -> *mut super::types:: BIO);
windows_link::link!("crypto" "C" fn ossl_check_const_BIO_sk_type(sk : *const core::ffi::c_void) -> *mut core::ffi::c_void);
pub type BIO_ADDR = isize;
pub type BIO_ADDRINFO = isize;
pub const BIO_BIND_NORMAL: i32 = 0i32;
pub const BIO_CB_CTRL: i32 = 6i32;
pub const BIO_CB_FREE: i32 = 1i32;
pub const BIO_CB_GETS: i32 = 5i32;
pub const BIO_CB_PUTS: i32 = 4i32;
pub const BIO_CB_READ: i32 = 2i32;
pub const BIO_CB_RETURN: i32 = 128i32;
pub const BIO_CB_WRITE: i32 = 3i32;
pub const BIO_CLOSE: i32 = 1i32;
pub const BIO_CTRL_DGRAM_CONNECT: i32 = 31i32;
pub const BIO_CTRL_DGRAM_GET_FALLBACK_MTU: i32 = 47i32;
pub const BIO_CTRL_DGRAM_GET_MTU: i32 = 41i32;
pub const BIO_CTRL_DGRAM_GET_MTU_OVERHEAD: i32 = 49i32;
pub const BIO_CTRL_DGRAM_GET_PEER: i32 = 46i32;
pub const BIO_CTRL_DGRAM_GET_RECV_TIMEOUT: i32 = 34i32;
pub const BIO_CTRL_DGRAM_GET_RECV_TIMER_EXP: i32 = 37i32;
pub const BIO_CTRL_DGRAM_GET_SEND_TIMEOUT: i32 = 36i32;
pub const BIO_CTRL_DGRAM_GET_SEND_TIMER_EXP: i32 = 38i32;
pub const BIO_CTRL_DGRAM_MTU_DISCOVER: i32 = 39i32;
pub const BIO_CTRL_DGRAM_MTU_EXCEEDED: i32 = 43i32;
pub const BIO_CTRL_DGRAM_QUERY_MTU: i32 = 40i32;
pub const BIO_CTRL_DGRAM_SCTP_MSG_WAITING: i32 = 78i32;
pub const BIO_CTRL_DGRAM_SCTP_SET_IN_HANDSHAKE: i32 = 50i32;
pub const BIO_CTRL_DGRAM_SCTP_WAIT_FOR_DRY: i32 = 77i32;
pub const BIO_CTRL_DGRAM_SET_CONNECTED: i32 = 32i32;
pub const BIO_CTRL_DGRAM_SET_DONT_FRAG: i32 = 48i32;
pub const BIO_CTRL_DGRAM_SET_MTU: i32 = 42i32;
pub const BIO_CTRL_DGRAM_SET_NEXT_TIMEOUT: i32 = 45i32;
pub const BIO_CTRL_DGRAM_SET_PEEK_MODE: i32 = 71i32;
pub const BIO_CTRL_DGRAM_SET_PEER: i32 = 44i32;
pub const BIO_CTRL_DGRAM_SET_RECV_TIMEOUT: i32 = 33i32;
pub const BIO_CTRL_DGRAM_SET_SEND_TIMEOUT: i32 = 35i32;
pub const BIO_CTRL_DUP: i32 = 12i32;
pub const BIO_CTRL_EOF: i32 = 2i32;
pub const BIO_CTRL_FLUSH: i32 = 11i32;
pub const BIO_CTRL_GET: i32 = 5i32;
pub const BIO_CTRL_GET_CALLBACK: i32 = 15i32;
pub const BIO_CTRL_GET_CLOSE: i32 = 8i32;
pub const BIO_CTRL_GET_INDENT: i32 = 81i32;
pub const BIO_CTRL_GET_KTLS_RECV: i32 = 76i32;
pub const BIO_CTRL_GET_KTLS_SEND: i32 = 73i32;
pub const BIO_CTRL_INFO: i32 = 3i32;
pub const BIO_CTRL_PEEK: i32 = 29i32;
pub const BIO_CTRL_PENDING: i32 = 10i32;
pub const BIO_CTRL_POP: i32 = 7i32;
pub const BIO_CTRL_PUSH: i32 = 6i32;
pub const BIO_CTRL_RESET: i32 = 1i32;
pub const BIO_CTRL_SET: i32 = 4i32;
pub const BIO_CTRL_SET_CALLBACK: i32 = 14i32;
pub const BIO_CTRL_SET_CLOSE: i32 = 9i32;
pub const BIO_CTRL_SET_FILENAME: i32 = 30i32;
pub const BIO_CTRL_SET_INDENT: i32 = 80i32;
pub const BIO_CTRL_SET_PREFIX: i32 = 79i32;
pub const BIO_CTRL_WPENDING: i32 = 13i32;
pub const BIO_C_DESTROY_BIO_PAIR: i32 = 139i32;
pub const BIO_C_DO_STATE_MACHINE: i32 = 101i32;
pub const BIO_C_FILE_SEEK: i32 = 128i32;
pub const BIO_C_FILE_TELL: i32 = 133i32;
pub const BIO_C_GET_ACCEPT: i32 = 124i32;
pub const BIO_C_GET_BIND_MODE: i32 = 132i32;
pub const BIO_C_GET_BUFF_NUM_LINES: i32 = 116i32;
pub const BIO_C_GET_BUF_MEM_PTR: i32 = 115i32;
pub const BIO_C_GET_CIPHER_CTX: i32 = 129i32;
pub const BIO_C_GET_CIPHER_STATUS: i32 = 113i32;
pub const BIO_C_GET_CONNECT: i32 = 123i32;
pub const BIO_C_GET_EX_ARG: i32 = 154i32;
pub const BIO_C_GET_FD: i32 = 105i32;
pub const BIO_C_GET_FILE_PTR: i32 = 107i32;
pub const BIO_C_GET_MD: i32 = 112i32;
pub const BIO_C_GET_MD_CTX: i32 = 120i32;
pub const BIO_C_GET_PREFIX: i32 = 150i32;
pub const BIO_C_GET_READ_REQUEST: i32 = 141i32;
pub const BIO_C_GET_SOCKS: i32 = 134i32;
pub const BIO_C_GET_SSL: i32 = 110i32;
pub const BIO_C_GET_SSL_NUM_RENEGOTIATES: i32 = 126i32;
pub const BIO_C_GET_SUFFIX: i32 = 152i32;
pub const BIO_C_GET_WRITE_BUF_SIZE: i32 = 137i32;
pub const BIO_C_GET_WRITE_GUARANTEE: i32 = 140i32;
pub const BIO_C_MAKE_BIO_PAIR: i32 = 138i32;
pub const BIO_C_NREAD: i32 = 144i32;
pub const BIO_C_NREAD0: i32 = 143i32;
pub const BIO_C_NWRITE: i32 = 146i32;
pub const BIO_C_NWRITE0: i32 = 145i32;
pub const BIO_C_RESET_READ_REQUEST: i32 = 147i32;
pub const BIO_C_SET_ACCEPT: i32 = 118i32;
pub const BIO_C_SET_BIND_MODE: i32 = 131i32;
pub const BIO_C_SET_BUFF_READ_DATA: i32 = 122i32;
pub const BIO_C_SET_BUFF_SIZE: i32 = 117i32;
pub const BIO_C_SET_BUF_MEM: i32 = 114i32;
pub const BIO_C_SET_BUF_MEM_EOF_RETURN: i32 = 130i32;
pub const BIO_C_SET_CONNECT: i32 = 100i32;
pub const BIO_C_SET_CONNECT_MODE: i32 = 155i32;
pub const BIO_C_SET_EX_ARG: i32 = 153i32;
pub const BIO_C_SET_FD: i32 = 104i32;
pub const BIO_C_SET_FILENAME: i32 = 108i32;
pub const BIO_C_SET_FILE_PTR: i32 = 106i32;
pub const BIO_C_SET_MD: i32 = 111i32;
pub const BIO_C_SET_MD_CTX: i32 = 148i32;
pub const BIO_C_SET_NBIO: i32 = 102i32;
pub const BIO_C_SET_PREFIX: i32 = 149i32;
pub const BIO_C_SET_SOCKS: i32 = 135i32;
pub const BIO_C_SET_SSL: i32 = 109i32;
pub const BIO_C_SET_SSL_RENEGOTIATE_BYTES: i32 = 125i32;
pub const BIO_C_SET_SSL_RENEGOTIATE_TIMEOUT: i32 = 127i32;
pub const BIO_C_SET_SUFFIX: i32 = 151i32;
pub const BIO_C_SET_WRITE_BUF_SIZE: i32 = 136i32;
pub const BIO_C_SHUTDOWN_WR: i32 = 142i32;
pub const BIO_C_SSL_MODE: i32 = 119i32;
pub const BIO_FAMILY_IPANY: i32 = 256i32;
pub const BIO_FAMILY_IPV4: i32 = 4i32;
pub const BIO_FAMILY_IPV6: i32 = 6i32;
pub const BIO_FLAGS_BASE64_NO_NL: i32 = 256i32;
pub const BIO_FLAGS_IN_EOF: i32 = 2048i32;
pub const BIO_FLAGS_IO_SPECIAL: i32 = 4i32;
pub const BIO_FLAGS_MEM_RDONLY: i32 = 512i32;
pub const BIO_FLAGS_NONCLEAR_RST: i32 = 1024i32;
pub const BIO_FLAGS_READ: i32 = 1i32;
pub const BIO_FLAGS_SHOULD_RETRY: i32 = 8i32;
pub const BIO_FLAGS_UPLINK: i32 = 0i32;
pub const BIO_FLAGS_WRITE: i32 = 2i32;
pub const BIO_FP_APPEND: i32 = 8i32;
pub const BIO_FP_READ: i32 = 2i32;
pub const BIO_FP_TEXT: i32 = 16i32;
pub const BIO_FP_WRITE: i32 = 4i32;
pub const BIO_LOOKUP_CLIENT: u32 = 0u32;
pub const BIO_LOOKUP_SERVER: u32 = 1u32;
pub type BIO_METHOD = isize;
pub const BIO_NOCLOSE: i32 = 0i32;
pub const BIO_PARSE_PRIO_HOST: u32 = 0u32;
pub const BIO_PARSE_PRIO_SERV: u32 = 1u32;
pub const BIO_RR_ACCEPT: i32 = 3i32;
pub const BIO_RR_CONNECT: i32 = 2i32;
pub const BIO_RR_SSL_X509_LOOKUP: i32 = 1i32;
pub const BIO_SOCK_INFO_ADDRESS: u32 = 0u32;
pub const BIO_SOCK_KEEPALIVE: i32 = 4i32;
pub const BIO_SOCK_NODELAY: i32 = 16i32;
pub const BIO_SOCK_NONBLOCK: i32 = 8i32;
pub const BIO_SOCK_REUSEADDR: i32 = 1i32;
pub const BIO_SOCK_V6_ONLY: i32 = 2i32;
pub const BIO_TYPE_DESCRIPTOR: i32 = 256i32;
pub const BIO_TYPE_FILTER: i32 = 512i32;
pub const BIO_TYPE_NONE: i32 = 0i32;
pub const BIO_TYPE_SOURCE_SINK: i32 = 1024i32;
pub const BIO_TYPE_START: i32 = 128i32;
#[cfg(feature = "types")]
pub type BIO_callback_fn = Option<
    unsafe extern "system" fn(
        param0: *const super::types::BIO,
        param1: i32,
        param2: *const i8,
        param3: i32,
        param4: i64,
        param5: i64,
    ) -> i64,
>;
#[cfg(feature = "types")]
pub type BIO_callback_fn_ex = Option<
    unsafe extern "system" fn(
        param0: *const super::types::BIO,
        param1: i32,
        param2: *const i8,
        param3: u64,
        param4: i32,
        param5: i64,
        param6: i32,
        param7: *const u64,
    ) -> i64,
>;
#[cfg(feature = "types")]
pub type BIO_dgram_sctp_notification_handler_fn = Option<
    unsafe extern "system" fn(
        param0: *const super::types::BIO,
        param1: *const core::ffi::c_void,
        param2: *const core::ffi::c_void,
    ),
>;
pub type BIO_hostserv_priorities = u32;
#[cfg(feature = "types")]
pub type BIO_info_cb = Option<
    unsafe extern "system" fn(param0: *const super::types::BIO, param1: i32, param2: i32) -> i32,
>;
pub type BIO_lookup_type = u32;
pub type BIO_sock_info_type = u32;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub union BIO_sock_info_u {
    pub addr: *mut BIO_ADDR,
}
impl Default for BIO_sock_info_u {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[cfg(feature = "types")]
pub type asn1_ps_func = Option<
    unsafe extern "system" fn(
        param0: *const super::types::BIO,
        param1: *const *const u8,
        param2: *const i32,
        param3: *const core::ffi::c_void,
    ) -> i32,
>;
pub type bio_info_cb = BIO_info_cb;
#[cfg(feature = "types")]
pub type sk_BIO_compfunc = Option<
    unsafe extern "system" fn(
        param0: *const *const super::types::BIO,
        param1: *const *const super::types::BIO,
    ) -> i32,
>;
#[cfg(feature = "types")]
pub type sk_BIO_copyfunc =
    Option<unsafe extern "system" fn(param0: *const super::types::BIO) -> *mut super::types::BIO>;
#[cfg(feature = "types")]
pub type sk_BIO_freefunc = Option<unsafe extern "system" fn(param0: *const super::types::BIO)>;
