[package]
name = "bnd-linux"
version = "0.0.8"
edition.workspace = true
description = "Rust FFI bindings for POSIX and Linux system APIs generated through bnd-clang"
authors.workspace = true
repository.workspace = true
license.workspace = true
documentation = "https://docs.rs/bnd-linux"
readme = "README.md"
keywords = ["linux", "posix", "ffi", "bindings"]
categories = ["external-ffi-bindings", "os::linux-apis"]

[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
bnd-macros.workspace = true

[dev-dependencies]
libc = "0.2"
tempfile.workspace = true

[features]
default = [
    "__fpos_t",
    "__locale_t",
    "__mbstate_t",
    "__sigset_t",
    "__sigval_t",
    "atomic_wide_counter",
    "clock_t",
    "clockid_t",
    "cookie_io_functions_t",
    "cpu_set",
    "dirent",
    "dlfcn",
    "epoll",
    "errno",
    "errno_base",
    "eventfd",
    "fcntl",
    "fcntl_linux",
    "file",
    "in_",
    "inet",
    "inotify",
    "int_ll64",
    "locale_t",
    "mman",
    "mman_linux",
    "mman_map_flags_generic",
    "mount",
    "netdb",
    "pthread",
    "pthread_stack_min",
    "pthreadtypes",
    "sched",
    "sendfile",
    "setjmp",
    "sigaction",
    "sigcontext",
    "sigevent_t",
    "siginfo_t",
    "signal",
    "sigset_t",
    "signalfd",
    "signum_arch",
    "signum_generic",
    "sockaddr",
    "socket",
    "socket_type",
    "stack_t",
    "stat",
    "stdio",
    "stdio_lim",
    "struct___jmp_buf_tag",
    "struct_file",
    "struct_iovec",
    "struct_itimerspec",
    "struct_mutex",
    "struct_rwlock",
    "struct_sched_param",
    "struct_sigstack",
    "struct_stat",
    "struct_timespec",
    "struct_timeval",
    "struct_tm",
    "thread_shared_types",
    "time",
    "time_t",
    "timer_t",
    "timerfd",
    "types",
    "typesizes",
    "unistd",
    "xattr",
]
Foundation = []
# generated features
__fpos_t = ["__mbstate_t", "types"]
__locale_t = []
__mbstate_t = []
__sigset_t = []
__sigval_t = []
atomic_wide_counter = []
clock_t = ["types"]
clockid_t = ["types"]
cookie_io_functions_t = ["types"]
cpu_set = []
dirent = ["types"]
dlfcn = []
epoll = ["__sigset_t", "struct_timespec", "types"]
errno = []
errno_base = []
eventfd = []
fcntl = ["types"]
fcntl_linux = []
file = ["struct_file", "types"]
in_ = ["sockaddr", "socket"]
inet = ["in_", "types", "unistd"]
inotify = []
int_ll64 = []
locale_t = ["__locale_t"]
mman = ["types"]
mman_linux = []
mman_map_flags_generic = []
mount = []
netdb = ["sockaddr", "socket", "types", "unistd"]
pthread = ["__sigset_t", "atomic_wide_counter", "pthreadtypes", "setjmp", "struct___jmp_buf_tag", "struct_mutex", "struct_rwlock", "struct_sched_param", "struct_timespec", "thread_shared_types", "types"]
pthread_stack_min = []
pthreadtypes = ["atomic_wide_counter", "struct_mutex", "struct_rwlock", "thread_shared_types"]
sched = ["struct_sched_param", "struct_timespec", "types"]
sendfile = ["types"]
setjmp = []
sigaction = []
sigcontext = ["types"]
sigevent_t = ["__sigval_t", "pthreadtypes", "types"]
siginfo_t = ["__sigval_t", "types"]
signal = ["__sigset_t", "__sigval_t", "sigcontext", "siginfo_t", "sigset_t", "stack_t", "struct_timespec", "types"]
signalfd = ["__sigset_t", "sigset_t"]
signum_arch = []
signum_generic = []
sigset_t = ["__sigset_t"]
sockaddr = []
socket = ["sockaddr", "struct_iovec", "types", "unistd"]
socket_type = []
stack_t = []
stat = ["struct_stat", "struct_timespec", "types"]
stdio = ["__fpos_t", "__mbstate_t", "cookie_io_functions_t", "file", "struct_file", "types"]
stdio_lim = []
struct___jmp_buf_tag = ["__sigset_t", "setjmp"]
struct_file = ["types"]
struct_iovec = []
struct_itimerspec = ["struct_timespec", "types"]
struct_mutex = ["thread_shared_types"]
struct_rwlock = []
struct_sched_param = []
struct_sigstack = []
struct_stat = ["struct_timespec", "types"]
struct_timespec = ["types"]
struct_timeval = ["types"]
struct_tm = []
thread_shared_types = ["atomic_wide_counter"]
time = ["__locale_t", "__sigval_t", "clock_t", "clockid_t", "locale_t", "pthreadtypes", "sigevent_t", "struct_itimerspec", "struct_timespec", "struct_timeval", "struct_tm", "time_t", "timer_t", "types"]
time_t = ["types"]
timer_t = ["types"]
timerfd = ["struct_itimerspec", "struct_timespec", "types"]
types = ["int_ll64", "typesizes"]
typesizes = []
unistd = ["types"]
xattr = ["types"]
