name: build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-26.04 ]
    steps:
    - uses: actions/checkout@v7

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libclang-dev zlib1g-dev

    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v2
      with:
        components: rustfmt, clippy, llvm-tools

    - uses: taiki-e/install-action@cargo-llvm-cov

    - name: Run cargo check
      run: cargo check

    - name: Run cargo fmt
      run: cargo fmt --all -- --check
    
    - name: Run cargo clippy
      run: cargo clippy --all-targets -- -D warnings
    
    - name: Run cargo build
      run: cargo build --all-targets

    - name: Run cargo test
      run: cargo test --all -- --nocapture

    - name: Check no uncommitted changes
      run: |
        git diff --exit-code
        git diff --cached --exit-code