name: build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-26.04 ]
    steps:
    - uses: actions/checkout@v7

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libclang-dev zlib1g-dev

    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v2
      with:
        components: rustfmt, clippy, llvm-tools

    - uses: taiki-e/install-action@just

    - uses: taiki-e/install-action@cargo-llvm-cov

    - name: Run CI
      run: just ci
